using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using nORM.Core;
using nORM.Providers;
using Xunit;

#nullable enable

namespace nORM.Tests;

/// <summary>
/// A single-column integer primary key with no explicit configuration is a convention store-generated key:
/// Add + SaveChanges omits it from the INSERT and lets the database assign it. A bulk insert of the same
/// entity with a default (0) key must behave the same way — it must NOT write the literal 0 into the key,
/// which on SQLite (rowid alias) and PostgreSQL (GENERATED BY DEFAULT) is stored verbatim, corrupting the row.
/// </summary>
[Xunit.Trait("Category", "Fast")]
public class BulkInsertConventionKeyTests
{
    [Table("BckFoo")]
    private sealed class Foo
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
    }

    private static DbContext Create()
    {
        var cn = new SqliteConnection("Data Source=:memory:");
        cn.Open();
        using (var cmd = cn.CreateCommand())
        {
            cmd.CommandText = "CREATE TABLE BckFoo (Id INTEGER PRIMARY KEY, Name TEXT NOT NULL)";
            cmd.ExecuteNonQuery();
        }
        return new DbContext(cn, new SqliteProvider());
    }

    // Oracle: the NORMAL Add + SaveChanges path treats a default (0) convention key as store-generated.
    // Bulk insert must match this — the two paths cannot disagree on what a 0 key means.
    [Fact]
    public async Task Normal_add_of_default_convention_key_lets_db_generate()
    {
        await using var ctx = Create();
        var foo = new Foo { Name = "a" }; // Id defaults to 0
        ctx.Add(foo);
        await ctx.SaveChangesAsync();
        Assert.NotEqual(0, foo.Id);
    }

    [Fact]
    public async Task Bulk_insert_of_convention_key_entity_lets_db_generate_the_key()
    {
        await using var ctx = Create();

        await ctx.BulkInsertAsync(new[] { new Foo { Name = "a" } });

        // The stored row must have a DB-generated key (rowid = 1), NOT the literal 0 the entity carried.
        await using var cmd = ctx.Connection.CreateCommand();
        cmd.CommandText = "SELECT Id FROM BckFoo WHERE Name = 'a'";
        var storedId = System.Convert.ToInt64(await cmd.ExecuteScalarAsync());
        Assert.NotEqual(0L, storedId);
    }

    [Fact]
    public async Task Bulk_insert_multiple_convention_key_entities_get_distinct_keys()
    {
        await using var ctx = Create();

        await ctx.BulkInsertAsync(new[] { new Foo { Name = "a" }, new Foo { Name = "b" }, new Foo { Name = "c" } });

        await using var cmd = ctx.Connection.CreateCommand();
        cmd.CommandText = "SELECT COUNT(DISTINCT Id) FROM BckFoo";
        var distinct = System.Convert.ToInt64(await cmd.ExecuteScalarAsync());
        Assert.Equal(3L, distinct);
    }

    [Fact]
    public async Task Bulk_insert_mixed_explicit_and_default_keys_honors_explicit_and_generates_the_rest()
    {
        await using var ctx = Create();

        await ctx.BulkInsertAsync(new[]
        {
            new Foo { Id = 100, Name = "explicit" },
            new Foo { Name = "generated" },
        });

        await using var cmd = ctx.Connection.CreateCommand();
        cmd.CommandText = "SELECT Id FROM BckFoo WHERE Name = 'explicit'";
        Assert.Equal(100L, System.Convert.ToInt64(await cmd.ExecuteScalarAsync()));

        await using var cmd2 = ctx.Connection.CreateCommand();
        cmd2.CommandText = "SELECT Id FROM BckFoo WHERE Name = 'generated'";
        var genId = System.Convert.ToInt64(await cmd2.ExecuteScalarAsync());
        Assert.NotEqual(0L, genId);
        Assert.NotEqual(100L, genId);
    }
}
