using System;
using System.Data.Common;
using System.Threading.Tasks;
using nORM.Core;
using nORM.Providers;
using Xunit;

#nullable enable

namespace nORM.Tests;

/// <summary>
/// The write-path state machines against real servers: the same seeded
/// mutation sequences that validate tracking, batching, relationship fixup,
/// and optimistic concurrency on SQLite here run through each provider's
/// batched-write emission, parameter handling, generated-key backfill, and
/// client-managed concurrency token.
/// </summary>
[Trait("Category", TestCategory.LiveProvider)]
public class CrudStateMachineFuzzLiveTests
{
    private static (Func<DbConnection>?, DatabaseProvider?, string?) OpenLive(string kind)
    {
        switch (kind)
        {
            case "mysql":
            {
                var cs = LiveProviderEnvironment.GetByCanonicalName("NORM_TEST_MYSQL");
                if (string.IsNullOrEmpty(cs)) return (null, null, "NORM_TEST_MYSQL not set");
                // Matched-rows semantics are required for [Timestamp] optimistic
                // concurrency (the provider fails closed otherwise).
                if (!cs.Contains("UseAffectedRows", StringComparison.OrdinalIgnoreCase))
                    cs = cs.TrimEnd(';') + ";UseAffectedRows=false";
                var t = Type.GetType("MySqlConnector.MySqlConnection, MySqlConnector")!;
                var csMysql = cs;
                return (() => Open(t, csMysql), new MySqlProvider(new SqliteParameterFactory(), useAffectedRowsSemantics: false), null);
            }
            case "postgres":
            {
                var cs = LiveProviderEnvironment.GetByCanonicalName("NORM_TEST_POSTGRES");
                if (string.IsNullOrEmpty(cs)) return (null, null, "NORM_TEST_POSTGRES not set");
                var t = Type.GetType("Npgsql.NpgsqlConnection, Npgsql")!;
                return (() => Open(t, cs), new PostgresProvider(new SqliteParameterFactory()), null);
            }
            case "sqlserver":
            {
                var cs = LiveProviderEnvironment.GetByCanonicalName("NORM_TEST_SQLSERVER");
                if (string.IsNullOrEmpty(cs)) return (null, null, "NORM_TEST_SQLSERVER not set");
                var t = Type.GetType("Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient")!;
                return (() => Open(t, cs), new SqlServerProvider(), null);
            }
            default:
                throw new ArgumentOutOfRangeException(nameof(kind));
        }
    }

    private static DbConnection Open(Type connectionType, string cs)
    {
        var cn = (DbConnection)Activator.CreateInstance(connectionType, cs)!;
        cn.Open();
        return cn;
    }

    private static void Exec(Func<DbConnection> factory, string sql)
    {
        using var cn = factory();
        using var cmd = cn.CreateCommand();
        cmd.CommandText = sql;
        cmd.ExecuteNonQuery();
    }

    private static string CreateTablesSql(string kind) => kind switch
    {
        "mysql" => """
            CREATE TABLE MutRow_Test (Id INT PRIMARY KEY, IntVal INT NOT NULL, Name VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL, Amount DECIMAL(18,6) NOT NULL, Flag TINYINT(1) NOT NULL);
            CREATE TABLE MutGen_Test (Id INT AUTO_INCREMENT PRIMARY KEY, IntVal INT NOT NULL, Name VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL, Amount DECIMAL(18,6) NOT NULL, Flag TINYINT(1) NOT NULL);
            CREATE TABLE RelParent_Test (Id INT PRIMARY KEY, Name VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL);
            CREATE TABLE RelChild_Test (Id INT PRIMARY KEY, ParentId INT NOT NULL, Val INT NOT NULL);
            CREATE TABLE OccFuzz_Test (Id INT PRIMARY KEY, Val INT NOT NULL, Token VARBINARY(8));
            CREATE TABLE MixTok_Test (Id INT PRIMARY KEY, Val INT NOT NULL, Token VARBINARY(8));
            CREATE TABLE MixPlain_Test (Id INT PRIMARY KEY, Val INT NOT NULL);
            CREATE TABLE BulkCud_Test (Id INT PRIMARY KEY, IntVal INT NOT NULL, Name VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL, Flag TINYINT(1) NOT NULL);
            CREATE TABLE BulkCudChild_Test (Id INT PRIMARY KEY, ParentId INT NOT NULL, Weight INT NOT NULL)
            """,
        "postgres" => """
            CREATE TABLE "MutRow_Test" ("Id" INT PRIMARY KEY, "IntVal" INT NOT NULL, "Name" TEXT NOT NULL, "Amount" DECIMAL(18,6) NOT NULL, "Flag" BOOLEAN NOT NULL);
            CREATE TABLE "MutGen_Test" ("Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "IntVal" INT NOT NULL, "Name" TEXT NOT NULL, "Amount" DECIMAL(18,6) NOT NULL, "Flag" BOOLEAN NOT NULL);
            CREATE TABLE "RelParent_Test" ("Id" INT PRIMARY KEY, "Name" TEXT NOT NULL);
            CREATE TABLE "RelChild_Test" ("Id" INT PRIMARY KEY, "ParentId" INT NOT NULL, "Val" INT NOT NULL);
            CREATE TABLE "OccFuzz_Test" ("Id" INT PRIMARY KEY, "Val" INT NOT NULL, "Token" BYTEA);
            CREATE TABLE "MixTok_Test" ("Id" INT PRIMARY KEY, "Val" INT NOT NULL, "Token" BYTEA);
            CREATE TABLE "MixPlain_Test" ("Id" INT PRIMARY KEY, "Val" INT NOT NULL);
            CREATE TABLE "BulkCud_Test" ("Id" INT PRIMARY KEY, "IntVal" INT NOT NULL, "Name" TEXT NOT NULL, "Flag" BOOLEAN NOT NULL);
            CREATE TABLE "BulkCudChild_Test" ("Id" INT PRIMARY KEY, "ParentId" INT NOT NULL, "Weight" INT NOT NULL)
            """,
        _ => """
            CREATE TABLE MutRow_Test (Id INT PRIMARY KEY, IntVal INT NOT NULL, Name NVARCHAR(64) NOT NULL, Amount DECIMAL(18,6) NOT NULL, Flag BIT NOT NULL);
            CREATE TABLE MutGen_Test (Id INT IDENTITY(1,1) PRIMARY KEY, IntVal INT NOT NULL, Name NVARCHAR(64) NOT NULL, Amount DECIMAL(18,6) NOT NULL, Flag BIT NOT NULL);
            CREATE TABLE RelParent_Test (Id INT PRIMARY KEY, Name NVARCHAR(64) NOT NULL);
            CREATE TABLE RelChild_Test (Id INT PRIMARY KEY, ParentId INT NOT NULL, Val INT NOT NULL);
            CREATE TABLE OccFuzz_Test (Id INT PRIMARY KEY, Val INT NOT NULL, Token ROWVERSION);
            CREATE TABLE MixTok_Test (Id INT PRIMARY KEY, Val INT NOT NULL, Token ROWVERSION);
            CREATE TABLE MixPlain_Test (Id INT PRIMARY KEY, Val INT NOT NULL);
            CREATE TABLE BulkCud_Test (Id INT PRIMARY KEY, IntVal INT NOT NULL, Name NVARCHAR(64) NOT NULL, Flag BIT NOT NULL);
            CREATE TABLE BulkCudChild_Test (Id INT PRIMARY KEY, ParentId INT NOT NULL, Weight INT NOT NULL)
            """,
    };

    private static string DropTablesSql(string kind) => kind switch
    {
        "postgres" => """
            DROP TABLE IF EXISTS "MutRow_Test"; DROP TABLE IF EXISTS "MutGen_Test";
            DROP TABLE IF EXISTS "RelParent_Test"; DROP TABLE IF EXISTS "RelChild_Test";
            DROP TABLE IF EXISTS "OccFuzz_Test";
            DROP TABLE IF EXISTS "MixTok_Test"; DROP TABLE IF EXISTS "MixPlain_Test";
            DROP TABLE IF EXISTS "BulkCud_Test"; DROP TABLE IF EXISTS "BulkCudChild_Test"
            """,
        "sqlserver" => """
            IF OBJECT_ID('MutRow_Test') IS NOT NULL DROP TABLE MutRow_Test;
            IF OBJECT_ID('MutGen_Test') IS NOT NULL DROP TABLE MutGen_Test;
            IF OBJECT_ID('RelParent_Test') IS NOT NULL DROP TABLE RelParent_Test;
            IF OBJECT_ID('RelChild_Test') IS NOT NULL DROP TABLE RelChild_Test;
            IF OBJECT_ID('OccFuzz_Test') IS NOT NULL DROP TABLE OccFuzz_Test;
            IF OBJECT_ID('MixTok_Test') IS NOT NULL DROP TABLE MixTok_Test;
            IF OBJECT_ID('MixPlain_Test') IS NOT NULL DROP TABLE MixPlain_Test;
            IF OBJECT_ID('BulkCud_Test') IS NOT NULL DROP TABLE BulkCud_Test;
            IF OBJECT_ID('BulkCudChild_Test') IS NOT NULL DROP TABLE BulkCudChild_Test
            """,
        _ => """
            DROP TABLE IF EXISTS MutRow_Test; DROP TABLE IF EXISTS MutGen_Test;
            DROP TABLE IF EXISTS RelParent_Test; DROP TABLE IF EXISTS RelChild_Test;
            DROP TABLE IF EXISTS OccFuzz_Test;
            DROP TABLE IF EXISTS MixTok_Test; DROP TABLE IF EXISTS MixPlain_Test;
            DROP TABLE IF EXISTS BulkCud_Test; DROP TABLE IF EXISTS BulkCudChild_Test
            """,
    };

    [Theory]
    [InlineData("mysql")]
    [InlineData("postgres")]
    [InlineData("sqlserver")]
    public async Task Write_path_state_machines_hold_on_live_server(string kind)
    {
        var (factory, provider, skip) = OpenLive(kind);
        if (skip != null) return;

        Exec(factory!, DropTablesSql(kind));
        Exec(factory!, CreateTablesSql(kind));
        try
        {
            DbContext OpenCtx() => new(factory!(), provider!);
            DbContext OpenRelCtx() => new(factory!(), provider!, CrudStateMachineFuzzTests.RelOptions());

            await CrudStateMachineFuzzTests.RunExplicitKeyMachineAsync(OpenCtx, seed: 20260714, steps: 100);
            Exec(factory!, kind == "postgres" ? "DELETE FROM \"MutRow_Test\"" : "DELETE FROM MutRow_Test");
            await CrudStateMachineFuzzTests.RunExplicitKeyMachineAsync(OpenCtx, seed: 42, steps: 100);

            await CrudStateMachineFuzzTests.RunGenKeyMachineAsync(OpenCtx, seed: 20260714, steps: 100);
            Exec(factory!, kind == "postgres" ? "DELETE FROM \"MutGen_Test\"" : "DELETE FROM MutGen_Test");
            await CrudStateMachineFuzzTests.RunGenKeyMachineAsync(OpenCtx, seed: 42, steps: 100);

            await CrudStateMachineFuzzTests.RunRelationshipMachineAsync(OpenRelCtx, seed: 20260714, steps: 100);
            Exec(factory!, kind == "postgres"
                ? "DELETE FROM \"RelChild_Test\"; DELETE FROM \"RelParent_Test\""
                : "DELETE FROM RelChild_Test; DELETE FROM RelParent_Test");
            await CrudStateMachineFuzzTests.RunRelationshipMachineAsync(OpenRelCtx, seed: 42, steps: 100);

            await OccInterleavingFuzzTests.RunOccMachineAsync(OpenCtx, seed: 20260714, steps: 100);
            Exec(factory!, kind == "postgres" ? "DELETE FROM \"OccFuzz_Test\"" : "DELETE FROM OccFuzz_Test");
            await OccInterleavingFuzzTests.RunOccMachineAsync(OpenCtx, seed: 42, steps: 100);

            var mixInjector = new MixedTokenOccFuzzTests.NthWriteFailureInterceptor();
            DbContext OpenMixCtx() => new(factory!(), provider!, MixedTokenOccFuzzTests.FaultOptions(mixInjector));
            await MixedTokenOccFuzzTests.RunMixedOccMachineAsync(OpenMixCtx, mixInjector, seed: 20260714, steps: 100);
            Exec(factory!, kind == "postgres"
                ? "DELETE FROM \"MixTok_Test\"; DELETE FROM \"MixPlain_Test\""
                : "DELETE FROM MixTok_Test; DELETE FROM MixPlain_Test");
            await MixedTokenOccFuzzTests.RunMixedOccMachineAsync(OpenMixCtx, mixInjector, seed: 42, steps: 100);

            await BulkCudOracleFuzzTests.RunBulkCudMachineAsync(OpenCtx, seed: 20260714, steps: 80);
            Exec(factory!, kind == "postgres" ? "DELETE FROM \"BulkCud_Test\"" : "DELETE FROM BulkCud_Test");
            await BulkCudOracleFuzzTests.RunBulkCudMachineAsync(OpenCtx, seed: 42, steps: 80);
        }
        finally
        {
            Exec(factory!, DropTablesSql(kind));
        }
    }
}
