#nullable enable

using System;
using System.IO;
using System.Text;
using Xunit;

namespace nORM.Tests;

public partial class DatabaseScaffolderPrivateMethodTests
{
    // ScaffoldContext, routine, and sequence writer tests.
    [Fact]
    public void ScaffoldContext_ContainsClassName()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User", "Order" });
        Assert.Contains("public partial class AppDbContext", code);
    }

    [Fact]
    public void ScaffoldContext_ContainsNamespace()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User" });
        Assert.Contains("namespace MyApp", code);
    }

    [Fact]
    public void ScaffoldContext_ContainsEntityProperty()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User" });
        Assert.Contains("Users", code);
    }

    [Fact]
    public void ScaffoldContext_UsesReadablePluralizedQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Category", "Class" });
        Assert.Contains("IQueryable<Category> Categories", code);
        Assert.Contains("IQueryable<Class> Classes", code);
    }

    [Fact]
    public void ScaffoldContext_UsesRowsSuffixForDescriptorQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "SchemaFiltered", "AuditData", "CustomerInfo" });
        Assert.Contains("IQueryable<SchemaFiltered> SchemaFilteredRows", code);
        Assert.Contains("IQueryable<AuditData> AuditDataRows", code);
        Assert.Contains("IQueryable<CustomerInfo> CustomerInfoRows", code);
    }

    [Fact]
    public void ScaffoldContext_PluralizesCommonIrregularQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Person", "Child" });
        Assert.Contains("IQueryable<Person> People", code);
        Assert.Contains("IQueryable<Child> Children", code);
    }

    [Fact]
    public void ScaffoldContext_CanDisablePluralizedQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Category", "User" }, pluralizeQueryProperties: false);
        Assert.Contains("IQueryable<Category> Category", code);
        Assert.Contains("IQueryable<User> User", code);
        Assert.DoesNotContain("IQueryable<Category> Categories", code);
        Assert.DoesNotContain("IQueryable<User> Users", code);
    }

    [Fact]
    public void ScaffoldContext_WithForeignKeyConstraintName_EmitsNamedRelationshipConfiguration()
    {
        var code = InvokeScaffoldContextWithNamedRelationship();

        Assert.Contains(".HasForeignKey(d => d.AuthorId, p => p.Id, \"FK_Book_Author_Custom\", false);", code);
    }

    [Fact]
    public void ScaffoldContext_WithPrimaryKeyConstraintName_EmitsNamedKeyConfiguration()
    {
        var code = InvokeScaffoldContextWithPrimaryKeyConstraintName();

        Assert.Contains("mb.Entity<User>().HasKey(e => e.Id, \"PK_User_Custom\");", code);
    }

    [Fact]
    public void ScaffoldContext_EntitiesAreSortedAlphabetically()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Zebra", "Apple" });
        var appleIdx = code.IndexOf("Apples", StringComparison.Ordinal);
        var zebraIdx = code.IndexOf("Zebras", StringComparison.Ordinal);
        Assert.True(appleIdx < zebraIdx, "Entities should be alphabetically sorted in the context.");
    }

    [Fact]
    public void ScaffoldContext_ContextInheritsDbContext()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", Array.Empty<string>());
        Assert.Contains(": DbContext", code);
    }

    [Fact]
    public void ScaffoldContext_EmitsPartialCustomizationHook()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User" });

        Assert.Contains("public partial class AppDbContext : DbContext", code);
        Assert.Contains(": base(cn, provider, ConfigureOptions(options))", code);
        Assert.Contains(": base(connectionString, provider, ConfigureOptions(options))", code);
        Assert.Contains("configure?.Invoke(mb);", code);
        Assert.Contains("OnModelCreatingPartial(mb);", code);
        Assert.Contains("static partial void OnModelCreatingPartial(ModelBuilder modelBuilder);", code);
    }

    [Fact]
    public void ScaffoldContext_KeywordContextName_PrependsAt()
    {
        // "class" is a C# keyword; the context class name should be escaped
        var code = InvokeScaffoldContext("MyApp", "class", Array.Empty<string>());
        Assert.Contains("@class", code);
    }

    [Fact]
    public void ScaffoldContext_ContainsAutoGeneratedHeader()
    {
        var code = InvokeScaffoldContext("MyApp", "Ctx", Array.Empty<string>());
        Assert.Contains("auto-generated", code);
    }

    [Fact]
    public void ScaffoldContext_WithRoutineStub_EmitsProviderBoundWrapperMethods()
    {
        var code = InvokeScaffoldContextWithRoutineStub();

        Assert.Contains("using System.Threading;", code);
        Assert.Contains("using System.Threading.Tasks;", code);
        Assert.Contains("Executes provider-bound stored procedure `dbo.GetRevenue`", code);
        Assert.Contains("Parameters discovered at scaffold time: @tenantId IN int, @total OUT decimal", code);
        Assert.Contains("public sealed class GetRevenueParameters", code);
        Assert.Contains("public int? tenantId { get; init; }", code);
        Assert.Contains("public string? message { get; init; }", code);
        Assert.Contains("public sealed class GetRevenueResult", code);
        Assert.Contains("public int Id { get; set; }", code);
        Assert.Contains("public string Name { get; set; } = default!;", code);
        Assert.Contains("Task<List<TResult>> GetRevenueAsync<TResult>(GetRevenueParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("Task<List<GetRevenueResult>> GetRevenueAsync(GetRevenueParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("ExecuteStoredProcedureAsync<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\")))", code);
        Assert.Contains("ExecuteStoredProcedureAsync<GetRevenueResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\")))", code);
        Assert.Contains("IAsyncEnumerable<TResult> StreamGetRevenueAsync<TResult>(GetRevenueParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("IAsyncEnumerable<GetRevenueResult> StreamGetRevenueAsync(GetRevenueParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("ExecuteStoredProcedureAsAsyncEnumerable<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\")))", code);
        Assert.Contains("ExecuteStoredProcedureAsAsyncEnumerable<GetRevenueResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\")))", code);
        Assert.Contains("without buffering the full result set", code);
        Assert.Contains("Task<StoredProcedureResult<TResult>> GetRevenueWithOutputAsync<TResult>", code);
        Assert.Contains("Task<StoredProcedureResult<GetRevenueResult>> GetRevenueWithOutputAsync", code);
        Assert.Contains("ExecuteStoredProcedureWithOutputAsync<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\")), outputParameters)", code);
        Assert.Contains("output parameters discovered at scaffold time", code);
        Assert.Contains("ExecuteStoredProcedureWithOutputAsync<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenue\")), CreateGetRevenueOutputParameters())", code);
        Assert.Contains("public static OutputParameter[] CreateGetRevenueOutputParameters()", code);
        Assert.Contains("new OutputParameter(\"total\", System.Data.DbType.Decimal, (byte)18, (byte)2)", code);
        Assert.Contains("new OutputParameter(\"message\", System.Data.DbType.String, 32, System.Data.ParameterDirection.InputOutput)", code);
        Assert.Contains("private static object? RequireScaffoldedRoutineParameters", code);
        Assert.Contains("Routine bodies are provider-owned and are not translated by nORM", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_routine_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    // ── ScaffoldAsync (public integration) ─────────────────────────────────

    [Fact]
    public void ScaffoldContext_WithUseDatabaseNames_RoutineStubPreservesLegalRoutineAndResultColumnNames()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "calculate_risk",
            "SQL Server stored procedure; parameters=1; outputParameters=0; parameterModes=@customer_id:IN:int; resultColumns=total_value:decimal(18,2):0",
            useDatabaseNames: true);

        Assert.Contains("public sealed class calculate_riskParameters", code);
        Assert.Contains("public int? customer_id { get; init; }", code);
        Assert.Contains("public sealed class calculate_riskResult", code);
        Assert.Contains("public decimal total_value { get; set; }", code);
        Assert.Contains("Task<List<TResult>> calculate_riskAsync<TResult>(calculate_riskParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("Task<List<calculate_riskResult>> calculate_riskAsync(calculate_riskParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("IAsyncEnumerable<calculate_riskResult> Streamcalculate_riskAsync(calculate_riskParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.DoesNotContain("CalculateRisk", code, StringComparison.Ordinal);
        Assert.DoesNotContain("TotalValue", code, StringComparison.Ordinal);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_database_names_routine_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithKnownNoResultProcedure_EmitsNonQueryWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "RecalculateLedger",
            "SQL Server stored procedure; parameters=1; outputParameters=0; parameterModes=@tenantId:IN:int; resultColumns=");

        Assert.Contains("Task<int> RecalculateLedgerAsync(RecalculateLedgerParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("ExecuteStoredProcedureNonQueryAsync(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"RecalculateLedger\"), ct, RequireScaffoldedRoutineParameters(parameters, 1, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"RecalculateLedger\")))", code);
        Assert.DoesNotContain("RecalculateLedgerAsync<TResult>", code);
        Assert.DoesNotContain("StreamRecalculateLedgerAsync", code);
    }

    [Fact]
    public void ScaffoldContext_WithKnownNoResultOutputProcedure_EmitsNonQueryOutputWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "FinalizeLedger",
            "SQL Server stored procedure; parameters=2; outputParameters=1; parameterModes=@tenantId:IN:int,@status:OUT:nvarchar(32); resultColumns=");

        Assert.Contains("Task<int> FinalizeLedgerAsync(FinalizeLedgerParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("Task<StoredProcedureNonQueryResult> FinalizeLedgerWithOutputAsync(FinalizeLedgerParameters? parameters = null, CancellationToken ct = default, params OutputParameter[] outputParameters)", code);
        Assert.Contains("ExecuteStoredProcedureNonQueryWithOutputAsync(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"FinalizeLedger\"), ct, RequireScaffoldedRoutineParameters(parameters, 1, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"FinalizeLedger\")), outputParameters)", code);
        Assert.Contains("Task<StoredProcedureNonQueryResult> FinalizeLedgerWithOutputAsync(FinalizeLedgerParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("ExecuteStoredProcedureNonQueryWithOutputAsync(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"FinalizeLedger\"), ct, RequireScaffoldedRoutineParameters(parameters, 1, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"FinalizeLedger\")), CreateFinalizeLedgerOutputParameters())", code);
        Assert.DoesNotContain("StoredProcedureResult<TResult> FinalizeLedgerWithOutputAsync", code);
        Assert.DoesNotContain("FinalizeLedgerAsync<TResult>", code);
        Assert.DoesNotContain("StreamFinalizeLedgerAsync", code);
    }

    [Fact]
    public void ScaffoldContext_WithPrecisionOnlyRoutineOutput_EmitsNullableScaleOutputParameter()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "GetLedgerTotal",
            "SQL Server stored procedure; parameters=1; outputParameters=1; parameterModes=@total:OUT:decimal(18); resultColumns=");

        Assert.Contains("public static OutputParameter[] CreateGetLedgerTotalOutputParameters()", code);
        Assert.Contains("new OutputParameter(\"total\", System.Data.DbType.Decimal, null, (byte)18, null, System.Data.ParameterDirection.Output, null)", code);
    }

    [Fact]
    public void ScaffoldContext_WithRoutineReturnValue_EmitsReturnOutputParameter()
    {
        var code = InvokeScaffoldContextWithRoutineReturnStub();

        Assert.Contains("Parameters discovered at scaffold time: @orderId IN int, return RETURN int", code);
        Assert.Contains("public int? orderId { get; init; }", code);
        Assert.Contains("Task<StoredProcedureResult<TResult>> ApplyDiscountWithOutputAsync<TResult>", code);
        Assert.Contains("ExecuteStoredProcedureWithOutputAsync<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"ApplyDiscount\"), ct, RequireScaffoldedRoutineParameters(parameters, 1, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"ApplyDiscount\")), CreateApplyDiscountOutputParameters())", code);
        Assert.Contains("new OutputParameter(\"return\", System.Data.DbType.Int32, null, System.Data.ParameterDirection.ReturnValue)", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_routine_return_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithSqlServerAliasAndTableValuedRoutineParameters_EmitsBestEffortTypes()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "ImportLines",
            "SQL Server stored procedure; parameters=4; outputParameters=0; parameterModes=@email:IN:nvarchar(320),@amount:IN:decimal(18,4),@login:IN:sysname,@items:IN:table type (dbo.LineItemList)");

        Assert.Contains("public string? email { get; init; }", code);
        Assert.Contains("public decimal? amount { get; init; }", code);
        Assert.Contains("public string? login { get; init; }", code);
        Assert.Contains("public DbParameter? items { get; init; }", code);
        Assert.Contains("Parameters discovered at scaffold time: @email IN nvarchar(320), @amount IN decimal(18,4), @login IN sysname, @items IN table type (dbo.LineItemList)", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_sqlserver_alias_routine_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithQuotedStoredProcedureName_UsesProviderEscapedInvocationName()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "sales ops",
            "Get Revenue",
            "SQL Server stored procedure; parameters=1; outputParameters=0; parameterModes=@tenantId:IN:int");

        Assert.Contains("Provider.Escape(\"sales ops\") + \".\" + Provider.Escape(\"Get Revenue\")", code);
        Assert.DoesNotContain("\"sales ops.Get Revenue\"", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_quoted_routine_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithSqlServerTableValuedFunction_EmitsSelectWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "GetRevenueRows",
            "SQL Server table-valued function; parameters=1; outputParameters=0; callShape=table-valued-function; parameterModes=@tenantId:IN:int; dataType=TABLE; resultColumns=Id:int:0|Name:nvarchar(40):0");

        Assert.Contains("Executes provider-bound table-valued function `dbo.GetRevenueRows`", code);
        Assert.Contains("public sealed class GetRevenueRowsParameters", code);
        Assert.Contains("public int? tenantId { get; init; }", code);
        Assert.Contains("public sealed class GetRevenueRowsResult", code);
        Assert.Contains("public int Id { get; set; }", code);
        Assert.Contains("public string Name { get; set; } = default!;", code);
        Assert.Contains("var args = parameters is null ? System.Array.Empty<object>() : new object[] { (object?)parameters.tenantId ?? System.DBNull.Value };", code);
        Assert.Contains("if (args.Length != 1)", code);
        Assert.Contains("Function `dbo.GetRevenueRows` was scaffolded with 1 input parameters", code);
        Assert.Contains("Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"GetRevenueRows\")", code);
        Assert.Contains("SELECT * FROM ", code);
        Assert.Contains("QueryUnchangedAsync<TResult>", code);
        Assert.Contains("Task<List<GetRevenueRowsResult>> GetRevenueRowsAsync(GetRevenueRowsParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("QueryUnchangedAsync<GetRevenueRowsResult>", code);
        Assert.Contains("IAsyncEnumerable<TResult> StreamGetRevenueRowsAsync<TResult>", code);
        Assert.Contains("IAsyncEnumerable<GetRevenueRowsResult> StreamGetRevenueRowsAsync(GetRevenueRowsParameters? parameters = null", code);
        Assert.Contains("QueryUnchangedStreamAsync<TResult>", code);
        Assert.Contains("QueryUnchangedStreamAsync<GetRevenueRowsResult>", code);
        Assert.DoesNotContain("ExecuteStoredProcedureAsync<TResult>(\"dbo.GetRevenueRows\"", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_tvf_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithSqlServerScalarFunction_EmitsValueProjectionWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "CalculateRisk",
            "SQL Server scalar function; parameters=1; outputParameters=1; callShape=scalar-function; parameterModes=@customerId:IN:int,return:RETURN:int; dataType=int");

        Assert.Contains("Executes provider-bound scalar function `dbo.CalculateRisk`", code);
        Assert.Contains("public sealed class CalculateRiskParameters", code);
        Assert.Contains("public int? customerId { get; init; }", code);
        Assert.Contains("private sealed class CalculateRiskValueResult<TValue>", code);
        Assert.Contains("Task<TValue?> CalculateRiskValueAsync<TValue>(CalculateRiskParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("QueryUnchangedAsync<CalculateRiskValueResult<TValue>>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\"), ct, args)", code);
        Assert.Contains("return rows.Count == 0 ? default : rows[0].Value;", code);
        Assert.Contains("SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.Contains("QueryUnchangedAsync<TResult>", code);
        Assert.DoesNotContain("WithOutputAsync", code);
        Assert.True(
            code.IndexOf("Executes provider-bound scalar function `dbo.CalculateRisk`", StringComparison.Ordinal) <
            code.IndexOf("public Task<List<TResult>> CalculateRiskAsync<TResult>", StringComparison.Ordinal));
        Assert.True(
            code.IndexOf("public Task<List<TResult>> CalculateRiskAsync<TResult>", StringComparison.Ordinal) <
            code.IndexOf("private sealed class CalculateRiskValueResult<TValue>", StringComparison.Ordinal));

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_scalar_fn_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithPostgresFunction_EmitsSelectInvocationWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate_risk",
            "PostgreSQL function; parameters=1; outputParameters=0; parameterModes=customer_id:IN:integer; dataType=integer");

        Assert.Contains("Executes provider-bound function `public.calculate_risk`", code);
        Assert.Contains("public int? customer_id { get; init; }", code);
        Assert.Contains("Task<TValue?> CalculateRiskValueAsync<TValue>(CalculateRiskParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("return QueryUnchangedAsync<TResult>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.DoesNotContain("ExecuteStoredProcedureAsync<TResult>", code);
    }

    [Fact]
    public void ScaffoldContext_WithPostgresFunctionAdvancedParameterTypes_EmitsTypedParameterDto()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate_campaign",
            "PostgreSQL function; parameters=6; outputParameters=0; parameterModes=tenant_id:IN:integer,duration:IN:interval,customer_ids:IN:ARRAY (_int4),labels:IN:ARRAY (_text),note:IN:USER-DEFINED (citext),trace_id:IN:USER-DEFINED (uuid); dataType=integer");

        Assert.Contains("using System;", code);
        Assert.Contains("public int? tenant_id { get; init; }", code);
        Assert.Contains("public TimeSpan? duration { get; init; }", code);
        Assert.Contains("public int[]? customer_ids { get; init; }", code);
        Assert.Contains("public string[]? labels { get; init; }", code);
        Assert.Contains("public string? note { get; init; }", code);
        Assert.Contains("public Guid? trace_id { get; init; }", code);
        Assert.Contains("if (args.Length != 6)", code);
        Assert.Contains("var casts = new[] { \"integer\", \"interval\", \"integer[]\", \"text[]\", \"citext\", \"uuid\" };", code);
        Assert.Contains("Provider.ParamPrefix + \"p\" + i + \"::\" + casts[i]", code);
        Assert.DoesNotContain("public object? duration { get; init; }", code);
        Assert.DoesNotContain("public object? customer_ids { get; init; }", code);
        Assert.DoesNotContain("public object? trace_id { get; init; }", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_pg_routine_types_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithFunctionParametersThatCannotBecomeDto_UsesPositionalArguments()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate odd",
            "PostgreSQL function; parameters=2; outputParameters=0; parameterModes=tenant-id:IN:integer,search text:IN:text; dataType=integer");

        Assert.DoesNotContain("public sealed class CalculateOddParameters", code);
        Assert.Contains("Task<TValue?> CalculateOddValueAsync<TValue>(object?[]? arguments = null, CancellationToken ct = default)", code);
        Assert.Contains("var args = arguments is null ? System.Array.Empty<object>() : System.Array.ConvertAll(arguments, value => (object)(value ?? System.DBNull.Value));", code);
        Assert.Contains("if (args.Length != 2)", code);
        Assert.Contains("Function `public.calculate odd` was scaffolded with 2 input parameters", code);
        Assert.Contains("pass exactly 2 arguments in scaffolded order", code);
        Assert.DoesNotContain("var args = System.Array.Empty<object>();", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_positional_function_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithColonDelimitedFunctionParameterNames_ParsesModeTokenBeforePositionalFallback()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate odd",
            "PostgreSQL function; parameters=2; outputParameters=0; parameterModes=tenant:id:IN:integer,search:text:IN:text; dataType=integer");

        Assert.DoesNotContain("public sealed class CalculateOddParameters", code);
        Assert.Contains("Task<TValue?> CalculateOddValueAsync<TValue>(object?[]? arguments = null, CancellationToken ct = default)", code);
        Assert.Contains("if (args.Length != 2)", code);
        Assert.Contains("var casts = new[] { \"integer\", \"text\" };", code);
        Assert.Contains("Parameters discovered at scaffold time: tenant:id IN integer, search:text IN text", code);
        Assert.DoesNotContain("public object? tenant", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_colon_function_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithModeLikeTextInsideFunctionParameterName_UsesTerminalModeToken()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate odd",
            "PostgreSQL function; parameters=1; outputParameters=0; parameterModes=tenant:IN:name:IN:integer; dataType=integer");

        Assert.DoesNotContain("public sealed class CalculateOddParameters", code);
        Assert.Contains("Task<TValue?> CalculateOddValueAsync<TValue>(object?[]? arguments = null, CancellationToken ct = default)", code);
        Assert.Contains("if (args.Length != 1)", code);
        Assert.Contains("var casts = new[] { \"integer\" };", code);
        Assert.Contains("Parameters discovered at scaffold time: tenant:IN:name IN integer", code);
        Assert.DoesNotContain("public object? tenant", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_mode_text_function_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithSemicolonDelimitedFunctionParameterNames_PreservesGeneratedMetadataFields()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate odd",
            "PostgreSQL function; parameters=2; outputParameters=0; parameterModes=tenant;id:IN:integer,search;text:IN:text; dataType=integer");

        Assert.DoesNotContain("public sealed class CalculateOddParameters", code);
        Assert.Contains("Task<TValue?> CalculateOddValueAsync<TValue>(object?[]? arguments = null, CancellationToken ct = default)", code);
        Assert.Contains("if (args.Length != 2)", code);
        Assert.Contains("var casts = new[] { \"integer\", \"text\" };", code);
        Assert.Contains("Parameters discovered at scaffold time: tenant;id IN integer, search;text IN text", code);
        Assert.DoesNotContain("var args = System.Array.Empty<object>();", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_semicolon_function_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithAllowListedKeyTextInsideFunctionParameterName_KeepsRoutineFieldsIntact()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate odd",
            "PostgreSQL function; parameters=1; outputParameters=0; parameterModes=tenant; dataType=retained:IN:integer; dataType=integer");

        Assert.DoesNotContain("public sealed class CalculateOddParameters", code);
        Assert.Contains("Task<TValue?> CalculateOddValueAsync<TValue>(object?[]? arguments = null, CancellationToken ct = default)", code);
        Assert.Contains("if (args.Length != 1)", code);
        Assert.Contains("var casts = new[] { \"integer\" };", code);
        Assert.Contains("Parameters discovered at scaffold time: tenant; dataType=retained IN integer", code);
        Assert.DoesNotContain("var args = System.Array.Empty<object>();", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_key_text_function_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithCommaDelimitedFunctionParameterNames_SplitsOnlyCompleteParameters()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "calculate odd",
            "PostgreSQL function; parameters=2; outputParameters=0; parameterModes=tenant,id:IN:integer,search,text:IN:text; dataType=integer");

        Assert.DoesNotContain("public sealed class CalculateOddParameters", code);
        Assert.Contains("Task<TValue?> CalculateOddValueAsync<TValue>(object?[]? arguments = null, CancellationToken ct = default)", code);
        Assert.Contains("if (args.Length != 2)", code);
        Assert.Contains("var casts = new[] { \"integer\", \"text\" };", code);
        Assert.Contains("Parameters discovered at scaffold time: tenant,id IN integer, search,text IN text", code);
        Assert.DoesNotContain("var args = System.Array.Empty<object>();", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_comma_function_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithStoredProcedureParametersThatCannotBecomeDto_UsesDictionaryArguments()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "import odd",
            "SQL Server stored procedure; parameters=2; outputParameters=0; parameterModes=@tenant-id:IN:int,@search text:IN:nvarchar(64)");

        Assert.DoesNotContain("public sealed class ImportOddParameters", code);
        Assert.Contains("Task<List<TResult>> ImportOddAsync<TResult>(IReadOnlyDictionary<string, object?>? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("IAsyncEnumerable<TResult> StreamImportOddAsync<TResult>(IReadOnlyDictionary<string, object?>? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("ExecuteStoredProcedureAsync<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"import odd\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"import odd\")))", code);
        Assert.Contains("ExecuteStoredProcedureAsAsyncEnumerable<TResult>(Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"import odd\"), ct, RequireScaffoldedRoutineParameters(parameters, 2, Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"import odd\")))", code);
        Assert.Contains("pass exactly {expectedInputCount} dictionary entries using the provider parameter names", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_dictionary_routine_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithPostgresTableFunction_EmitsSelectStarInvocationWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "customer_orders",
            "PostgreSQL function; parameters=3; outputParameters=2; parameterModes=customer_id:IN:integer,Id:OUT:integer,Name:OUT:text; dataType=record");

        Assert.Contains("Executes provider-bound function `public.customer_orders`", code);
        Assert.Contains("public sealed class CustomerOrdersResult", code);
        Assert.Contains("public int Id { get; set; }", code);
        Assert.Contains("public string Name { get; set; } = default!;", code);
        Assert.Contains("Task<List<CustomerOrdersResult>> CustomerOrdersAsync(CustomerOrdersParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("return QueryUnchangedAsync<TResult>(\"SELECT * FROM \" + invocation", code);
        Assert.Contains("QueryUnchangedAsync<CustomerOrdersResult>", code);
        Assert.DoesNotContain("ExecuteStoredProcedureAsync<TResult>", code);
    }

    [Fact]
    public void ScaffoldContext_WithResultColumnNamesContainingColon_PreservesNameBeforeTypeMapping()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "GetOrderLines",
            "SQL Server stored procedure; parameters=1; outputParameters=0; parameterModes=@tenantId:IN:int; resultColumns=Order:Id:int:0|Line:Name:nvarchar(40):1");

        Assert.Contains("public sealed class GetOrderLinesResult", code);
        Assert.Contains("public int OrderId { get; set; }", code);
        Assert.Contains("public string? LineName { get; set; }", code);
        Assert.DoesNotContain("public object? Order", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_colon_result_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithResultColumnNamesContainingSemicolon_PreservesMetadataFields()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "GetOrderLines",
            "SQL Server stored procedure; parameters=1; outputParameters=0; parameterModes=@tenantId:IN:int; resultColumns=Order;Id:int:0|Line;Name:nvarchar(40):1");

        Assert.Contains("public sealed class GetOrderLinesResult", code);
        Assert.Contains("public int OrderId { get; set; }", code);
        Assert.Contains("public string? LineName { get; set; }", code);
        Assert.DoesNotContain("public object? Order", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_semicolon_result_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithResultColumnNamesContainingPipe_SplitsOnlyCompleteColumns()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "dbo",
            "GetOrderLines",
            "SQL Server stored procedure; parameters=1; outputParameters=0; parameterModes=@tenantId:IN:int; resultColumns=Order|Id:int:0|Line|Name:nvarchar(40):1");

        Assert.Contains("public sealed class GetOrderLinesResult", code);
        Assert.Contains("public int OrderId { get; set; }", code);
        Assert.Contains("public string? LineName { get; set; }", code);
        Assert.DoesNotContain("public object? Order", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_pipe_result_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithPostgresSetReturningScalarFunction_EmitsValueProjectionWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            "public",
            "customer_ids",
            "PostgreSQL function; parameters=1; outputParameters=0; callShape=table-valued-function; parameterModes=tenant_id:IN:integer; dataType=integer");

        Assert.Contains("Executes provider-bound function `public.customer_ids`", code);
        Assert.Contains("public sealed class CustomerIdsResult", code);
        Assert.Contains("public int Value { get; set; }", code);
        Assert.Contains("Task<List<CustomerIdsResult>> CustomerIdsAsync", code);
        Assert.Contains("return QueryUnchangedAsync<TResult>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.Contains("return QueryUnchangedAsync<CustomerIdsResult>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.Contains("QueryUnchangedStreamAsync<TResult>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.Contains("QueryUnchangedStreamAsync<CustomerIdsResult>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.Contains("IAsyncEnumerable<TResult> StreamCustomerIdsAsync<TResult>", code);
        Assert.DoesNotContain("QueryUnchangedAsync<TResult>(\"SELECT * FROM \" + invocation", code);
    }

    [Fact]
    public void ScaffoldContext_WithMySqlFunction_EmitsSelectInvocationWrapper()
    {
        var code = InvokeScaffoldContextWithRoutine(
            null,
            "calculate_risk",
            "MySQL FUNCTION; parameters=1; outputParameters=0; parameterModes=customer_id:IN:int; dataType=int");

        Assert.Contains("Executes provider-bound FUNCTION `calculate_risk`", code);
        Assert.Contains("Task<TValue?> CalculateRiskValueAsync<TValue>(CalculateRiskParameters? parameters = null, CancellationToken ct = default)", code);
        Assert.Contains("return QueryUnchangedAsync<TResult>(\"SELECT \" + invocation + \" AS \" + Provider.Escape(\"Value\")", code);
        Assert.DoesNotContain("ExecuteStoredProcedureAsync<TResult>", code);
    }

    [Fact]
    public void ScaffoldContext_WithMySqlUnsignedRoutineParameters_EmitsUnsignedClrTypes()
    {
        var code = InvokeScaffoldContextWithRoutine(
            null,
            "calculate_unsigned_risk",
            "MySQL FUNCTION; parameters=4; outputParameters=0; parameterModes=customer_id:IN:int unsigned,max_id:IN:bigint unsigned,rank:IN:smallint unsigned,flag:IN:tinyint unsigned; dataType=int");

        Assert.Contains("public uint? customer_id { get; init; }", code);
        Assert.Contains("public ulong? max_id { get; init; }", code);
        Assert.Contains("public ushort? rank { get; init; }", code);
        Assert.Contains("public byte? flag { get; init; }", code);
        Assert.DoesNotContain("public int? customer_id { get; init; }", code);
        Assert.DoesNotContain("public long? max_id { get; init; }", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_mysql_unsigned_routine_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithSqlServerSequence_EmitsNextValueWrapper()
    {
        var code = InvokeScaffoldContextWithSequence(
            "dbo",
            "OrderNo",
            "SQL Server sequence; dataType=bigint");

        Assert.Contains("private sealed class OrderNoSequenceValue", code);
        Assert.Contains("public long Value { get; set; }", code);
        Assert.Contains("public async Task<long> NextOrderNoValueAsync(CancellationToken ct = default)", code);
        Assert.Contains("SELECT NEXT VALUE FOR ", code);
        Assert.Contains("Provider.Escape(\"dbo\") + \".\" + Provider.Escape(\"OrderNo\")", code);
        Assert.Contains("QueryUnchangedAsync<OrderNoSequenceValue>", code);

        var dir = Path.Combine(Path.GetTempPath(), "san_scaffold_sequence_" + Guid.NewGuid().ToString("N"));
        try
        {
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "AppDbContext.cs"), code, Encoding.UTF8);
            File.WriteAllText(Path.Combine(dir, "User.cs"), "namespace MyApp; public class User { public int Id { get; set; } }", Encoding.UTF8);
            AssertScaffoldOutputBuildsAsConsumerProject(dir);
        }
        finally
        {
            if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
        }
    }

    [Fact]
    public void ScaffoldContext_WithSqlServerTinyIntSequence_EmitsByteWrapper()
    {
        var code = InvokeScaffoldContextWithSequence(
            "dbo",
            "TinyOrderNo",
            "SQL Server sequence; dataType=tinyint");

        Assert.Contains("private sealed class TinyOrderNoSequenceValue", code);
        Assert.Contains("public byte Value { get; set; }", code);
        Assert.Contains("public async Task<byte> NextTinyOrderNoValueAsync(CancellationToken ct = default)", code);
        Assert.Contains("QueryUnchangedAsync<TinyOrderNoSequenceValue>", code);
    }

    [Fact]
    public void ScaffoldContext_WithPostgresSequence_EmitsRegclassWrapper()
    {
        var code = InvokeScaffoldContextWithSequence(
            "public",
            "invoice_no",
            "PostgreSQL sequence; dataType=integer");

        Assert.Contains("private sealed class InvoiceNoSequenceValue", code);
        Assert.Contains("public int Value { get; set; }", code);
        Assert.Contains("public async Task<int> NextInvoiceNoValueAsync(CancellationToken ct = default)", code);
        Assert.Contains("SELECT nextval('", code);
        Assert.Contains("::regclass) AS ", code);
        Assert.Contains("(Provider.Escape(\"public\") + \".\" + Provider.Escape(\"invoice_no\")).Replace(\"'\", \"''\")", code);
    }

    [Fact]
    public void ScaffoldContext_WithUseDatabaseNames_SequenceStubPreservesLegalSequenceName()
    {
        var code = InvokeScaffoldContextWithSequence(
            "public",
            "invoice_no",
            "PostgreSQL sequence; dataType=integer",
            useDatabaseNames: true);

        Assert.Contains("private sealed class invoice_noSequenceValue", code);
        Assert.Contains("public async Task<int> Nextinvoice_noValueAsync(CancellationToken ct = default)", code);
        Assert.Contains("QueryUnchangedAsync<invoice_noSequenceValue>", code);
        Assert.DoesNotContain("InvoiceNoSequenceValue", code, StringComparison.Ordinal);
        Assert.DoesNotContain("NextInvoiceNoValueAsync", code, StringComparison.Ordinal);
    }

    [Fact]
    public void ScaffoldContext_WithIdentityOptions_EmitsFluentSeedAndIncrement()
    {
        var code = InvokeScaffoldContextWithIdentityOptions();

        Assert.Contains("mb.Entity<User>().Property(e => e.Id).HasIdentityOptions(1000, 25);", code);
        Assert.Contains("ConfigureOptions(options)", code);
    }

    [Fact]
    public void ScaffoldContext_WithDecimalPrecision_EmitsFluentPrecision()
    {
        var code = InvokeScaffoldContextWithPrecision();

        Assert.Contains("mb.Entity<Invoice>().Property(e => e.Amount).HasPrecision(28, 6);", code);
        Assert.Contains("ConfigureOptions(options)", code);
    }

    [Fact]
    public void ScaffoldContext_WithDecimalPrecisionWithoutScale_EmitsPrecisionOnlyFluentPrecision()
    {
        var code = InvokeScaffoldContextWithPrecision(null);

        Assert.Contains("mb.Entity<Invoice>().Property(e => e.Amount).HasPrecision(28);", code);
        Assert.DoesNotContain("HasPrecision(28,", code, StringComparison.Ordinal);
    }

    [Fact]
    public void ScaffoldContext_WithColumnFacets_EmitsLengthUnicodeAndFixedLengthFluentConfiguration()
    {
        var code = InvokeScaffoldContextWithColumnFacets();

        Assert.Contains("mb.Entity<Customer>().Property(e => e.Code).HasMaxLength(40).IsUnicode(false).IsFixedLength();", code);
        Assert.Contains("mb.Entity<Customer>().Property(e => e.Token).HasMaxLength(16).IsFixedLength();", code);
    }

}
