#nullable enable

using System;
using Xunit;

namespace nORM.Tests;

public partial class DatabaseScaffolderPrivateMethodTests
{
    [Fact]
    public void ScaffoldContext_ContainsClassName()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User", "Order" });
        Assert.Contains("public partial class AppDbContext", code);
    }

    [Fact]
    public void ScaffoldContext_ContainsNamespace()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User" });
        Assert.Contains("namespace MyApp", code);
    }

    [Fact]
    public void ScaffoldContext_ContainsEntityProperty()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User" });
        Assert.Contains("Users", code);
    }

    [Fact]
    public void ScaffoldContext_UsesReadablePluralizedQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Category", "Class" });
        Assert.Contains("IQueryable<Category> Categories", code);
        Assert.Contains("IQueryable<Class> Classes", code);
    }

    [Fact]
    public void ScaffoldContext_UsesRowsSuffixForDescriptorQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "SchemaFiltered", "AuditData", "CustomerInfo" });
        Assert.Contains("IQueryable<SchemaFiltered> SchemaFilteredRows", code);
        Assert.Contains("IQueryable<AuditData> AuditDataRows", code);
        Assert.Contains("IQueryable<CustomerInfo> CustomerInfoRows", code);
    }

    [Fact]
    public void ScaffoldContext_PluralizesCommonIrregularQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Person", "Child" });
        Assert.Contains("IQueryable<Person> People", code);
        Assert.Contains("IQueryable<Child> Children", code);
    }

    [Fact]
    public void ScaffoldContext_CanDisablePluralizedQueryPropertyNames()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Category", "User" }, pluralizeQueryProperties: false);
        Assert.Contains("IQueryable<Category> Category", code);
        Assert.Contains("IQueryable<User> User", code);
        Assert.DoesNotContain("IQueryable<Category> Categories", code);
        Assert.DoesNotContain("IQueryable<User> Users", code);
    }

    [Fact]
    public void ScaffoldContext_WithForeignKeyConstraintName_EmitsNamedRelationshipConfiguration()
    {
        var code = InvokeScaffoldContextWithNamedRelationship();

        Assert.Contains(".HasForeignKey(d => d.AuthorId, p => p.Id, \"FK_Book_Author_Custom\", false);", code);
    }

    [Fact]
    public void ScaffoldContext_WithPrimaryKeyConstraintName_EmitsNamedKeyConfiguration()
    {
        var code = InvokeScaffoldContextWithPrimaryKeyConstraintName();

        Assert.Contains("mb.Entity<User>().HasKey(e => e.Id, \"PK_User_Custom\");", code);
    }

    [Fact]
    public void ScaffoldContext_EntitiesAreSortedAlphabetically()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "Zebra", "Apple" });
        var appleIdx = code.IndexOf("Apples", StringComparison.Ordinal);
        var zebraIdx = code.IndexOf("Zebras", StringComparison.Ordinal);
        Assert.True(appleIdx < zebraIdx, "Entities should be alphabetically sorted in the context.");
    }

    [Fact]
    public void ScaffoldContext_ContextInheritsDbContext()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", Array.Empty<string>());
        Assert.Contains(": DbContext", code);
    }

    [Fact]
    public void ScaffoldContext_EmitsPartialCustomizationHook()
    {
        var code = InvokeScaffoldContext("MyApp", "AppDbContext", new[] { "User" });

        Assert.Contains("public partial class AppDbContext : DbContext", code);
        Assert.Contains(": base(cn, provider, ConfigureOptions(options))", code);
        Assert.Contains(": base(connectionString, provider, ConfigureOptions(options))", code);
        Assert.Contains("configure?.Invoke(mb);", code);
        Assert.Contains("OnModelCreatingPartial(mb);", code);
        Assert.Contains("static partial void OnModelCreatingPartial(ModelBuilder modelBuilder);", code);
    }

    [Fact]
    public void ScaffoldContext_KeywordContextName_PrependsAt()
    {
        // "class" is a C# keyword; the context class name should be escaped
        var code = InvokeScaffoldContext("MyApp", "class", Array.Empty<string>());
        Assert.Contains("@class", code);
    }

    [Fact]
    public void ScaffoldContext_ContainsAutoGeneratedHeader()
    {
        var code = InvokeScaffoldContext("MyApp", "Ctx", Array.Empty<string>());
        Assert.Contains("auto-generated", code);
    }

    [Fact]
    public void ScaffoldContext_WithIdentityOptions_EmitsFluentSeedAndIncrement()
    {
        var code = InvokeScaffoldContextWithIdentityOptions();

        Assert.Contains("mb.Entity<User>().Property(e => e.Id).HasIdentityOptions(1000, 25);", code);
        Assert.Contains("ConfigureOptions(options)", code);
    }

    [Fact]
    public void ScaffoldContext_WithDecimalPrecision_EmitsFluentPrecision()
    {
        var code = InvokeScaffoldContextWithPrecision();

        Assert.Contains("mb.Entity<Invoice>().Property(e => e.Amount).HasPrecision(28, 6);", code);
        Assert.Contains("ConfigureOptions(options)", code);
    }

    [Fact]
    public void ScaffoldContext_WithDecimalPrecisionWithoutScale_EmitsPrecisionOnlyFluentPrecision()
    {
        var code = InvokeScaffoldContextWithPrecision(null);

        Assert.Contains("mb.Entity<Invoice>().Property(e => e.Amount).HasPrecision(28);", code);
        Assert.DoesNotContain("HasPrecision(28,", code, StringComparison.Ordinal);
    }

    [Fact]
    public void ScaffoldContext_WithColumnFacets_EmitsLengthUnicodeAndFixedLengthFluentConfiguration()
    {
        var code = InvokeScaffoldContextWithColumnFacets();

        Assert.Contains("mb.Entity<Customer>().Property(e => e.Code).HasMaxLength(40).IsUnicode(false).IsFixedLength();", code);
        Assert.Contains("mb.Entity<Customer>().Property(e => e.Token).HasMaxLength(16).IsFixedLength();", code);
    }
}
