using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using nORM.Core;
using Xunit;

namespace nORM.Tests;

/// <summary>
/// On PostgreSQL a single-column integer primary key with no explicit configuration is a convention
/// store-generated key (mapped to GENERATED BY DEFAULT AS IDENTITY). Add + SaveChanges omits a default (0)
/// key and lets the sequence assign it; the native bulk insert used a fixed COPY column list that INCLUDED
/// the key, writing the literal 0 — GENERATED BY DEFAULT stores an explicit 0 verbatim, so a single row got
/// Id 0 and multiple rows collided on the primary key. Bulk must omit the convention key for default-keyed
/// rows, matching the row-by-row path. Live-only: needs a real PostgreSQL server.
/// </summary>
[Trait("Category", TestCategory.LiveProvider)]
public class LiveProviderPostgresBulkInsertConventionKeyTests
{
    [Table("BckPgFoo")]
    private sealed class Foo
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
    }

    private static async Task ExecuteAsync(DbContext ctx, string sql)
    {
        await using var cmd = ctx.Connection.CreateCommand();
        cmd.CommandText = sql;
        await cmd.ExecuteNonQueryAsync();
    }

    private static async Task<long> ScalarAsync(DbContext ctx, string sql)
    {
        await using var cmd = ctx.Connection.CreateCommand();
        cmd.CommandText = sql;
        return System.Convert.ToInt64(await cmd.ExecuteScalarAsync());
    }

    [Fact]
    public async Task Bulk_insert_of_convention_key_entities_lets_db_generate_keys()
    {
        var live = LiveProviderFactory.OpenLive(ProviderKind.Postgres);
        if (Skip.If(live is null, "Live provider Postgres not configured")) return;

        var (connection, provider) = live!.Value;
        await using (connection)
        using (var ctx = new DbContext(connection, provider))
        {
            await ExecuteAsync(ctx, "DROP TABLE IF EXISTS \"BckPgFoo\"");
            await ExecuteAsync(ctx, "CREATE TABLE \"BckPgFoo\" (\"Id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Name\" TEXT NOT NULL)");
            try
            {
                await ctx.BulkInsertAsync(new[]
                {
                    new Foo { Name = "a" },
                    new Foo { Name = "b" },
                    new Foo { Name = "c" },
                });

                // BUG: all three carried Id 0 -> collide (or a single default row is stored as 0).
                Assert.Equal(0L, await ScalarAsync(ctx, "SELECT COUNT(*) FROM \"BckPgFoo\" WHERE \"Id\" = 0"));
                Assert.Equal(3L, await ScalarAsync(ctx, "SELECT COUNT(DISTINCT \"Id\") FROM \"BckPgFoo\""));
            }
            finally
            {
                await ExecuteAsync(ctx, "DROP TABLE IF EXISTS \"BckPgFoo\"");
            }
        }
    }

    [Fact]
    public async Task Bulk_insert_mixed_explicit_and_default_keys_honors_explicit()
    {
        var live = LiveProviderFactory.OpenLive(ProviderKind.Postgres);
        if (Skip.If(live is null, "Live provider Postgres not configured")) return;

        var (connection, provider) = live!.Value;
        await using (connection)
        using (var ctx = new DbContext(connection, provider))
        {
            await ExecuteAsync(ctx, "DROP TABLE IF EXISTS \"BckPgFoo\"");
            await ExecuteAsync(ctx, "CREATE TABLE \"BckPgFoo\" (\"Id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Name\" TEXT NOT NULL)");
            try
            {
                await ctx.BulkInsertAsync(new[]
                {
                    new Foo { Id = 100, Name = "explicit" },
                    new Foo { Name = "generated" },
                });

                Assert.Equal(1L, await ScalarAsync(ctx, "SELECT COUNT(*) FROM \"BckPgFoo\" WHERE \"Id\" = 100 AND \"Name\" = 'explicit'"));
                Assert.Equal(0L, await ScalarAsync(ctx, "SELECT COUNT(*) FROM \"BckPgFoo\" WHERE \"Id\" = 0"));
                Assert.Equal(2L, await ScalarAsync(ctx, "SELECT COUNT(DISTINCT \"Id\") FROM \"BckPgFoo\""));
            }
            finally
            {
                await ExecuteAsync(ctx, "DROP TABLE IF EXISTS \"BckPgFoo\"");
            }
        }
    }
}
