using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using nORM.Configuration;
using nORM.Core;
using nORM.Enterprise;
using nORM.Providers;
using Xunit;

#nullable enable

namespace nORM.Tests;

/// <summary>
/// SaveChanges atomicity + error-path tracker consistency. Each test triggers a failure (or a rollback)
/// mid-save and asserts the DB and the in-memory ChangeTracker end in a mutually-consistent, non-lossy state.
/// </summary>
[Xunit.Trait("Category", "Fast")]
public class SaveChangesAtomicityConsistencyTests
{
    // ---- Convention-key entity (bare int Id => store-generated by SQLite convention, IsDbGenerated == false) ----
    [Table("ChkItem")]
    private class ChkItem
    {
        public int Id { get; set; }               // convention store-generated key
        public string Name { get; set; } = "";
        public int Value { get; set; }
    }

    // ---- Client-assigned key entity ----
    [Table("CliItem")]
    private class CliItem
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)] public int Id { get; set; }
        public string Name { get; set; } = "";
    }

    // ---- OCC entity (client-managed token on SQLite) ----
    [Table("OccItem")]
    private class OccItem
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)] public int Id { get; set; }
        public string Payload { get; set; } = "";
        [Timestamp] public byte[] Token { get; set; } = Array.Empty<byte>();
    }

    private static SqliteConnection Open(string ddl)
    {
        var cn = new SqliteConnection("Data Source=:memory:");
        cn.Open();
        using var cmd = cn.CreateCommand();
        cmd.CommandText = ddl;
        cmd.ExecuteNonQuery();
        return cn;
    }

    private static int Count(SqliteConnection cn, string table)
    {
        using var cmd = cn.CreateCommand();
        cmd.CommandText = $"SELECT COUNT(*) FROM {table}";
        return Convert.ToInt32(cmd.ExecuteScalar());
    }

    private static DbContext MakeCtx<T>(SqliteConnection cn, RetryPolicy? retry = null, IDbCommandInterceptor? icept = null) where T : class
    {
        var opts = new DbContextOptions { OnModelCreating = mb => mb.Entity<T>(), RetryPolicy = retry };
        if (icept != null) opts.CommandInterceptors.Add(icept);
        return new DbContext(cn, new SqliteProvider(), opts);
    }

    // ============================================================================
    // SURFACE 1 — Partial batch failure with CONVENTION keys: atomic rollback + clean re-save.
    // ============================================================================
    [Fact]
    public async Task ConventionKey_partial_batch_failure_rolls_back_all_and_resaves_cleanly()
    {
        using var cn = Open("CREATE TABLE ChkItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Value INTEGER NOT NULL CHECK (Value < 500))");
        await using var ctx = MakeCtx<ChkItem>(cn);

        var items = new List<ChkItem>();
        for (int i = 0; i < 50; i++)
        {
            var e = new ChkItem { Name = $"n{i}", Value = i == 25 ? 999 : i };  // one violates CHECK
            items.Add(e);
            ctx.Add(e);
        }

        await Assert.ThrowsAnyAsync<Exception>(() => ctx.SaveChangesAsync());
        Assert.Equal(0, Count(cn, "ChkItem"));   // atomic: nothing persisted

        // Fix the offending value and re-save on the SAME context/tracker.
        items[25].Value = 25;
        await ctx.SaveChangesAsync();

        Assert.Equal(50, Count(cn, "ChkItem"));                       // exactly once
        Assert.Equal(50, items.Select(i => i.Id).Distinct().Count()); // all distinct keys
        Assert.All(items, i => Assert.True(i.Id > 0));                // all keys assigned
    }

    // ============================================================================
    // SURFACE 3 (variant) — CONVENTION key stamped on attempt 1, rolled back, retried.
    // The store-generated (convention) key is NOT captured by addedKeySnapshot; verify the
    // retry does not silently drop the row nor duplicate it.
    // ============================================================================
    private sealed class ThrowOnceOnTable : IDbCommandInterceptor
    {
        private readonly string _needle;
        private int _fired;
        public int FireCount => _fired;
        public ThrowOnceOnTable(string needle) => _needle = needle;
        public Task<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c, DbContext ctx, CancellationToken ct)
        {
            if (c.CommandText.Contains(_needle, StringComparison.Ordinal) && Interlocked.Exchange(ref _fired, 1) == 0)
                throw new SqliteException("Injected transient lock", 6);
            return Task.FromResult(InterceptionResult<int>.Continue());
        }
        public Task NonQueryExecutedAsync(DbCommand c, DbContext ctx, int r, TimeSpan d, CancellationToken ct) => Task.CompletedTask;
        public Task<InterceptionResult<object?>> ScalarExecutingAsync(DbCommand c, DbContext ctx, CancellationToken ct) => Task.FromResult(InterceptionResult<object?>.Continue());
        public Task ScalarExecutedAsync(DbCommand c, DbContext ctx, object? r, TimeSpan d, CancellationToken ct) => Task.CompletedTask;
        public Task<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c, DbContext ctx, CancellationToken ct) => Task.FromResult(InterceptionResult<DbDataReader>.Continue());
        public Task ReaderExecutedAsync(DbCommand c, DbContext ctx, DbDataReader r, TimeSpan d, CancellationToken ct) => Task.CompletedTask;
        public Task CommandFailedAsync(DbCommand c, DbContext ctx, Exception ex, CancellationToken ct) => Task.CompletedTask;
    }

    [Table("CkParent")]
    private class CkParent { public int Id { get; set; } public string Name { get; set; } = ""; }
    [Table("CkChild")]
    private class CkChild { [Key, DatabaseGenerated(DatabaseGeneratedOption.None)] public int Id { get; set; } public string Name { get; set; } = ""; }

    [Fact]
    public async Task ConventionKey_retry_after_rollback_reinserts_exactly_once()
    {
        using var cn = Open(
            "CREATE TABLE CkParent (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL);" +
            "CREATE TABLE CkChild (Id INTEGER PRIMARY KEY, Name TEXT NOT NULL);");
        var icept = new ThrowOnceOnTable("CkChild");
        var retry = new RetryPolicy { MaxRetries = 3, BaseDelay = TimeSpan.FromMilliseconds(1), ShouldRetry = ex => ex is SqliteException };
        var opts = new DbContextOptions
        {
            OnModelCreating = mb => { mb.Entity<CkParent>(); mb.Entity<CkChild>(); },
            RetryPolicy = retry
        };
        opts.CommandInterceptors.Add(icept);
        await using var ctx = new DbContext(cn, new SqliteProvider(), opts);

        var parent = new CkParent { Name = "keep-me" };  // convention key -> stamped on attempt 1
        ctx.Add(parent);
        ctx.Add(new CkChild { Id = 100, Name = "child" }); // its insert throws once -> rollback + retry

        await ctx.SaveChangesAsync();

        Assert.Equal(1, icept.FireCount);
        Assert.Equal(1, Count(cn, "CkParent"));  // parent must NOT be silently dropped
        Assert.Equal(1, Count(cn, "CkChild"));
        Assert.True(parent.Id > 0);
    }

    // ============================================================================
    // SURFACE 6 — OCC stale token mid multi-row UPDATE batch: whole batch atomic + tracker consistent.
    // ============================================================================
    [Fact]
    public async Task Occ_stale_token_mid_batch_rolls_back_whole_batch_and_good_row_resaves()
    {
        using var cn = Open("CREATE TABLE OccItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Payload TEXT NOT NULL, Token BLOB NOT NULL)");
        using (var seed = cn.CreateCommand())
        {
            seed.CommandText = "INSERT INTO OccItem (Payload, Token) VALUES ('a', X'01'), ('b', X'01')";
            seed.ExecuteNonQuery();
        }
        await using var ctx = MakeCtx<OccItem>(cn);

        var rows = await ctx.Query<OccItem>().OrderBy(r => r.Id).ToListAsync();
        Assert.Equal(2, rows.Count);

        // Externally bump row 2's token so nORM's snapshot is stale -> its UPDATE matches 0 rows.
        using (var ext = cn.CreateCommand())
        {
            ext.CommandText = "UPDATE OccItem SET Token = X'02' WHERE Id = 2";
            ext.ExecuteNonQuery();
        }

        rows[0].Payload = "a-new";
        rows[1].Payload = "b-new";
        ctx.Update(rows[0]);
        ctx.Update(rows[1]);

        await Assert.ThrowsAsync<DbConcurrencyException>(() => ctx.SaveChangesAsync());

        // Atomicity: row 1's update must be rolled back too (row 2 keeps the external 'b', token 02).
        using (var q = cn.CreateCommand())
        {
            q.CommandText = "SELECT Payload FROM OccItem WHERE Id = 1";
            Assert.Equal("a", q.ExecuteScalar() as string);  // NOT 'a-new'
        }

        // Tracker consistency: fix the stale row (reload its token) and re-save; row 1's edit must still apply.
        rows[1].Token = new byte[] { 0x02 };
        ctx.Entry(rows[1]).OriginalValues["Token"] = new byte[] { 0x02 };
        await ctx.SaveChangesAsync();

        using (var q = cn.CreateCommand())
        {
            q.CommandText = "SELECT Payload FROM OccItem WHERE Id = 1";
            Assert.Equal("a-new", q.ExecuteScalar() as string);   // row 1's pending edit survived + applied
        }
    }

    // ============================================================================
    // SURFACE 7 — DELETE + re-INSERT of the SAME client-assigned key in one SaveChanges.
    // The old row must be replaced by the new values, and the tracker identity map must resolve K
    // to the NEW entity.
    // ============================================================================
    [Fact]
    public async Task Delete_then_readd_same_key_in_one_save_replaces_row_and_fixes_identity_map()
    {
        using var cn = Open("CREATE TABLE CliItem (Id INTEGER PRIMARY KEY, Name TEXT NOT NULL)");
        await using var ctx = MakeCtx<CliItem>(cn);

        var original = new CliItem { Id = 7, Name = "original" };
        ctx.Add(original);
        await ctx.SaveChangesAsync();
        Assert.Equal(1, Count(cn, "CliItem"));

        // Remove the tracked row and add a brand-new instance at the same key in one unit of work.
        ctx.Remove(original);
        var replacement = new CliItem { Id = 7, Name = "replacement" };
        ctx.Add(replacement);
        await ctx.SaveChangesAsync();

        Assert.Equal(1, Count(cn, "CliItem"));
        using (var q = cn.CreateCommand())
        {
            q.CommandText = "SELECT Name FROM CliItem WHERE Id = 7";
            Assert.Equal("replacement", q.ExecuteScalar() as string);
        }

        // Identity map: a fresh query must return the replacement, and a further edit must persist.
        replacement.Name = "edited";
        ctx.Update(replacement);
        await ctx.SaveChangesAsync();
        using (var q = cn.CreateCommand())
        {
            q.CommandText = "SELECT Name FROM CliItem WHERE Id = 7";
            Assert.Equal("edited", q.ExecuteScalar() as string);
        }
    }

    // ============================================================================
    // SURFACE 4 — Caller-owned tx: convention-key insert, ROLL BACK via wrapper, then reuse the
    // context. The still-Added entity must be re-inserted, not silently dropped.
    // ============================================================================
    [Fact]
    public async Task CallerOwnedTx_convention_insert_rolled_back_then_resaved_reinserts()
    {
        using var cn = Open("CREATE TABLE ChkItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Value INTEGER NOT NULL)");
        await using var ctx = MakeCtx<ChkItem>(cn);

        var e = new ChkItem { Name = "x", Value = 1 };
        await using (var tx = await ctx.Database.BeginTransactionAsync())
        {
            ctx.Add(e);
            await ctx.SaveChangesAsync();       // inserts, convention key stamped, stays Added
            Assert.Equal(1, Count(cn, "ChkItem"));
            await tx.RollbackAsync();           // DB reverts; entity must remain re-insertable
        }

        Assert.Equal(0, Count(cn, "ChkItem"));  // rolled back

        // Reuse the context: the still-Added entity must be re-inserted.
        await ctx.SaveChangesAsync();
        Assert.Equal(1, Count(cn, "ChkItem"));  // NOT silently dropped
    }

    // ============================================================================
    // SURFACE 4b — Caller-owned tx: DELETE flushed then rolled back; the row must be restored AND
    // a re-save must re-delete it (tracker not wrongly reconciled).
    // ============================================================================
    [Fact]
    public async Task CallerOwnedTx_delete_rolled_back_then_resaved_redeletes()
    {
        using var cn = Open("CREATE TABLE CliItem (Id INTEGER PRIMARY KEY, Name TEXT NOT NULL)");
        await using var ctx = MakeCtx<CliItem>(cn);

        var e = new CliItem { Id = 1, Name = "row" };
        ctx.Add(e);
        await ctx.SaveChangesAsync();
        Assert.Equal(1, Count(cn, "CliItem"));

        await using (var tx = await ctx.Database.BeginTransactionAsync())
        {
            ctx.Remove(e);
            await ctx.SaveChangesAsync();       // flushes DELETE (row gone in tx)
            Assert.Equal(0, Count(cn, "CliItem"));
            await tx.RollbackAsync();           // DB reverts -> row back
        }

        Assert.Equal(1, Count(cn, "CliItem"));  // row restored

        // The entity is still tracked Deleted; a re-save must re-delete it (not silently skip).
        await ctx.SaveChangesAsync();
        Assert.Equal(0, Count(cn, "CliItem"));
    }
}
