using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Xunit;

namespace nORM.Tests;

[Trait("Category", TestCategory.Fast)]
public partial class ScaffoldingContractDocTests
{
    [Fact]
    public void Docs_and_gate_pin_recent_scaffold_hardening_scope()
    {
        var doc = ReadDoc();
        var rootReadme = ReadRepoFile("README.md");
        var cliReadme = ReadRepoFile("src", "dotnet-norm", "README.md");
        var releaseGates = ReadRepoFile("docs", "release-gates.md");
        var source = ReadStaticEntityScaffoldSource();
        var joinDiagnosticBuilderSource = ReadJoinTableDiagnosticSource();
        var relationshipDiscoverySource = ReadRelationshipDiscoverySource();
        var featureMapBuilderSource = ReadRepoFile("src", "nORM", "Scaffolding", "ScaffoldFeatureMapBuilder.cs");
        var columnDiscoverySource = ReadColumnDiscoverySource();
        var contextWriterSource = ReadContextWriterSource();
        var diagnosticsWriterSource = ReadDiagnosticsWriterSource();
        var manyToManyDiscoverySource = ReadManyToManyDiscoverySource();
        var postgresUnsupportedSource = ReadPostgresUnsupportedFeatureSource();
        var sqlServerUnsupportedSource = ReadSqlServerUnsupportedFeatureSource();
        var mySqlUnsupportedSource = ReadMySqlUnsupportedFeatureSource();
        var sqliteUnsupportedSource = ReadSqliteUnsupportedFeatureSource();
        var sqliteDdlParserSource = ReadRepoFile("src", "nORM", "Scaffolding", "ScaffoldSqliteDdlParser.DeclaredTypes.cs");
        var dynamicSource = ReadDynamicEntitySource();
        var providerTypeClassifierSource = ReadProviderSpecificTypeClassifierSource();
        var unsupportedMetadataSource = ReadUnsupportedFeatureMetadataSource();
        var defaultValidator = ReadRepoFile("src", "nORM", "Migration", "DefaultValueValidator.cs");
        var liveScaffoldTests = ReadLiveProviderScaffoldingParitySource();
        var liveScaffoldCliTests = ReadLiveProviderScaffoldCliParitySource();

        Assert.Contains("Repeated scaffolds of the same schema", cliReadme, StringComparison.Ordinal);
        Assert.Contains("ordered deterministically", cliReadme, StringComparison.Ordinal);
        Assert.Contains("stale `nORM.ScaffoldWarnings.*`", cliReadme, StringComparison.Ordinal);
        Assert.Contains("role-based self-referencing FK and self-join navigations", cliReadme, StringComparison.Ordinal);
        Assert.Contains("SQLite rowid integer primary keys are generated as non-null `long`", rootReadme, StringComparison.Ordinal);
        Assert.Contains("unsafe provider-specific columns such as SQL Server/SQLite spatial", rootReadme, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL `inet`, or MySQL spatial columns", rootReadme, StringComparison.Ordinal);
        Assert.Contains("unsafe provider-specific columns such as SQL Server/SQLite spatial", cliReadme, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL `inet`, or MySQL spatial columns", cliReadme, StringComparison.Ordinal);
        Assert.Contains("unsafe MySQL `set(...)` declarations", rootReadme, StringComparison.Ordinal);
        Assert.Contains("unsafe MySQL `set(...)` declarations", cliReadme, StringComparison.Ordinal);
        Assert.Contains("exact ordered unfiltered unique indexes", rootReadme, StringComparison.Ordinal);
        Assert.Contains("exact ordered unfiltered unique index", cliReadme, StringComparison.Ordinal);
        Assert.Contains("one-to-one reference navigations for exact unique dependent FKs", rootReadme, StringComparison.Ordinal);
        Assert.Contains("one-to-one reference navigations when the dependent FK columns are exact unique", cliReadme, StringComparison.Ordinal);
        Assert.Contains("complex/provider-specific defaults", rootReadme, StringComparison.Ordinal);
        Assert.Contains("unmodeled complex/provider-specific defaults", cliReadme, StringComparison.Ordinal);
        Assert.Contains("Safe SQL defaults, including vetted hex/binary literals and PostgreSQL", rootReadme, StringComparison.Ordinal);
        Assert.Contains("Safe SQL defaults, including vetted hex/binary literals and PostgreSQL", cliReadme, StringComparison.Ordinal);
        Assert.Contains("explicit non-system default-constraint names are preserved", rootReadme, StringComparison.Ordinal);
        Assert.Contains("explicit non-system default-constraint names are preserved", cliReadme, StringComparison.Ordinal);
        Assert.Contains("HasDefaultValueSql(..., constraintName: ...)", rootReadme, StringComparison.Ordinal);
        Assert.Contains("HasDefaultValueSql(..., constraintName: ...)", cliReadme, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL domains over safe scalar/array/enum base types remain diagnostics", rootReadme, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL domains over safe scalar/array/enum base types remain diagnostics", cliReadme, StringComparison.Ordinal);
        Assert.Contains("SQL Server alias types over scaffoldable scalar/binary bases remain diagnostics", rootReadme, StringComparison.Ordinal);
        Assert.Contains("SQL Server alias types over scaffoldable scalar/binary bases remain diagnostics", cliReadme, StringComparison.Ordinal);
        Assert.Contains("MySQL expression indexes exposed by `SHOW INDEX` are emitted", rootReadme, StringComparison.Ordinal);
        Assert.Contains("MySQL expression indexes exposed by `SHOW INDEX` are emitted", cliReadme, StringComparison.Ordinal);
        Assert.DoesNotContain("SQL Server/MySQL expression-index shapes are kept", rootReadme, StringComparison.Ordinal);
        Assert.Contains("TryMapSqlServerAliasBaseClrType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("NormalizeSqlServerAliasBaseTypeName", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("GetSqlServerAliasBaseMaxLength", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("GetSqlServerAliasColumnBaseTypes", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("TryMapSqlServerAliasBaseClrType", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetSqlServerAliasBaseMaxLengthFromTypeText", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("alias base", doc, StringComparison.Ordinal);
        Assert.Contains("bounded string/binary length", doc, StringComparison.Ordinal);
        Assert.Contains("preserves bounded string/numeric facets where provider", rootReadme, StringComparison.Ordinal);
        Assert.Contains("preserves bounded string/numeric facets where provider", cliReadme, StringComparison.Ordinal);
        Assert.Contains("the generated entity read-only", cliReadme, StringComparison.Ordinal);
        Assert.Contains("unknown provider-specific referential actions", rootReadme, StringComparison.Ordinal);
        Assert.Contains("unknown provider-specific referential actions", cliReadme, StringComparison.Ordinal);
        Assert.Contains("unparsed provider-specific identity strategies that make the generated entity read-only", rootReadme, StringComparison.Ordinal);
        Assert.Contains("unparsed provider-specific identity strategies that make the generated entity read-only", cliReadme, StringComparison.Ordinal);
        Assert.Contains("stale warning reports", rootReadme, StringComparison.Ordinal);
        Assert.Contains("SQLite rowid integer primary keys are normalized to non-null `long`", doc, StringComparison.Ordinal);
        Assert.Contains("reference-column `[Required]` parity", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server alias/user-defined column types are reported with schema/name", doc, StringComparison.Ordinal);
        Assert.Contains("base system type, and bounded facets when available", doc, StringComparison.Ordinal);
        Assert.Contains("Unsigned decimal/numeric columns keep `decimal` storage plus precision/scale", doc, StringComparison.Ordinal);
        Assert.Contains("larger or", doc, StringComparison.Ordinal);
        Assert.Contains("ambiguous `set(...)` definitions remain diagnostics and make static or", doc, StringComparison.Ordinal);
        Assert.Contains("malformed comma structure", doc, StringComparison.Ordinal);
        Assert.Contains("runtime dynamic generated entity types read-only", doc, StringComparison.Ordinal);
        Assert.Contains("Required reference navigations", doc, StringComparison.Ordinal);
        Assert.Contains("Optional reference navigations remain nullable", doc, StringComparison.Ordinal);
        Assert.Contains("one-to-one `HasOne(...).WithOne(...)` relationship", doc, StringComparison.Ordinal);
        Assert.Contains("required and optional single-column FK column sets", doc, StringComparison.Ordinal);
        Assert.Contains("optional composite FK column sets", doc, StringComparison.Ordinal);
        Assert.Contains("dependent FKs keep nullable scalar FK columns", doc, StringComparison.Ordinal);
        Assert.Contains("nullable scalar FK columns and the dependent reference", doc, StringComparison.Ordinal);
        Assert.Contains("shared primary-key one-to-one", doc, StringComparison.Ordinal);
        Assert.Contains("dependent PK is also the FK", doc, StringComparison.Ordinal);
        Assert.Contains("FK-role-based reference navigation", doc, StringComparison.Ordinal);
        Assert.Contains("do not produce possible-join-table warnings", doc, StringComparison.Ordinal);
        Assert.Contains("composite FK relationships use the distinguishing FK", doc, StringComparison.Ordinal);
        Assert.Contains("shared tenant or partition column", doc, StringComparison.Ordinal);
        Assert.Contains("database-name preservation with role-named FK navigations", doc, StringComparison.Ordinal);
        Assert.Contains("one-to-one reference navigation generation for required and", doc, StringComparison.Ordinal);
        Assert.Contains("shared-primary-key", doc, StringComparison.Ordinal);
        Assert.Contains("role-named multiple unique dependent FKs", doc, StringComparison.Ordinal);
        Assert.Contains("otherwise the principal side remains a collection navigation", doc, StringComparison.Ordinal);
        Assert.Contains("nullable and non-null alternate-key FK generation", doc, StringComparison.Ordinal);
        Assert.Contains("Self-referencing pure join tables", doc, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_one_to_one_for_unique_dependent_fk_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_optional_one_to_one_for_nullable_unique_dependent_fk_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_role_named_one_to_one_for_multiple_unique_dependent_fks_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_one_to_one_for_shared_primary_key_fk_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_one_to_one_for_composite_unique_dependent_fk_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_optional_one_to_one_for_nullable_composite_unique_dependent_fk_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_role_named_navigations_for_multiple_composite_fks_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_preserves_database_names_and_role_navigations_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("ScaffoldAsync_generates_fk_to_nullable_unique_index_on_live_provider", liveScaffoldTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_database_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_mixed_single_fk_and_many_to_many_shape_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_composite_primary_key_fk_model_shape_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_composite_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_many_to_many_referential_actions_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_shared_tenant_alternate_key_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_alternate_key_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_self_referencing_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_surrogate_key_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_database_generated_bridge_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_composite_surrogate_key_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_keeps_composite_payload_join_as_explicit_entity_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_rejects_filtered_unique_surrogate_join_table_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_schema_qualified_many_to_many_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_composite_fk_to_unique_index_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_role_named_composite_fks_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_role_named_one_to_one_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_required_and_optional_unique_dependent_one_to_one_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_shared_primary_key_one_to_one_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_composite_unique_dependent_one_to_one_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_optional_composite_unique_dependent_one_to_one_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_suppresses_keyless_dependent_relationship_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_json_fail_on_warnings_reports_live_provider_diagnostics", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_provider_option_accepts_ef_provider_package_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_honors_connection_provider_option_precedence_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_dbcontext_scaffold_accepts_ef_provider_package_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_valid_unique_identifiers_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_respects_project_namespace_context_dir_and_nullable_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_reads_directory_build_props_project_metadata_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_project_metadata_overrides_directory_build_props_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_accepts_project_directory_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_accepts_project_and_force_short_aliases_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_accepts_short_aliases_and_qualified_context_namespace_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_infers_current_directory_project_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_inferred_current_directory_project_reads_named_connection_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_inferred_current_directory_project_user_secrets_override_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_no_project_reads_named_connection_current_directory_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_no_project_pass_through_environment_selects_current_directory_appsettings_environment_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_uses_dotnet_ef_config_startup_named_connection_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_cli_options_override_dotnet_ef_config_defaults_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_startup_project_named_connection_overrides_target_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_startup_project_directory_named_connection_overrides_target_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_startup_project_named_connection_shorthand_overrides_target_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_startup_project_user_secrets_override_target_user_secrets_and_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_omitted_context_uses_named_connection_leaf_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_named_connection_shorthand_reads_project_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_named_connection_user_secrets_override_project_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_named_connection_environment_overrides_project_appsettings_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_named_connection_environment_overrides_project_user_secrets_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_named_connection_environment_overrides_startup_and_target_user_secrets_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_pass_through_environment_selects_appsettings_environment_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_startup_project_pass_through_environment_selects_startup_appsettings_environment_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_startup_project_dotnet_environment_selects_startup_appsettings_environment_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_ambient_environment_selects_appsettings_environment_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_enforces_output_safety_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_accepts_csv_and_multi_value_table_filters_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_accepts_csv_and_multi_value_schema_filters_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_unions_schema_and_table_filters_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_accepts_no_onconfiguring_data_annotations_and_no_pluralize_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_singularizes_plural_table_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_emits_routine_stubs_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_emits_advanced_routine_stubs_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_emits_routine_output_and_non_query_wrappers_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_emits_sequence_stubs_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_table_filter_suppresses_unselected_principal_relationship_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_table_filter_emits_view_query_artifact_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_emits_provider_query_artifacts_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_default_discovery_emits_table_and_view_query_artifacts_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_non_nullable_alternate_key_relationship_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_generates_nullable_alternate_key_relationship_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_suppresses_synthetic_fk_constraint_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_promotes_safe_feature_metadata_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_suppresses_synthetic_check_constraint_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_suppresses_synthetic_unique_constraint_index_names_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_reports_trigger_diagnostics_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_reports_provider_specific_column_diagnostics_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_safe_provider_specific_columns_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_writable_provider_specific_diagnostics_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_fk_referential_actions_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_restrict_fk_referential_actions_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_set_default_fk_referential_actions_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_scalar_facets_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_index_metadata_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_preserves_provider_index_metadata_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("--use-database-names --no-pluralize", doc, StringComparison.Ordinal);
        Assert.Contains("Default plural table-name singularization", doc, StringComparison.Ordinal);
        Assert.Contains("Invalid table/column identifiers", doc, StringComparison.Ordinal);
        Assert.Contains("duplicate normalized entity", doc, StringComparison.Ordinal);
        Assert.Contains("object-member column names", doc, StringComparison.Ordinal);
        Assert.Contains("Project-targeted scaffold", doc, StringComparison.Ordinal);
        Assert.Contains("`--project`, project-relative `--output-dir`", doc, StringComparison.Ordinal);
        Assert.Contains("project nullable-reference settings", doc, StringComparison.Ordinal);
        Assert.Contains("Inherited", doc, StringComparison.Ordinal);
        Assert.Contains("`Directory.Build.props` metadata", doc, StringComparison.Ordinal);
        Assert.Contains("root namespace, nullable-reference settings", doc, StringComparison.Ordinal);
        Assert.Contains("user-secrets connection", doc, StringComparison.Ordinal);
        Assert.Contains("Project-file", doc, StringComparison.Ordinal);
        Assert.Contains("metadata overrides conflicting", doc, StringComparison.Ordinal);
        Assert.Contains("AssemblyName fallback", doc, StringComparison.Ordinal);
        Assert.Contains("Passing a single-project", doc, StringComparison.Ordinal);
        Assert.Contains("directory to `--project` instead of a `.csproj` file", doc, StringComparison.Ordinal);
        Assert.Contains("relative output and context paths remain project-relative", doc, StringComparison.Ordinal);
        Assert.Contains("Short `-p` and `-f` aliases", doc, StringComparison.Ordinal);
        Assert.Contains("overwrite stale project-relative generated files", doc, StringComparison.Ordinal);
        Assert.Contains("EF-style short aliases", doc, StringComparison.Ordinal);
        Assert.Contains("`-o`, `-n`, `-c`, and `-t`", doc, StringComparison.Ordinal);
        Assert.Contains("`--context-namespace` overrides", doc, StringComparison.Ordinal);
        Assert.Contains("final context class-name segment", doc, StringComparison.Ordinal);
        Assert.Contains("contains exactly one `.csproj`", doc, StringComparison.Ordinal);
        Assert.Contains("infers that current-directory project", doc, StringComparison.Ordinal);
        Assert.Contains("inferred current-directory project appsettings", doc, StringComparison.Ordinal);
        Assert.Contains("inferred current-directory project user secrets", doc, StringComparison.Ordinal);
        Assert.Contains("override inferred-project appsettings", doc, StringComparison.Ordinal);
        Assert.Contains("No-project current-directory appsettings", doc, StringComparison.Ordinal);
        Assert.Contains("no-project current-directory environment-specific appsettings", doc, StringComparison.Ordinal);
        Assert.Contains("current-directory-relative output and context paths", doc, StringComparison.Ordinal);
        Assert.Contains("project-relative output and context paths", doc, StringComparison.Ordinal);
        Assert.Contains("builds the generated project", doc, StringComparison.Ordinal);
        Assert.Contains("EF-style `.config/dotnet-ef.json`", doc, StringComparison.Ordinal);
        Assert.Contains("config-supplied `project`, `startupProject`, and `context`", doc, StringComparison.Ordinal);
        Assert.Contains("Expanded config-supplied output directory, namespace", doc, StringComparison.Ordinal);
        Assert.Contains("context directory, context namespace, table filters", doc, StringComparison.Ordinal);
        Assert.Contains("overwrite", doc, StringComparison.Ordinal);
        Assert.Contains("defaults are likewise verified through real CLI scaffolds", doc, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_dotnet_ef_config_expanded_defaults_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("`Name=...` named connections from startup-project `appsettings.json`", doc, StringComparison.Ordinal);
        Assert.Contains("Explicit CLI", doc, StringComparison.Ordinal);
        Assert.Contains("`--project`, `--startup-project`, and", doc, StringComparison.Ordinal);
        Assert.Contains("`--context` values", doc, StringComparison.Ordinal);
        Assert.Contains("override conflicting", doc, StringComparison.Ordinal);
        Assert.Contains("`.config/dotnet-ef.json` defaults", doc, StringComparison.Ordinal);
        Assert.Contains("Explicit `--startup-project`/`-s` named-connection", doc, StringComparison.Ordinal);
        Assert.Contains("startup-project", doc, StringComparison.Ordinal);
        Assert.Contains("`appsettings.json` wins over target-project", doc, StringComparison.Ordinal);
        Assert.Contains("target-project `appsettings.json`", doc, StringComparison.Ordinal);
        Assert.Contains("single-project startup directories are accepted", doc, StringComparison.Ordinal);
        Assert.Contains("startup-project shorthand `Name=AppDb`", doc, StringComparison.Ordinal);
        Assert.Contains("resolves through startup-project", doc, StringComparison.Ordinal);
        Assert.Contains("`ConnectionStrings:AppDb` entries", doc, StringComparison.Ordinal);
        Assert.Contains("Startup-project", doc, StringComparison.Ordinal);
        Assert.Contains("user secrets declared through `UserSecretsId`", doc, StringComparison.Ordinal);
        Assert.Contains("startup-project user-secret connection wins over", doc, StringComparison.Ordinal);
        Assert.Contains("target-project user secrets", doc, StringComparison.Ordinal);
        Assert.Contains("Omitting `--context` with a named connection", doc, StringComparison.Ordinal);
        Assert.Contains("uses that named leaf", doc, StringComparison.Ordinal);
        Assert.Contains("duplicate `Context` suffix", doc, StringComparison.Ordinal);
        Assert.Contains("Lowercase named-connection shorthand", doc, StringComparison.Ordinal);
        Assert.Contains("target-project", doc, StringComparison.Ordinal);
        Assert.Contains("`ConnectionStrings:AppDb` appsettings", doc, StringComparison.Ordinal);
        Assert.Contains("Named-connection environment variable precedence", doc, StringComparison.Ordinal);
        Assert.Contains("`ConnectionStrings__Name`", doc, StringComparison.Ordinal);
        Assert.Contains("also override project user secrets", doc, StringComparison.Ordinal);
        Assert.Contains("startup-project and target-project user secrets", doc, StringComparison.Ordinal);
        Assert.Contains("environment-selected live database", doc, StringComparison.Ordinal);
        Assert.Contains("Project user secrets declared through `UserSecretsId`", doc, StringComparison.Ordinal);
        Assert.Contains("user-secret connection wins over target-project", doc, StringComparison.Ordinal);
        Assert.Contains("secret-selected", doc, StringComparison.Ordinal);
        Assert.Contains("Ambient", doc, StringComparison.Ordinal);
        Assert.Contains("startup-project", doc, StringComparison.Ordinal);
        Assert.Contains("`appsettings.Production.json`", doc, StringComparison.Ordinal);
        Assert.Contains("target-project environment files", doc, StringComparison.Ordinal);
        Assert.Contains("`ASPNETCORE_ENVIRONMENT=Staging`", doc, StringComparison.Ordinal);
        Assert.Contains("`DOTNET_ENVIRONMENT=Development`", doc, StringComparison.Ordinal);
        Assert.Contains("startup-project `appsettings.Development.json`", doc, StringComparison.Ordinal);
        Assert.Contains("environment-specific appsettings lookup builds", doc, StringComparison.Ordinal);
        Assert.Contains("Output-safety semantics", doc, StringComparison.Ordinal);
        Assert.Contains("successful `--dry-run --json`", doc, StringComparison.Ordinal);
        Assert.Contains("`--no-overwrite`", doc, StringComparison.Ordinal);
        Assert.Contains("`--force --json` removes stale", doc, StringComparison.Ordinal);
        Assert.Contains("CSV `--tables` filters", doc, StringComparison.Ordinal);
        Assert.Contains("multi-value `--table First Second`", doc, StringComparison.Ordinal);
        Assert.Contains("filter parsing and provider", doc, StringComparison.Ordinal);
        Assert.Contains("catalog matching stay aligned", doc, StringComparison.Ordinal);
        Assert.Contains("CSV `--schemas` filters", doc, StringComparison.Ordinal);
        Assert.Contains("multi-value `--schema Accounting Sales` filters", doc, StringComparison.Ordinal);
        Assert.Contains("real CLI across all four providers", doc, StringComparison.Ordinal);
        Assert.Contains("MySQL's current database as a filter-only catalog", doc, StringComparison.Ordinal);
        Assert.Contains("unqualified model metadata", doc, StringComparison.Ordinal);
        Assert.Contains("Combined `--schema` plus explicit `--table`", doc, StringComparison.Ordinal);
        Assert.Contains("schema-selected tables and explicitly selected tables are generated", doc, StringComparison.Ordinal);
        Assert.Contains("outside the selected SQL Server/PostgreSQL schemas stay", doc, StringComparison.Ordinal);
        Assert.Contains("`--no-onconfiguring` emits no `OnConfiguring`", doc, StringComparison.Ordinal);
        Assert.Contains("hard-coded scaffold connection string", doc, StringComparison.Ordinal);
        Assert.Contains("`--data-annotations` is accepted", doc, StringComparison.Ordinal);
        Assert.Contains("`--no-pluralize` disables", doc, StringComparison.Ordinal);
        Assert.Contains("common", doc, StringComparison.Ordinal);
        Assert.Contains("output switches `--json`, `--verbose`, `--no-color`, and `--prefix-output`", doc, StringComparison.Ordinal);
        Assert.Contains("successful machine-readable summary", doc, StringComparison.Ordinal);
        Assert.Contains("\"--json \"", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("\"--verbose \"", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("\"--no-color \"", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("\"--prefix-output \"", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("alternate-key many-to-many", doc, StringComparison.Ordinal);
        Assert.Contains("--fail-on-warnings --json", doc, StringComparison.Ordinal);
        Assert.Contains("Explicit `--provider <EF Core provider package>`", doc, StringComparison.Ordinal);
        Assert.Contains("parser precedence", doc, StringComparison.Ordinal);
        Assert.Contains("duplicate named and", doc, StringComparison.Ordinal);
        Assert.Contains("positional connection/provider values are rejected", doc, StringComparison.Ordinal);
        Assert.Contains("provider after `--connection`", doc, StringComparison.Ordinal);
        Assert.Contains("dbcontext scaffold <connection> <provider-package>", doc, StringComparison.Ordinal);
        Assert.Contains("compatibility design-time switch bundle", doc, StringComparison.Ordinal);
        Assert.Contains("`--no-build`, `--framework`", doc, StringComparison.Ordinal);
        Assert.Contains("`--msbuildprojectextensionspath`", doc, StringComparison.Ordinal);
        Assert.Contains("Provider-bound routine stubs are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("--emit-routine-stubs", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server/PostgreSQL/MySQL routine comments", doc, StringComparison.Ordinal);
        Assert.Contains("Advanced routine wrappers", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server scalar/table-valued", doc, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL array/UUID routine parameters", doc, StringComparison.Ordinal);
        Assert.Contains("MySQL unsigned", doc, StringComparison.Ordinal);
        Assert.Contains("output-parameter routine factories", doc, StringComparison.Ordinal);
        Assert.Contains("no-result stored procedure non-query wrappers", doc, StringComparison.Ordinal);
        Assert.Contains("Provider-bound sequence stubs are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("--emit-sequence-stubs", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server/PostgreSQL sequence comments", doc, StringComparison.Ordinal);
        Assert.Contains("relationships to unselected principal tables are", doc, StringComparison.Ordinal);
        Assert.Contains("mixed one-to-many plus many-to-many model shape", doc, StringComparison.Ordinal);
        Assert.Contains("composite index metadata through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("direct composite primary-key FK model shape", doc, StringComparison.Ordinal);
        Assert.Contains("generated composite `HasKey` and fluent FK selectors", doc, StringComparison.Ordinal);
        Assert.Contains("selected ordinary", doc, StringComparison.Ordinal);
        Assert.Contains("views are emitted as read-only query artifacts", doc, StringComparison.Ordinal);
        Assert.Contains("Default and schema-scoped CLI discovery also", doc, StringComparison.Ordinal);
        Assert.Contains("ordinary views are emitted with discovered tables", doc, StringComparison.Ordinal);
        Assert.Contains("Provider query-artifact opt-in is", doc, StringComparison.Ordinal);
        Assert.Contains("--emit-query-artifacts", doc, StringComparison.Ordinal);
        Assert.Contains("SQLite virtual tables", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server local table synonyms", doc, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL materialized", doc, StringComparison.Ordinal);
        Assert.Contains("nullable", doc, StringComparison.Ordinal);
        Assert.Contains("nullable and non-null alternate-key FK relationships", doc, StringComparison.Ordinal);
        Assert.Contains("non-default FK delete/update referential actions", doc, StringComparison.Ordinal);
        Assert.Contains("RESTRICT and SET DEFAULT referential actions where providers expose them", doc, StringComparison.Ordinal);
        Assert.Contains("safe string/binary defaults, table CHECK constraints", doc, StringComparison.Ordinal);
        Assert.Contains("computed/generated columns", doc, StringComparison.Ordinal);
        Assert.Contains("provider-native table/column comments", doc, StringComparison.Ordinal);
        Assert.Contains("explicit SQL Server/PostgreSQL primary-key constraint names", doc, StringComparison.Ordinal);
        Assert.Contains("primary-key constraint-name", releaseGates, StringComparison.Ordinal);
        Assert.Contains("preservation while MySQL's fixed `PRIMARY` metadata", releaseGates, StringComparison.Ordinal);
        Assert.Contains("parentPkName", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Dotnet_norm_scaffold_builds_composite_primary_key_fk_model_shape_on_live_provider", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Routine <summary> & description", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("Sequence <summary> & description", liveScaffoldCliTests, StringComparison.Ordinal);
        Assert.Contains("SQL Server local-synonym comments", doc, StringComparison.Ordinal);
        Assert.Contains("view/materialized-view query-artifact comments", doc, StringComparison.Ordinal);
        Assert.Contains("generated XML documentation", doc, StringComparison.Ordinal);
        Assert.Contains("downgraded to provider-owned diagnostics", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server/PostgreSQL/MySQL routine comments", releaseGates, StringComparison.Ordinal);
        Assert.Contains("SQL Server/PostgreSQL sequence comments", releaseGates, StringComparison.Ordinal);
        Assert.Contains("Trigger-owned tables are", doc, StringComparison.Ordinal);
        Assert.Contains("trigger metadata across all four live providers", doc, StringComparison.Ordinal);
        Assert.Contains("Unsafe provider-specific columns are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("Safe provider-specific columns are also verified through the real CLI across", doc, StringComparison.Ordinal);
        Assert.Contains("SQLite UUID/JSON/XML declared types, SQL", doc, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL UUID/array columns, and MySQL JSON/YEAR/enum/set", doc, StringComparison.Ordinal);
        Assert.Contains("Writable provider-specific diagnostics are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server alias types, PostgreSQL domains over safe base types, and MySQL", doc, StringComparison.Ordinal);
        Assert.Contains("SCF104 remains in", doc, StringComparison.Ordinal);
        Assert.Contains("SCF104", doc, StringComparison.Ordinal);
        Assert.Contains("Decimal precision plus", doc, StringComparison.Ordinal);
        Assert.Contains("bounded string/binary length, Unicode, and fixed-length facets", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server, PostgreSQL, MySQL, and SQLite", doc, StringComparison.Ordinal);
        Assert.Contains("SQLite parses declared `DECIMAL(p,s)`", doc, StringComparison.Ordinal);
        Assert.Contains("SQLite participates by parsing declared `VARCHAR(n)`", doc, StringComparison.Ordinal);
        Assert.Contains("`CHAR(n)`, `BINARY(n)`, `VARBINARY(n)`, `DECIMAL(p,s)`, and", doc, StringComparison.Ordinal);
        Assert.Contains("`NUMERIC(p,s)` type text from `PRAGMA table_xinfo`", doc, StringComparison.Ordinal);
        Assert.Contains("Ordinary", doc, StringComparison.Ordinal);
        Assert.Contains("ordered unique composite indexes", doc, StringComparison.Ordinal);
        Assert.Contains("generated `[Index]` attributes", doc, StringComparison.Ordinal);
        Assert.Contains("Provider-bound filtered/partial predicates", doc, StringComparison.Ordinal);
        Assert.Contains("included-column index metadata", doc, StringComparison.Ordinal);
        Assert.Contains("real CLI where each provider exposes the feature", doc, StringComparison.Ordinal);
        Assert.Contains("Multiple composite FKs to", doc, StringComparison.Ordinal);
        Assert.Contains("role-named navigations", doc, StringComparison.Ordinal);
        Assert.Contains("payload-bridge diagnostics", doc, StringComparison.Ordinal);
        Assert.Contains("Direct composite alternate-key FKs are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("Multiple unique dependent", doc, StringComparison.Ordinal);
        Assert.Contains("role-named one-to-one relationships", doc, StringComparison.Ordinal);
        Assert.Contains("Single-column required and nullable", doc, StringComparison.Ordinal);
        Assert.Contains("combined real CLI scaffold", doc, StringComparison.Ordinal);
        Assert.Contains("Composite unique-dependent FKs", doc, StringComparison.Ordinal);
        Assert.Contains("required one-to-one relationships", doc, StringComparison.Ordinal);
        Assert.Contains("nullable composite unique-dependent FKs", doc, StringComparison.Ordinal);
        Assert.Contains("optional one-to-one relationships", doc, StringComparison.Ordinal);
        Assert.Contains("Shared primary-key FK shapes", doc, StringComparison.Ordinal);
        Assert.Contains("one-to-one relationships through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("Keyless dependent FK shapes", doc, StringComparison.Ordinal);
        Assert.Contains("navigation-free", doc, StringComparison.Ordinal);
        Assert.Contains("RelationshipDependentKey", doc, StringComparison.Ordinal);
        Assert.Contains("Self-referencing pure join tables are also verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("distinct role-based skip navigations", doc, StringComparison.Ordinal);
        Assert.Contains("Pure composite primary-key join tables are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("exact composite FK column arrays", doc, StringComparison.Ordinal);
        Assert.Contains("Shared-tenant alternate-key join tables are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("composite alternate-key principal selectors", doc, StringComparison.Ordinal);
        Assert.Contains("Generated-surrogate pure join", doc, StringComparison.Ordinal);
        Assert.Contains("exact unique FK-pair index", doc, StringComparison.Ordinal);
        Assert.Contains("Database-generated bridge columns", doc, StringComparison.Ordinal);
        Assert.Contains("do not incorrectly force payload join entities", doc, StringComparison.Ordinal);
        Assert.Contains("Composite generated-surrogate pure join", doc, StringComparison.Ordinal);
        Assert.Contains("exact composite FK-pair index", doc, StringComparison.Ordinal);
        Assert.Contains("Composite payload join tables are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("payload-column diagnostics without composite-FK rejection", doc, StringComparison.Ordinal);
        Assert.Contains("Filtered unique surrogate join tables are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("remain explicit entities instead of unsafe skip navigations", doc, StringComparison.Ordinal);
        Assert.Contains("Schema-qualified many-to-many join tables are verified through the real CLI", doc, StringComparison.Ordinal);
        Assert.Contains("schema-aware `UsingTable` mapping", doc, StringComparison.Ordinal);

        Assert.Contains("Scaffold_sqlite_output_builds_as_consumer_project", releaseGates, StringComparison.Ordinal);
        Assert.Contains("Scaffold_clean_run_removes_stale_warning_reports_without_printing_summary", releaseGates, StringComparison.Ordinal);
        Assert.Contains("LiveProviderScaffoldingParityTests", releaseGates, StringComparison.Ordinal);
        Assert.Contains("LiveProviderScaffoldCliParityTests", releaseGates, StringComparison.Ordinal);
        Assert.Contains("already-built `nORM.dll`", releaseGates, StringComparison.Ordinal);

        Assert.Contains("NormalizeScaffoldClrType", source, StringComparison.Ordinal);
        Assert.Contains("effectiveAllowNull", source, StringComparison.Ordinal);
        Assert.Contains("reference.IsRequired", source, StringComparison.Ordinal);
        Assert.Contains("IsRequired = isRequired", relationshipDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("isUniqueDependentKey", relationshipDiscoverySource, StringComparison.Ordinal);
        Assert.Contains(".HasOne(p => p.", contextWriterSource, StringComparison.Ordinal);
        Assert.Contains("isSelfRelationship", relationshipDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("isSelfJoin", manyToManyDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("LeftCollectionNavigationName", source, StringComparison.Ordinal);
        Assert.Contains("EnsureNoStaleScaffoldWarningReports", source, StringComparison.Ordinal);
        Assert.Contains("HasWriteBlockingProviderSpecificColumnTypes(providerSpecificColumnTypes)", source, StringComparison.Ordinal);
        Assert.Contains("IsSafeMySqlUnsignedDecimalType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("'bigint', 'decimal', 'numeric'", mySqlUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("IsSafeSqlServerAliasColumnType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("TryGetSqlServerAliasBaseTypeText", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("IsSafeSqlServerAliasBaseType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("c.max_length / 2", sqlServerUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("COALESCE(base_ty.name, ty.name) IN ('decimal', 'numeric')", sqlServerUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("COALESCE(base_ty.name, ty.name) IN ('decimal', 'numeric')", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("base_ty.name NOT IN", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsSafePostgresDomainColumnType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("TryNormalizePostgresParameterizedProbeCastType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("TryNormalizeSafePostgresDomainProbeCastType(detail, out var safeCastType)", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("TryParsePostgresDomainEnumValues", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("!typeText.StartsWith(\"ENUM\"", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("character_maximum_length::text", postgresUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("numeric_precision::text", postgresUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("c.domain_name IS NULL", postgresUnsupportedSource, StringComparison.Ordinal);
        Assert.DoesNotContain("c.domain_name IS NOT NULL", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("providerSpecificDefaultTableKeys.Contains(tableKey)", source, StringComparison.Ordinal);
        Assert.Contains("BuildProviderOwnedWriteBlockedTableKeys", featureMapBuilderSource, StringComparison.Ordinal);
        Assert.Contains("providerOwnedWriteBlockedTableKeys.Contains(canonicalJoinTableKey)", manyToManyDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("provider-owned-write-blocking-schema", joinDiagnosticBuilderSource, StringComparison.Ordinal);
        Assert.Contains("providerOwnedWriteBlockingSchema", joinDiagnosticBuilderSource, StringComparison.Ordinal);
        Assert.Contains("candidateQueryArtifacts", source, StringComparison.Ordinal);
        Assert.Contains("emittedQueryArtifacts", source, StringComparison.Ordinal);
        Assert.Contains("selectedTableKeys", source, StringComparison.Ordinal);
        Assert.Contains("provider-specific-default", unsupportedMetadataSource, StringComparison.Ordinal);
        Assert.Contains("QUOTE(column_default)", mySqlUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("providerSpecificIdentityStrategyTableKeys.Contains(tableKey)", source, StringComparison.Ordinal);
        Assert.Contains("provider-specific-identity-strategy", unsupportedMetadataSource, StringComparison.Ordinal);
        Assert.Contains("referential-action-not-scaffoldable", unsupportedMetadataSource, StringComparison.Ordinal);
        Assert.Contains("HasOnlyScaffoldableReferentialActions", joinDiagnosticBuilderSource, StringComparison.Ordinal);
        Assert.Contains("unmodeled complex/provider-specific defaults remain diagnostics", doc, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL `citext`/`json`/`jsonb`/`xml`/`uuid`", doc, StringComparison.Ordinal);
        Assert.Contains("provider-specific schema for provider-mobility review", doc, StringComparison.Ordinal);
        Assert.Contains("scaffoldable citext/JSON/XML/UUID scalar storage", diagnosticsWriterSource, StringComparison.Ordinal);
        Assert.Contains("CURRENT_TIMESTAMP()", doc, StringComparison.Ordinal);
        Assert.Contains("CURRENT_TIMESTAMP(6)", doc, StringComparison.Ordinal);
        Assert.Contains("Unsupported/provider-specific FK referential action discovered", doc, StringComparison.Ordinal);
        Assert.Contains("Valid `NO ACTION`, `CASCADE`, `SET NULL`, `RESTRICT`, and `SET DEFAULT` actions are emitted", doc, StringComparison.Ordinal);
        Assert.Contains("'draft'::text", doc, StringComparison.Ordinal);
        Assert.Contains("0xDEADBEEF", doc, StringComparison.Ordinal);
        Assert.Contains("X'DEADBEEF'", doc, StringComparison.Ordinal);
        Assert.Contains("now()::timestamp without time zone", doc, StringComparison.Ordinal);
        Assert.Contains("now() AT TIME ZONE 'utc'", doc, StringComparison.Ordinal);
        Assert.Contains("timezone('utc', now())", doc, StringComparison.Ordinal);
        Assert.Contains("Safe PostgreSQL cast suffixes", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("Hex/binary literals", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("0x[0-9a-f]+", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("x'(?:[0-9a-f]{2})*'", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("Strict PostgreSQL UTC timestamp defaults", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("at\\s+time\\s+zone\\s+'utc'", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("timezone\\s*\\(", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("character\\s+varying", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("timestamp\\s+(?:with|without)\\s+time\\s+zone", defaultValidator, StringComparison.Ordinal);
        Assert.Contains("unparsed strategies remain diagnostics and make the generated entity `[ReadOnlyEntity]`", doc, StringComparison.Ordinal);
        Assert.Contains("referential-action-not-scaffoldable", doc, StringComparison.Ordinal);
        Assert.Contains("provider-owned write-blocking schema", doc, StringComparison.Ordinal);
        Assert.Contains("only selected query artifacts count as emitted", doc, StringComparison.Ordinal);
        Assert.Contains("unselected SQLite virtual-table shadow storage is not reported", doc, StringComparison.Ordinal);
        Assert.Contains("NormalizeScaffoldClrType", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("effectiveAllowNull", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("existingPropertyNames.Add(EscapeCSharpIdentifier(ToPascalCase(tableName)))", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetScaffoldMaxLength(normalizedClrType, row)", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsUnboundedScaffoldMaxLength", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("ScaffoldDecimalPrecision", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetDecimalPrecisions", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("QueryDecimalPrecisionMap", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("TryParseDeclaredStringBinaryFacet", sqliteDdlParserSource, StringComparison.Ordinal);
        Assert.Contains("TryParseDeclaredDecimalPrecision", sqliteDdlParserSource, StringComparison.Ordinal);
        Assert.Contains("NormalizeDeclaredTypeBase", sqliteDdlParserSource, StringComparison.Ordinal);
        Assert.Contains("GetSqlServerStringBinaryFacetsAsync", columnDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("GetPostgresStringBinaryFacetsAsync", columnDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("GetMySqlStringBinaryFacetsAsync", columnDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("GetSqliteDeclaredStringBinaryFacetsAsync", columnDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("TryParseDeclaredStringBinaryFacet", columnDiscoverySource, StringComparison.Ordinal);
        Assert.Contains("TryParseDeclaredDecimalPrecision", sqliteUnsupportedSource, StringComparison.Ordinal);
        Assert.Contains("GetSqlServerStringBinaryFacets", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetPostgresStringBinaryFacets", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetMySqlStringBinaryFacets", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetSqliteDeclaredStringBinaryFacets", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetSqlServerDecimalPrecisions", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetPostgresDecimalPrecisions", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetMySqlDecimalPrecisions", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetSqliteDeclaredDecimalPrecisions", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("nameof(ColumnAttribute.TypeName)", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("column.DecimalPrecision", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("RequiredAttribute", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("BuildSchemaDescriptor", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetSqliteDeclaredColumnTypes", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("GetPostgresDomainColumnCastTypes", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsSafePostgresUserDefinedScalarColumnType", providerTypeClassifierSource, StringComparison.Ordinal);
        Assert.Contains("data_type = 'ARRAY'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("AND COALESCE(udt_name, '') IN (", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("'_timestamptz'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("AND COALESCE(c.udt_name, '') NOT IN ('citext', 'json', 'jsonb', 'xml', 'uuid')", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("NormalizeMySqlUnsignedTypeDetail", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsReadOnlyDynamicObject", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsDynamicQueryObject", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsProviderOwnedSynonym", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("sys.synonyms", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsProviderNativeTemporalTable", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("HasProviderOwnedTriggers", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("HasUnmodeledDefaults", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("TryNormalizeDynamicDefaultSql", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("ScaffoldSqlMetadataParser.TryNormalizeScaffoldDefaultSql(raw, out defaultValueSql)", dynamicSource, StringComparison.Ordinal);
        Assert.DoesNotContain("DefaultValueValidator.Validate(candidate)", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("AND is_identity <> 'YES'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("QUOTE(column_default)", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("HasWriteBlockingProviderSpecificColumns", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("ty.name IN ('geography', 'geometry', 'hierarchyid', 'sql_variant')", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("c.udt_name IN ('inet', 'cidr', 'macaddr', 'macaddr8', 'tsvector', 'tsquery')", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("'geometrycollection'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("'multipolygon'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("HasWriteBlockingMySqlSetColumns", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("TryParseBoundedMySqlSetValues", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("data_type = 'set'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("c.data_type = 'ARRAY'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("COALESCE(c.udt_name, '') NOT IN", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("'_int4'", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsUnsafeSqliteProviderSpecificDeclaredType", source, StringComparison.Ordinal);
        Assert.Contains("IsUnsafeSqliteProviderSpecificDeclaredType", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("ContainsSqliteDeclaredTypeToken", source, StringComparison.Ordinal);
        Assert.Contains("ContainsSqliteDeclaredTypeToken", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("!DynamicEntityReadOnlyClassifier.IsUnsafeSqliteProviderSpecificDeclaredType(normalized)", source, StringComparison.Ordinal);
        Assert.Contains("!IsUnsafeSqliteProviderSpecificDeclaredType(normalized)", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("IsWriteBlockingSqliteDeclaredType", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("RO", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("SQLite `UUID` declared-type parity", doc, StringComparison.Ordinal);
        Assert.Contains("keyless dynamic", doc, StringComparison.Ordinal);
        Assert.Contains("provider-owned dynamic read-only parity", doc, StringComparison.Ordinal);
        Assert.Contains("SQL Server synonyms", doc, StringComparison.Ordinal);
        Assert.Contains("unmodeled defaults", doc, StringComparison.Ordinal);
        Assert.Contains("MySQL `information_schema`", doc, StringComparison.Ordinal);
        Assert.Contains("provider-owned triggers", doc, StringComparison.Ordinal);
        Assert.Contains("write-blocking", doc, StringComparison.Ordinal);
        Assert.Contains("unsafe PostgreSQL provider-specific array columns", doc, StringComparison.Ordinal);
        Assert.Contains("SQLite declared", doc, StringComparison.Ordinal);
        Assert.Contains("spatial provider-specific column diagnostics", doc, StringComparison.Ordinal);
        Assert.Contains("unsafe MySQL", doc, StringComparison.Ordinal);
        Assert.Contains("`set(...)` declarations", doc, StringComparison.Ordinal);
        Assert.Contains("provider-specific column types", doc, StringComparison.Ordinal);
        Assert.Contains("avoid the enclosing entity type name", doc, StringComparison.Ordinal);
        Assert.Contains("composite primary-key ordinal parity", doc, StringComparison.Ordinal);
        Assert.Contains("normalized dynamic `MaxLength` metadata", doc, StringComparison.Ordinal);
        Assert.Contains("dynamic decimal precision/scale", doc, StringComparison.Ordinal);
        Assert.Contains("Static and runtime dynamic scaffolding emit", doc, StringComparison.Ordinal);
        Assert.Contains("PostgreSQL array/domain-column schema probes", doc, StringComparison.Ordinal);
        Assert.Contains("safe-domain diagnostics do not make the generated entity `[ReadOnlyEntity]`", doc, StringComparison.Ordinal);
        Assert.Contains("GetPrimaryKeyOrdinals", dynamicSource, StringComparison.Ordinal);
        Assert.Contains("ReadOnlyEntityAttribute", dynamicSource, StringComparison.Ordinal);
    }

}
