using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using nORM.Configuration;
using nORM.Providers;
using nORM.Internal;

#nullable enable

namespace nORM.Mapping
{
    /// <summary>
    /// Describes the mapping between an entity property and a database column including
    /// metadata used for query generation and materialization.
    /// </summary>
    public sealed class Column
    {
        /// <summary>Reflection information for the property represented by this column.</summary>
        public PropertyInfo Prop { get; }
        /// <summary>Name of the property on the CLR type.</summary>
        public string PropName { get; }
        /// <summary>Plain (unescaped) column name.</summary>
        public string Name { get; }
        /// <summary>Escaped column name suitable for inclusion in SQL statements.</summary>
        public string EscCol { get; }
        /// <summary>Indicates whether the column is part of the primary key.</summary>
        public bool IsKey { get; private set; }
        /// <summary>Indicates whether the column value is generated by the database.</summary>
        public bool IsDbGenerated { get; }
        /// <summary>
        /// True when value generation was set explicitly — a <see cref="DatabaseGeneratedAttribute"/> (any
        /// option, including None) or a fluent <c>ValueGeneratedOnAdd/Never</c>. The store-generated-key
        /// convention only applies when this is false, so an explicit opt-out is respected.
        /// </summary>
        internal bool ValueGenerationExplicitlyConfigured { get; }
        /// <summary>Indicates whether the column stores a concurrency token.</summary>
        public bool IsTimestamp { get; }
        /// <summary>Indicates whether this column represents a shadow property not defined on the entity type.</summary>
        public bool IsShadow { get; }
        /// <summary>Indicates whether the mapped value can be null according to CLR metadata.</summary>
        public bool IsNullable { get; }
        /// <summary>Name of the principal type if this column is a foreign key, otherwise <c>null</c>.</summary>
        public string? ForeignKeyPrincipalTypeName { get; private set; }

        /// <summary>
        /// Promotes this column to the primary key under the EF-parity naming convention
        /// ("Id" / "&lt;Type&gt;Id" when no explicit key is configured). Clears the
        /// foreign-key inference the constructor may have applied to a "&lt;Type&gt;Id"
        /// property - a key is not a self-referencing foreign key.
        /// </summary>
        internal void MarkAsConventionKey()
        {
            IsKey = true;
            ForeignKeyPrincipalTypeName = null;
        }
        /// <summary>Delegate used to read the property value from an entity instance.</summary>
        public Func<object, object?> Getter { get; }
        /// <summary>Delegate used to assign a value to the property on an entity instance.</summary>
        public Action<object, object?> Setter { get; }
        /// <summary>The underlying setter method for the property.</summary>
        public MethodInfo SetterMethod { get; }
        /// <summary>Optional converter between model value and provider (database) value.</summary>
        public IValueConverter? Converter { get; set; }

        /// <summary>
        /// Initializes a new mapping using cached property metadata produced by the mapping cache.
        /// </summary>
        /// <param name="info">Precomputed property metadata.</param>
        /// <param name="p">Database provider used for escaping identifiers.</param>
        /// <param name="fluentConfig">Optional fluent configuration supplying overrides.</param>
        /// <param name="prefix">Optional prefix appended to the property name for column naming.</param>
        /// <param name="getterOverride">Custom getter delegate.</param>
        /// <param name="setterOverride">Custom setter delegate.</param>
        /// <param name="setterMethodOverride">Custom setter method.</param>
        internal Column(ColumnMappingCache.CachedPropertyInfo info, DatabaseProvider p, IEntityTypeConfiguration? fluentConfig, string? prefix = null,
            Func<object, object?>? getterOverride = null, Action<object, object?>? setterOverride = null,
            MethodInfo? setterMethodOverride = null)
        {
            Prop = info.Property;
            PropName = (prefix != null ? prefix + "_" : "") + info.Property.Name;

            var fluentColName = fluentConfig?.ColumnNames.TryGetValue(info.Property, out var name) == true ? name : null;
            var colName = fluentColName ?? info.ColumnName ?? PropName;
            Name = colName;
            EscCol = IdentifierEscaping.EscapeSingle(p, colName);

            IsKey = (fluentConfig?.KeyProperties.Any(p => p == info.Property) ?? false) || info.IsKey;
            IsTimestamp = info.IsTimestamp || (fluentConfig?.RowVersionSettings.Contains(info.Property) ?? false);
            IsDbGenerated = ResolveIsDbGenerated(fluentConfig, info.Property, info.IsDbGenerated);
            ValueGenerationExplicitlyConfigured = info.Property.GetCustomAttribute<DatabaseGeneratedAttribute>() != null
                || (fluentConfig?.ValueGeneratedSettings.ContainsKey(info.Property) ?? false);
            IsNullable = prefix != null || DetermineIsNullable(info.Property);
            ForeignKeyPrincipalTypeName = info.ForeignKeyName;
            if (ForeignKeyPrincipalTypeName == null && !IsKey)
            {
                var propName = info.Property.Name;
                if (propName.EndsWith("Id", StringComparison.OrdinalIgnoreCase) && propName.Length > 2)
                {
                    var principalName = propName[..^2];
                    if (!string.Equals(principalName, "Id", StringComparison.OrdinalIgnoreCase))
                        ForeignKeyPrincipalTypeName = principalName;
                }
                else
                {
                    var underscore = propName.IndexOf('_');
                    if (underscore > 0)
                        ForeignKeyPrincipalTypeName = propName.Substring(0, underscore);
                }
            }

            Getter = getterOverride ?? info.Getter;
            Setter = setterOverride ?? info.Setter;
            SetterMethod = setterMethodOverride ?? info.Property.GetSetMethod()
                ?? throw new InvalidOperationException(
                    $"Property '{info.Property.DeclaringType?.Name}.{info.Property.Name}' has no public setter " +
                    "and cannot be used as a mapped column. Remove it from the mapping or make it read-write.");
            IsShadow = false;
        }

        /// <summary>
        /// Initializes a new mapping for a regular property.
        /// </summary>
        /// <param name="pi">Property information.</param>
        /// <param name="p">Database provider used for escaping identifiers.</param>
        /// <param name="fluentConfig">Optional fluent configuration supplying overrides.</param>
        /// <param name="prefix">Optional prefix appended to the property name for column naming.</param>
        /// <param name="getterOverride">Custom getter delegate.</param>
        /// <param name="setterOverride">Custom setter delegate.</param>
        /// <param name="setterMethodOverride">Custom setter method.</param>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Column construction compiles property accessor delegates (Expression.Compile) when no overrides are supplied; runs via the interpreter under NativeAOT.")]
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Column construction reflects over the mapped property; trimming may remove the required members.")]
        public Column(PropertyInfo pi, DatabaseProvider p, IEntityTypeConfiguration? fluentConfig, string? prefix = null,
            Func<object, object?>? getterOverride = null, Action<object, object?>? setterOverride = null,
            MethodInfo? setterMethodOverride = null)
        {
            Prop = pi;
            PropName = (prefix != null ? prefix + "_" : "") + pi.Name;

            var fluentColName = fluentConfig?.ColumnNames.TryGetValue(pi, out var name) == true ? name : null;
            var colName = fluentColName ?? pi.GetCustomAttribute<ColumnAttribute>()?.Name ?? PropName;
            Name = colName;
            EscCol = IdentifierEscaping.EscapeSingle(p, colName);

            IsKey = (fluentConfig?.KeyProperties.Any(p => p == pi) ?? false) || pi.GetCustomAttribute<KeyAttribute>() != null;
            IsTimestamp = pi.GetCustomAttribute<TimestampAttribute>() != null || (fluentConfig?.RowVersionSettings.Contains(pi) ?? false);
            IsDbGenerated = ResolveIsDbGenerated(fluentConfig, pi,
                pi.GetCustomAttribute<DatabaseGeneratedAttribute>()?.DatabaseGeneratedOption is DatabaseGeneratedOption.Identity or DatabaseGeneratedOption.Computed);
            ValueGenerationExplicitlyConfigured = pi.GetCustomAttribute<DatabaseGeneratedAttribute>() != null
                || (fluentConfig?.ValueGeneratedSettings.ContainsKey(pi) ?? false);
            IsNullable = prefix != null || DetermineIsNullable(pi);
            ForeignKeyPrincipalTypeName = pi.GetCustomAttribute<ForeignKeyAttribute>()?.Name;
            if (ForeignKeyPrincipalTypeName == null && !IsKey)
            {
                var propName = pi.Name;
                if (propName.EndsWith("Id", StringComparison.OrdinalIgnoreCase) && propName.Length > 2)
                {
                    var principalName = propName[..^2];
                    if (!string.Equals(principalName, "Id", StringComparison.OrdinalIgnoreCase))
                        ForeignKeyPrincipalTypeName = principalName;
                }
                else
                {
                    var underscore = propName.IndexOf('_');
                    if (underscore > 0)
                        ForeignKeyPrincipalTypeName = propName.Substring(0, underscore);
                }
            }

            Getter = getterOverride ?? CreateGetterDelegate(pi);
            Setter = setterOverride ?? CreateSetterDelegate(pi);
            SetterMethod = setterMethodOverride ?? pi.GetSetMethod()
                ?? throw new InvalidOperationException(
                    $"Property '{pi.DeclaringType?.Name}.{pi.Name}' has no public setter " +
                    "and cannot be used as a mapped column. Remove it from the mapping or make it read-write.");
            IsShadow = false;
        }

        /// <summary>
        /// Initializes a new mapping for a shadow property not present on the CLR type.
        /// </summary>
        /// <param name="name">Name of the shadow property.</param>
        /// <param name="clrType">CLR type of the property.</param>
        /// <param name="declaringType">Declaring entity type.</param>
        /// <param name="p">Database provider used for escaping identifiers.</param>
        /// <param name="columnName">Optional column name override.</param>
        public Column(string name, Type clrType, Type declaringType, DatabaseProvider p, string? columnName = null)
        {
            Prop = new ShadowPropertyInfo(name, clrType, declaringType);
            PropName = name;
            var colName = columnName ?? name;
            Name = colName;
            EscCol = IdentifierEscaping.EscapeSingle(p, colName);
            IsKey = false;
            IsTimestamp = false;
            IsDbGenerated = false;
            ValueGenerationExplicitlyConfigured = true; // shadow columns never take the store-generated-key convention
            IsNullable = !clrType.IsValueType || Nullable.GetUnderlyingType(clrType) != null;
            ForeignKeyPrincipalTypeName = null;
            var propName = name;
            if (propName.EndsWith("Id", StringComparison.OrdinalIgnoreCase) && propName.Length > 2)
            {
                var principalName = propName[..^2];
                if (!string.Equals(principalName, "Id", StringComparison.OrdinalIgnoreCase))
                    ForeignKeyPrincipalTypeName = principalName;
            }
            else
            {
                var underscore = propName.IndexOf('_');
                if (underscore > 0)
                    ForeignKeyPrincipalTypeName = propName.Substring(0, underscore);
            }
            Getter = e => ShadowPropertyStore.Get(e, name);
            Setter = (e, v) => ShadowPropertyStore.Set(e, name, v);
            SetterMethod = Methods.SetShadowValue;
            IsShadow = true;
        }

        private static readonly NullabilityInfoContext? s_nullabilityContext = CreateNullabilityContext();
        private static readonly object s_nullabilityContextLock = new();

        private static NullabilityInfoContext? CreateNullabilityContext()
        {
            try { return new NullabilityInfoContext(); }
            catch (Exception ex) when (ex is NotSupportedException or TypeLoadException)
            {
                return null;
            }
        }

        // Fluent Property(x => x.Col).ValueGeneratedOnAdd()/Never()/OnAddOrUpdate() overrides the
        // attribute-derived database-generated flag: Identity/Computed mark the column store-generated (so it
        // is omitted from INSERT/UPDATE), None clears it.
        private static bool ResolveIsDbGenerated(IEntityTypeConfiguration? config, PropertyInfo prop, bool attributeDefault)
        {
            if (config != null && config.ValueGeneratedSettings.TryGetValue(prop, out var option))
                return option is DatabaseGeneratedOption.Identity or DatabaseGeneratedOption.Computed;
            return attributeDefault;
        }

        /// <summary>
        /// CLR types the store-generated-key convention applies to: the integer widths. Guid is excluded — EF
        /// generates Guid keys client-side, whereas nORM's store-generated path can't, so a Guid key stays
        /// client-set until nORM grows client-side key generation. Nullable is unwrapped.
        /// </summary>
        internal static bool IsConventionStoreGeneratedKeyType(Type t)
        {
            var u = Nullable.GetUnderlyingType(t) ?? t;
            return u == typeof(int) || u == typeof(long) || u == typeof(short) || u == typeof(byte)
                || u == typeof(uint) || u == typeof(ulong) || u == typeof(ushort) || u == typeof(sbyte);
        }

        private static bool DetermineIsNullable(PropertyInfo property)
        {
            var propertyType = property.PropertyType;
            if (Nullable.GetUnderlyingType(propertyType) != null)
                return true;
            if (propertyType.IsValueType)
                return false;
            if (property.GetCustomAttribute<RequiredAttribute>() != null ||
                property.GetCustomAttribute<DisallowNullAttribute>() != null)
                return false;
            if (property.GetCustomAttribute<AllowNullAttribute>() != null ||
                property.GetCustomAttribute<MaybeNullAttribute>() != null)
                return true;

            try
            {
                NullabilityState? state;
                lock (s_nullabilityContextLock)
                {
                    state = s_nullabilityContext?.Create(property).WriteState;
                }
                if (state == NullabilityState.NotNull)
                    return false;
                if (state == NullabilityState.Nullable)
                    return true;
            }
            catch (Exception ex) when (ex is ArgumentException or InvalidOperationException or NotSupportedException)
            {
                // Dynamic/emitted properties can lack complete nullable metadata.
            }

            return true;
        }

        /// <summary>
        /// Creates a compiled delegate that efficiently retrieves the value of the specified property
        /// on a given object instance, boxing value types as necessary.
        /// </summary>
        /// <param name="property">The property for which to generate a getter.</param>
        /// <returns>A delegate that returns the property's value for a supplied object.</returns>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("CreateGetterDelegate compiles an expression tree (Expression.Compile); runs via the interpreter under NativeAOT.")]
        public static Func<object, object?> CreateGetterDelegate(PropertyInfo property)
        {
            // Prefer a source-generated getter when one exists (trim/NativeAOT-safe, no runtime codegen).
            if (property.DeclaringType is Type declaringType &&
                nORM.SourceGeneration.GeneratedAccessors.TryGetGetter(declaringType, property.Name, out var generatedGetter))
                return generatedGetter;

            // Expression.Compile (not DynamicMethod/Reflection.Emit): under NativeAOT Reflection.Emit throws
            // PlatformNotSupportedException, whereas Expression.Compile transparently interprets. Reached via
            // new Column(PropertyInfo) — e.g. member-init DTO projections — which must run under trimming.
            // A member-init projection target's getter is never invoked, and the trimmer removes it (only the
            // setter is referenced), so a missing getter yields a fail-if-invoked delegate instead of throwing
            // "Expression must be readable" while building the tree.
            if (property.GetGetMethod(nonPublic: true) is null)
            {
                var member = $"{property.DeclaringType?.Name}.{property.Name}";
                return _ => throw new InvalidOperationException($"Property '{member}' has no readable getter.");
            }
            var instanceParam = Expression.Parameter(typeof(object), "instance");
            var castInstance = Expression.Convert(instanceParam, property.DeclaringType!);
            var getProperty = Expression.Property(castInstance, property);
            var convertResult = Expression.Convert(getProperty, typeof(object));
            return Expression.Lambda<Func<object, object?>>(convertResult, instanceParam).Compile();
        }

        /// <summary>
        /// Creates a compiled delegate capable of setting the value of the specified property on a
        /// target object instance. The delegate performs the necessary boxing or casting so that
        /// repeated property assignments can be performed without the overhead of reflection.
        /// </summary>
        /// <param name="property">The property for which a setter delegate should be created.</param>
        /// <returns>
        /// An <see cref="Action{T1,T2}"/> that assigns a value to the provided object's property.
        /// </returns>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("CreateSetterDelegate compiles an expression tree (Expression.Compile); runs via the interpreter under NativeAOT.")]
        private static Action<object, object?> CreateSetterDelegate(PropertyInfo property)
        {
            // Prefer a source-generated setter when one exists (trim/NativeAOT-safe, no runtime codegen).
            if (property.DeclaringType is Type declaringType &&
                nORM.SourceGeneration.GeneratedAccessors.TryGetSetter(declaringType, property.Name, out var generatedSetter))
                return generatedSetter;

            // Expression.Compile (not DynamicMethod/Reflection.Emit): AOT-safe (interprets) where Reflection.Emit throws.
            var setMethod = property.GetSetMethod(nonPublic: true);
            if (setMethod is null)
            {
                var member = $"{property.DeclaringType?.Name}.{property.Name}";
                return (_, __) => throw new InvalidOperationException($"Property '{member}' has no accessible setter.");
            }
            var instanceParam = Expression.Parameter(typeof(object), "instance");
            var valueParam = Expression.Parameter(typeof(object), "value");
            var castInstance = Expression.Convert(instanceParam, property.DeclaringType!);
            var castValue = Expression.Convert(valueParam, property.PropertyType);
            var setProperty = Expression.Call(castInstance, setMethod, castValue);
            return Expression.Lambda<Action<object, object?>>(setProperty, instanceParam, valueParam).Compile();
        }
    }
}
