using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Text;
using nORM.Query;
using System.Threading;
using System.Threading.Tasks;
using nORM.Core;
using nORM.Internal;
using nORM.Mapping;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.ObjectPool;
using nORM.Configuration;

#nullable enable

namespace nORM.Providers
{
    public abstract partial class DatabaseProvider
    {
        #region SQL Generation
        /// <summary>
        /// Returns the columns that should appear in an INSERT statement for the given mapping.
        /// Override in provider subclasses to exclude server-managed columns (e.g. SQL Server ROWVERSION)
        /// that cannot receive explicit values on INSERT.
        /// </summary>
        public virtual Column[] GetInsertColumns(TableMapping m) => m.InsertColumns;

        /// <summary>
        /// True when a single-column integer primary key that takes the store-generated-key convention
        /// (<see cref="Column.IsConventionGeneratedKey"/>, EF Core parity) is generated by the database when
        /// its value is default (0) yet honors an explicitly-supplied non-default value. SQLite supports this
        /// with no special DDL because a single-column INTEGER primary key is an alias for the rowid (it
        /// auto-generates when the column is omitted and honors an explicit value). Other providers require an
        /// identity/sequence column plus IDENTITY_INSERT-style handling for the explicit-value rows and are
        /// enabled as their write paths gain that support. When false, a convention key is never marked (the
        /// gate is applied once at mapping-build time), so the write path and change tracker behave exactly as
        /// before on that provider.
        /// </summary>
        public virtual bool SupportsConventionKeyStoreGeneration => false;

        /// <summary>
        /// When <see cref="SupportsConventionKeyStoreGeneration"/> is true, indicates HOW the convention key
        /// store-generates: <c>false</c> means it is a free rowid alias needing no special DDL (SQLite);
        /// <c>true</c> means it must be emitted as an identity/auto-increment column (SqlServer IDENTITY,
        /// PostgreSQL GENERATED BY DEFAULT AS IDENTITY, MySQL AUTO_INCREMENT). Drives whether the schema
        /// snapshot marks a convention key as identity for DDL generation. Inert unless the convention is
        /// supported on the provider.
        /// </summary>
        internal virtual bool ConventionKeyUsesIdentityColumn => false;

        /// <summary>
        /// Statement emitted BEFORE the batch/command that inserts EXPLICIT values into a store-generated
        /// convention key's identity column, so the explicit values are accepted (SQL Server
        /// <c>SET IDENTITY_INSERT t ON;</c>). Empty on providers whose identity honors an explicit value
        /// natively (MySQL AUTO_INCREMENT, PostgreSQL GENERATED BY DEFAULT). Paired with
        /// <see cref="GetIdentityInsertDisableSql"/>; both run on the same connection as the INSERT.
        /// </summary>
        internal virtual string GetIdentityInsertEnableSql(TableMapping m) => string.Empty;

        /// <summary>Restores the default after <see cref="GetIdentityInsertEnableSql"/> (SQL Server <c>SET IDENTITY_INSERT t OFF;</c>). Empty by default.</summary>
        internal virtual string GetIdentityInsertDisableSql(TableMapping m) => string.Empty;

        /// <summary>
        /// Clause emitted between SET and WHERE of an UPDATE to read back a
        /// server-generated concurrency token (SQL Server ROWVERSION), so the
        /// tracked instance can save again without a false stale-token conflict.
        /// Empty on providers whose tokens are client-managed.
        /// </summary>
        internal virtual string GetUpdateTokenOutputClause(TableMapping m) => string.Empty;

        /// <summary>
        /// Clause emitted between the column list and VALUES of an INSERT to read
        /// back a server-generated concurrency token (SQL Server ROWVERSION) for
        /// entities whose keys the application supplies. The server generates a
        /// fresh token on INSERT, so without this read-back the tracked instance's
        /// first UPDATE or DELETE compares a stale in-memory token and throws a
        /// false concurrency conflict. Entities with DB-generated keys read the
        /// token back through the identity-retrieval clause instead. Empty on
        /// providers whose tokens are client-managed.
        /// </summary>
        internal virtual string GetInsertTokenOutputClause(TableMapping m) => string.Empty;

        /// <summary>
        /// Builds a parameterized <c>INSERT</c> statement for the specified table
        /// mapping, caching the generated SQL for future use.
        /// </summary>
        /// <param name="m">The table mapping describing the entity.</param>
        /// <param name="hydrateGeneratedKeys">
        /// When <c>true</c>, append provider-specific identity retrieval so callers can hydrate generated keys.
        /// </param>
        /// <returns>An <c>INSERT</c> statement ready for parameter substitution.</returns>
        public string BuildInsert(TableMapping m, bool hydrateGeneratedKeys = true)
        {
            var includeIdentityRetrieval = hydrateGeneratedKeys && m.KeyColumns.Any(k => k.IsDbGenerated);
            var cacheKey = includeIdentityRetrieval ? "INSERT" : "INSERT_PLAIN";
            return _sqlCache.GetOrAdd((m.Type, m.TableName, cacheKey, m.SqlShapeKey), _ => {
                var cols = GetInsertColumns(m);
                var identityPrefix = includeIdentityRetrieval ? GetIdentityRetrievalPrefix(m) : string.Empty;
                var identitySuffix = includeIdentityRetrieval ? GetIdentityRetrievalString(m) : string.Empty;
                // Server-generated tokens (ROWVERSION) are assigned on INSERT too; when no
                // identity retrieval reads them back, the token output clause does. The two
                // are mutually exclusive: identity retrieval already includes the token.
                var tokenPrefix = !includeIdentityRetrieval && m.TimestampColumn != null && SupportsNativeRowVersion
                    ? GetInsertTokenOutputClause(m)
                    : string.Empty;
                if (cols.Length == 0)
                {
                    return $"INSERT INTO {m.EscTable}{identityPrefix}{tokenPrefix} {DefaultValuesInsertClause}{identitySuffix}";
                }
                var colNames = string.Join(", ", cols.Select(c => c.EscCol));
                var valParams = string.Join(", ", cols.Select(c => ParamPrefix + c.PropName));
                return $"INSERT INTO {m.EscTable} ({colNames}){identityPrefix}{tokenPrefix} VALUES ({valParams}){identitySuffix}";
            });
        }

        /// <summary>
        /// Builds a parameterized <c>UPDATE</c> statement that updates all non-key
        /// columns and filters by the entity's primary key (and timestamp when present).
        /// </summary>
        /// <param name="m">The table mapping describing the entity.</param>
        /// <param name="includeTenant">When <c>true</c>, appends an AND predicate for the tenant
        /// column so the statement can only modify the current tenant's rows.</param>
        /// <returns>An <c>UPDATE</c> SQL statement.</returns>
        public string BuildUpdate(TableMapping m, bool includeTenant = false)
        {
            if (m.UpdateColumns.Length == 0)
                throw new NormConfigurationException(
                    $"Entity '{m.Type.Name}' has no mutable columns to update. Add at least one non-key, non-timestamp property.");

            // X1: cache key distinguishes tenant vs non-tenant SQL so both shapes can coexist.
            var cacheOp = includeTenant ? "UPDATE_TENANT" : "UPDATE";
            return _sqlCache.GetOrAdd((m.Type, m.TableName, cacheOp, m.SqlShapeKey), _ =>
            {
                var setCols = m.UpdateColumns
                    .Select(c => $"{c.EscCol}={ParamPrefix}{c.PropName}").ToList();
                // Client-managed concurrency token: write a fresh value in SET (@Token) so a stale
                // concurrent UPDATE affects zero rows. Providers without a native rowversion only.
                if (m.ClientManagedConcurrencyToken)
                    setCols.Add($"{m.TimestampColumn!.EscCol}={ParamPrefix}{m.TimestampColumn.PropName}");
                var set = string.Join(", ", setCols);

                var whereCols = m.KeyColumns
                    .Select(c => $"{c.EscCol}={ParamPrefix}{c.PropName}").ToList();
                if (m.TimestampColumn != null)
                {
                    var tc = m.TimestampColumn;
                    // When the token is also in SET (@Token), the WHERE compares the OLD value under a
                    // distinct name (@Token_orig) so the two bindings don't collide.
                    var whereParam = m.ClientManagedConcurrencyToken ? $"{tc.PropName}_orig" : tc.PropName;
                    whereCols.Add($"({tc.EscCol}={ParamPrefix}{whereParam} OR ({tc.EscCol} IS NULL AND {ParamPrefix}{whereParam} IS NULL))");
                }
                // X1: include tenant column in WHERE so direct UpdateAsync cannot cross-write rows
                // belonging to other tenants - parity with the batched SaveChangesAsync path.
                if (includeTenant && m.TenantColumn != null)
                    whereCols.Add($"{m.TenantColumn.EscCol}={ParamPrefix}{m.TenantColumn.PropName}");
                var where = string.Join(" AND ", whereCols);

                // Server-generated tokens (ROWVERSION) regenerate on every UPDATE; read the
                // fresh value back inline so the entity can update or delete again without a
                // false stale-token conflict (mirrors the batched BuildUpdateBatch path).
                var tokenOutput = m.TimestampColumn != null && SupportsNativeRowVersion
                    ? GetUpdateTokenOutputClause(m)
                    : string.Empty;
                return $"UPDATE {m.EscTable} SET {set}{tokenOutput} WHERE {where}";
            });
        }

        /// <summary>
        /// Builds a parameterized <c>DELETE</c> statement that filters by the primary
        /// key (and timestamp when applicable) to ensure a single row is targeted.
        /// </summary>
        /// <param name="m">The table mapping describing the entity.</param>
        /// <param name="includeTenant">When <c>true</c>, appends an AND predicate for the tenant
        /// column so the statement can only delete the current tenant's rows.</param>
        /// <returns>A <c>DELETE</c> SQL statement.</returns>
        public string BuildDelete(TableMapping m, bool includeTenant = false)
        {
            // X1: cache key distinguishes tenant vs non-tenant SQL so both shapes can coexist.
            var cacheOp = includeTenant ? "DELETE_TENANT" : "DELETE";
            return _sqlCache.GetOrAdd((m.Type, m.TableName, cacheOp, m.SqlShapeKey), _ =>
            {
                var whereCols = m.KeyColumns
                    .Select(c => $"{c.EscCol}={ParamPrefix}{c.PropName}").ToList();
                if (m.TimestampColumn != null)
                {
                    var tc = m.TimestampColumn;
                    whereCols.Add($"({tc.EscCol}={ParamPrefix}{tc.PropName} OR ({tc.EscCol} IS NULL AND {ParamPrefix}{tc.PropName} IS NULL))");
                }
                // X1: include tenant column in WHERE so direct DeleteAsync cannot cross-delete rows
                // belonging to other tenants - parity with the batched SaveChangesAsync path.
                if (includeTenant && m.TenantColumn != null)
                    whereCols.Add($"{m.TenantColumn.EscCol}={ParamPrefix}{m.TenantColumn.PropName}");
                var where = string.Join(" AND ", whereCols);

                return $"DELETE FROM {m.EscTable} WHERE {where}";
            });
        }
        #endregion
    }
}
