using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.ObjectPool;
using nORM.Core;
using nORM.Internal;
using nORM.Mapping;
using nORM.Query;

#nullable enable

namespace nORM.Providers
{
    /// <summary>
    /// Database provider implementation optimized for PostgreSQL.
    /// Handles SQL dialect translation, bulk operations and temporal table support.
    /// </summary>
    public sealed partial class PostgresProvider : BulkOperationProvider
    {
        internal override bool SupportsFastPathPreparedCommandCache => true;
        internal override bool SupportsQueryPlanPreparedCommandCache => true;
        internal override bool PrefersSyncFastPathExecution => true;

        /// <summary>
        /// A single-column integer primary key with no explicit value-generation config is store-generated
        /// (EF Core parity): PostgreSQL realizes it as a <c>GENERATED BY DEFAULT AS IDENTITY</c> column, which
        /// generates a value when the column is omitted and honors an explicitly-supplied value. See <see cref="TableMapping.ConventionGeneratedKeyColumn"/>.
        /// </summary>
        public override bool SupportsConventionKeyStoreGeneration => true;

        /// <summary>PostgreSQL realizes the convention key as a GENERATED BY DEFAULT AS IDENTITY column (needs identity DDL).</summary>
        internal override bool ConventionKeyUsesIdentityColumn => true;

        internal override bool PrefersSyncCompiledQueryExecution => true;

        internal override bool PrefersSyncQueryPlanExecution => true;

        /// <summary>
        /// Minimum PostgreSQL version supported by nORM v1. PostgreSQL 12 is the lowest version
        /// where all advertised features work without fallbacks: generated identity columns
        /// (added in 10), JSON path operators (added in 12), and modern partition routing.
        /// This floor matches docs/provider-capabilities.md and is enforced by
        /// ProviderCapabilityContractTests so docs and runtime cannot drift apart.
        /// </summary>
        private static readonly Version MinimumPostgresVersion = new(12, 0);

        /// <summary>
        /// PostgreSQL error code for "undefined_table" (error class 42P01).
        /// </summary>
        private const string PgErrorUndefinedTable = "42P01";

        /// <summary>Factory used to create Npgsql-compatible <see cref="DbParameter"/> instances.</summary>
        private readonly IDbParameterFactory _parameterFactory;

        /// <summary>Shared pool of <see cref="StringBuilder"/> instances to reduce allocations during SQL generation.</summary>
        private static readonly ObjectPool<StringBuilder> _stringBuilderPool =
            new DefaultObjectPool<StringBuilder>(new StringBuilderPooledObjectPolicy());

        /// <summary>
        /// Initializes a new instance of the <see cref="PostgresProvider"/> class.
        /// </summary>
        /// <remarks>
        /// Uses a reflection-based Npgsql parameter factory. Consumer applications must
        /// reference the <c>Npgsql</c> package when executing PostgreSQL commands.
        /// </remarks>
        public PostgresProvider()
            : this(new ReflectionNpgsqlParameterFactory())
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostgresProvider"/> class.
        /// </summary>
        /// <param name="parameterFactory">Factory responsible for creating PostgreSQL parameters.</param>
        /// <remarks>
        /// <para>
        /// <b>Runtime dependency:</b> This provider uses PostgreSQL via reflection and requires
        /// <c>Npgsql</c> to be installed in the consuming application.
        /// Add it to your project:
        /// <code>
        /// dotnet add package Npgsql
        /// </code>
        /// A clear <see cref="InvalidOperationException"/> is thrown at runtime if Npgsql is not present.
        /// </para>
        /// </remarks>
        public PostgresProvider(IDbParameterFactory parameterFactory)
        {
            _parameterFactory = parameterFactory ?? throw new ArgumentNullException(nameof(parameterFactory));
            // Dialect-only mode: when a non-native parameter factory is supplied, the caller is using
            // this provider purely for its SQL dialect against a foreign engine (e.g., SQLite). Native
            // connection-type and server-version validation must be skipped in that scenario.
            _isDialectOnly = parameterFactory is not ReflectionNpgsqlParameterFactory;
        }

        private readonly bool _isDialectOnly;

        private sealed class ReflectionNpgsqlParameterFactory : IDbParameterFactory
        {
            [System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
            private readonly Type? _parameterType = ResolveNpgsqlParameterType();

            // The driver assembly is loaded by name at runtime without a build-time reference, so
            // the trimmer cannot preserve its members. Trimmed or NativeAOT deployments must pass
            // the driver's native IDbParameterFactory to the provider constructor instead; this
            // fallback throws with package guidance when the driver types are unavailable.
            [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2073",
                Justification = "Optional driver types are resolved by name at runtime; trimmed deployments use an explicit IDbParameterFactory.")]
            [return: System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
            private static Type? ResolveNpgsqlParameterType() =>
                Type.GetType("Npgsql.NpgsqlParameter, Npgsql");

            public DbParameter CreateParameter(string name, object? value)
            {
                if (_parameterType == null)
                {
                    throw new InvalidOperationException(
                        "Npgsql package is required for PostgreSQL support. Add PackageReference Include=\"Npgsql\" to the consuming project.");
                }

                return (DbParameter)Activator.CreateInstance(_parameterType, name, value ?? DBNull.Value)!;
            }
        }

        /// <summary>
        /// Maximum length in characters of a single SQL statement supported by PostgreSQL.
        /// </summary>
        public override int MaxSqlLength => int.MaxValue;

        /// <inheritdoc />
        /// <remarks>PostgreSQL requires <c>true</c>/<c>false</c> literals; <c>1</c>/<c>0</c> cause type errors in boolean comparisons.</remarks>
        public override string BooleanTrueLiteral => "true";

        /// <inheritdoc />
        /// <remarks>PostgreSQL uses <c>false</c> rather than the default <c>0</c>.</remarks>
        public override string BooleanFalseLiteral => "false";

        /// <summary>
        /// Maximum number of parameters permitted in a prepared statement.
        /// </summary>
        public override int MaxParameters => 32_767;

        /// <inheritdoc />
        public override ProviderCapabilities Capabilities => new(
            "PostgreSQL",
            MinimumPostgresVersion,
            MaxParameters,
            true,
            true,
            true,
            true,
            "Requires Npgsql and PostgreSQL 12.0 or newer.");

        /// <summary>
        /// PostgreSQL sorts nulls LAST ascending / FIRST descending by default — the opposite of
        /// C#'s "null is smallest" ordering — so nullable order keys need the explicit null-rank
        /// entry. Every other supported provider already sorts nulls first ascending.
        /// </summary>
        internal override bool RequiresExplicitNullOrderingForNullableKeys => true;

        /// <summary>PostgreSQL supports <c>IS NOT DISTINCT FROM</c> for index-friendly null-safe equality.</summary>
        public override string NullSafeEqual(string left, string right)
            => $"{left} IS NOT DISTINCT FROM {right}";

        /// <summary>PostgreSQL supports <c>IS DISTINCT FROM</c> for index-friendly null-safe inequality.</summary>
        public override string NullSafeNotEqual(string left, string right)
            => $"{left} IS DISTINCT FROM {right}";

        /// <summary>Escapes a PostgreSQL identifier, including schema-qualified names.</summary>
        /// <param name="id">Identifier to escape (e.g., <c>"table"</c> or <c>"schema.table"</c>).</param>
        /// <returns>The escaped identifier with each segment wrapped in double quotes.</returns>
        /// <remarks>
        /// Doubles embedded double-quote characters to prevent SQL injection via identifiers.
        /// Handles schema-qualified identifiers (schema.table) by escaping each part separately.
        /// </remarks>
        public override string Escape(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return id;
            if (id.Contains('.'))
                return string.Join(".", id.Split('.').Select(part => $"\"{part.Replace("\"", "\"\"")}\""));
            return $"\"{id.Replace("\"", "\"\"")}\"";
        }

        /// <summary>
        /// PostgreSQL's default locale/ICU collation interleaves case for ordering;
        /// the "C" collation orders by byte (code point), matching C# ordinal
        /// relational comparison. Value-preserving — only the comparison changes.
        /// </summary>
        internal override string OrdinalRelationalStringOperand(string sql) => $"({sql} COLLATE \"C\")";

        /// <summary>PostgreSQL errors on a negative LIMIT; clamp to zero for LINQ's empty-window semantics.</summary>
        internal override string ClampNonNegativeLimitExpression(string expr) => $"GREATEST({expr}, 0)";

        /// <summary>
        /// Adds PostgreSQL-specific <c>LIMIT</c> and <c>OFFSET</c> clauses to the SQL builder.
        /// </summary>
        /// <param name="sb">Builder receiving the clauses.</param>
        /// <param name="limit">Maximum number of rows to return.</param>
        /// <param name="offset">Number of rows to skip.</param>
        /// <param name="limitParameterName">Name of the parameter supplying the limit.</param>
        /// <param name="offsetParameterName">Name of the parameter supplying the offset.</param>
        public override void ApplyPaging(OptimizedSqlBuilder sb, int? limit, int? offset, string? limitParameterName, string? offsetParameterName)
        {
            EnsureValidParameterName(limitParameterName, nameof(limitParameterName));
            EnsureValidParameterName(offsetParameterName, nameof(offsetParameterName));

            if (limitParameterName != null)
                sb.Append(" LIMIT ").Append(limitParameterName);
            else if (limit.HasValue)
                sb.Append(" LIMIT ").Append(limit.Value);

            if (offsetParameterName != null)
                sb.Append(" OFFSET ").Append(offsetParameterName);
            else if (offset.HasValue)
                sb.Append(" OFFSET ").Append(offset.Value);
        }

        /// <summary>
        /// Generates SQL for retrieving the value of an identity column after an insert.
        /// Uses PostgreSQL's <c>RETURNING</c> clause for single-statement identity retrieval.
        /// </summary>
        /// <param name="m">The mapping for the table being inserted into.</param>
        /// <returns>A <c>RETURNING</c> clause if a DB-generated key exists; otherwise <see cref="string.Empty"/>.</returns>
        public override string GetIdentityRetrievalString(TableMapping m)
        {
            // Target a DB-generated key, or — for the store-generated convention key's default-value run —
            // the convention key column, so RETURNING reads the generated value back.
            var keyCol = m.KeyColumns.FirstOrDefault(c => c.IsDbGenerated) ?? m.ConventionGeneratedKeyColumn;
            return keyCol != null ? $" RETURNING {keyCol.EscCol}" : string.Empty;
        }

    }
}
