using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using nORM.Core;
using nORM.Internal;
using nORM.Mapping;

#nullable enable

namespace nORM.Providers
{
    public sealed partial class PostgresProvider
    {
        /// <summary>
        /// Inserts entities using PostgreSQL's <c>COPY</c> binary protocol when available, falling back to batched inserts otherwise.
        /// </summary>
        /// <typeparam name="T">Type of entity being inserted.</typeparam>
        /// <param name="ctx">Context providing the connection.</param>
        /// <param name="m">Mapping metadata for the entity.</param>
        /// <param name="entities">Entities to insert.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>The number of rows inserted.</returns>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Bulk operations build provider transfer structures from mapping metadata and may dispatch to reflection-loaded driver APIs; not NativeAOT-compatible. See docs/aot-trimming.md.")]
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Bulk operations reflect over entity and driver types; trimming may remove the required members. See docs/aot-trimming.md.")]
        public override async Task<int> BulkInsertAsync<T>(DbContext ctx, TableMapping m, IEnumerable<T> entities, CancellationToken ct) where T : class
        {
            ValidateConnection(ctx.RawConnection);
            var sw = Stopwatch.StartNew();
            var entityList = entities.ToList();
            if (entityList.Count == 0) return 0;

            var cols = m.Columns.Where(c => !c.IsDbGenerated).ToArray();
            // Every column is DB-generated (e.g. an identity-only table). Postgres COPY and the
            // multi-row VALUES form cannot express a zero-column insert, so returning 0 here would
            // silently insert nothing. Delegate to the base implementation, which emits one
            // `INSERT ... DEFAULT VALUES` per entity (as SQLite and the base contract already do).
            if (cols.Length == 0)
                return await base.BulkInsertAsync(ctx, m, entityList, ct).ConfigureAwait(false);

            var operationKey = $"Postgres_BulkInsert_{m.Type.Name}";

            int inserted;
            // A default-valued convention store-generated key must be assigned by PG's GENERATED BY DEFAULT
            // identity, exactly as Add + SaveChanges does. The fixed COPY / multi-row VALUES column list can't
            // express a per-row DEFAULT, so omit the key column for default-keyed rows — writing the literal 0
            // stores 0 and rows collide on the primary key. Explicit keys are honored; partition so a batch
            // mixing default and explicit keys is fully correct.
            if (m.ConventionGeneratedKeyColumn is { } convKey)
            {
                var colsNoKey = cols.Where(c => !ReferenceEquals(c, convKey)).ToArray();
                List<T>? defaultKeyed = null;
                List<T>? explicitKeyed = null;
                foreach (var e in entityList)
                {
                    if (ChangeTracker.IsDefaultKeyValue(convKey.Getter(e), convKey.Prop.PropertyType))
                        (defaultKeyed ??= new List<T>()).Add(e);
                    else
                        (explicitKeyed ??= new List<T>()).Add(e);
                }

                if (defaultKeyed != null && explicitKeyed != null)
                    inserted = await BulkInsertRowsAsync(ctx, m, explicitKeyed, cols, operationKey, sw, ct).ConfigureAwait(false)
                             + await BulkInsertRowsAsync(ctx, m, defaultKeyed, colsNoKey, operationKey, sw, ct).ConfigureAwait(false);
                else if (defaultKeyed != null)
                    inserted = await BulkInsertRowsAsync(ctx, m, entityList, colsNoKey, operationKey, sw, ct).ConfigureAwait(false);
                else
                    inserted = await BulkInsertRowsAsync(ctx, m, entityList, cols, operationKey, sw, ct).ConfigureAwait(false);
            }
            else
            {
                inserted = await BulkInsertRowsAsync(ctx, m, entityList, cols, operationKey, sw, ct).ConfigureAwait(false);
            }

            ctx.Options.CacheProvider?.InvalidateTag(m.TableName); // Invalidate query cache after bulk write to prevent stale reads
            ctx.Options.Logger?.LogBulkOperation(nameof(BulkInsertAsync), m.EscTable, inserted, sw.Elapsed);
            return inserted;
        }

        /// <summary>
        /// Inserts <paramref name="entityList"/> using the supplied column set via COPY BINARY (Npgsql) or the
        /// multi-row VALUES fallback. Factored out of <see cref="BulkInsertAsync{T}"/> so the convention-key
        /// partition can run it twice with different column sets (with vs without the store-generated key).
        /// </summary>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Bulk operations build provider transfer structures from mapping metadata and may dispatch to reflection-loaded driver APIs; not NativeAOT-compatible. See docs/aot-trimming.md.")]
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Bulk operations reflect over entity and driver types; trimming may remove the required members. See docs/aot-trimming.md.")]
        private async Task<int> BulkInsertRowsAsync<T>(DbContext ctx, TableMapping m, List<T> entityList, Column[] cols, string operationKey, Stopwatch sw, CancellationToken ct) where T : class
        {
            var npgConnType = Type.GetType("Npgsql.NpgsqlConnection, Npgsql");
            if (npgConnType != null && npgConnType.IsInstanceOfType(ctx.RawConnection))
            {
                var copySql = $"COPY {m.EscTable} ({string.Join(", ", cols.Select(c => c.EscCol))}) FROM STDIN (FORMAT BINARY)";
                var beginMethod = ctx.RawConnection.GetType().GetMethod("BeginBinaryImport", new[] { typeof(string) });
                var importerObj = beginMethod?.Invoke(ctx.RawConnection, new object[] { copySql });
                if (importerObj == null) throw new InvalidOperationException("BeginBinaryImport not available");
                try
                {
                    dynamic importer = importerObj;
                    foreach (var entity in entityList)
                    {
                        importer.StartRow();
                        foreach (var col in cols)
                        {
                            // Apply the value converter like every non-bulk write path; binding the raw
                            // model value would skip the converter and silently corrupt the column.
                            var raw = col.Getter(entity);
                            var conv = col.Converter;
                            var val = conv != null ? conv.ConvertToProvider(raw) : raw;
                            // Match every other write path's ulong contract (ParameterAssign.ToStorableInt64):
                            // store as signed 64-bit, failing loud above long.MaxValue rather than letting
                            // the COPY writer persist a wrapped value.
                            if (val is ulong ul) val = nORM.Query.ParameterAssign.ToStorableInt64(ul);
                            if (val == null) importer.WriteNull();
                            else importer.Write(val);
                        }
                    }
                    await importer.CompleteAsync(ct).ConfigureAwait(false);
                }
                finally
                {
                    if (importerObj is IAsyncDisposable iad) await iad.DisposeAsync().ConfigureAwait(false);
                    else if (importerObj is IDisposable id) id.Dispose();
                }
                BatchSizer.RecordBatchPerformance(operationKey, entityList.Count, sw.Elapsed, entityList.Count);
                return entityList.Count;
            }

            return await ExecuteBulkOperationAsync(ctx, m, entityList, operationKey,
                (batch, tx, token) => ExecutePostgresBatchInsert(ctx, tx, m, cols, batch, token), ct).ConfigureAwait(false);
        }

        /// <summary>
        /// Executes a single batch of inserts using PostgreSQL's multi-row VALUES syntax.
        /// </summary>
        private async Task<int> ExecutePostgresBatchInsert<T>(DbContext ctx, DbTransaction transaction,
            TableMapping mapping, Column[] cols, List<T> batch, CancellationToken ct) where T : class
        {
            var sql = BuildPostgresBatchInsertSql(mapping, cols, batch.Count);

            await using var cmd = ctx.CreateCommand();
            cmd.Transaction = transaction;
            cmd.CommandText = sql;
            cmd.CommandTimeout = (int)ctx.Options.TimeoutConfiguration.BaseTimeout.TotalSeconds;

            var paramIndex = 0;
            foreach (var entity in batch)
            {
                foreach (var col in cols)
                {
                    var paramName = $"{ParamPrefix}p{paramIndex++}";
                    var raw = col.Getter(entity);
                    var conv = col.Converter;
                    var value = (conv != null ? conv.ConvertToProvider(raw) : raw) ?? DBNull.Value;
                    cmd.AddParam(paramName, value);
                }
            }

            return await cmd.ExecuteNonQueryWithInterceptionAsync(ctx, ct).ConfigureAwait(false);
        }

        /// <summary>
        /// Builds a multi-row INSERT INTO ... VALUES statement with parameterized placeholders.
        /// </summary>
        internal string BuildPostgresBatchInsertSql(TableMapping mapping, Column[] cols, int batchSize)
        {
            var colNames = string.Join(", ", cols.Select(c => c.EscCol));
            var sb = _stringBuilderPool.Get();
            try
            {
                sb.Append("INSERT INTO ").Append(mapping.EscTable)
                  .Append(" (").Append(colNames).Append(") VALUES ");

                var paramIndex = 0;
                for (int i = 0; i < batchSize; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append('(');

                    for (int j = 0; j < cols.Length; j++)
                    {
                        if (j > 0) sb.Append(", ");
                        sb.Append(ParamPrefix).Append('p').Append(paramIndex++);
                    }

                    sb.Append(')');
                }

                return sb.ToString();
            }
            finally
            {
                sb.Clear();
                _stringBuilderPool.Return(sb);
            }
        }

        /// <summary>
        /// Updates a sequence of entities using parameterized <c>UPDATE</c> statements executed in batches.
        /// </summary>
        /// <typeparam name="T">Entity type being updated.</typeparam>
        /// <param name="ctx">Active database context.</param>
        /// <param name="m">Entity-table mapping information.</param>
        /// <param name="entities">Entities with new values to persist.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>Count of rows updated.</returns>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Bulk operations build provider transfer structures from mapping metadata and may dispatch to reflection-loaded driver APIs; not NativeAOT-compatible. See docs/aot-trimming.md.")]
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Bulk operations reflect over entity and driver types; trimming may remove the required members. See docs/aot-trimming.md.")]
        public override async Task<int> BulkUpdateAsync<T>(DbContext ctx, TableMapping m, IEnumerable<T> entities, CancellationToken ct) where T : class
        {
            ValidateConnection(ctx.RawConnection);
            // A client-managed [Timestamp] token must be freshly stamped per row on each update
            // (the VALUES-join fast path below only copies the entity columns and would leave the
            // token unchanged, silently losing a concurrent write). Route through the row-by-row
            // BatchedUpdateAsync, which stamps a new token and compares the old one.
            if (m.ClientManagedConcurrencyToken || ctx.Options.UseBatchedBulkOps)
                return await base.BatchedUpdateAsync(ctx, m, entities, ct).ConfigureAwait(false);

            var sw = Stopwatch.StartNew();
            var entityList = entities.ToList();
            if (entityList.Count == 0) return 0;

            // SET only the updatable columns (non-key, non-timestamp, non-db-generated, non-discriminator) —
            // the same set SqlServer/MySQL use. Assigning a DB-generated column is rejected by Postgres (a
            // GENERATED column can't be written) and a store-generated default / TPH discriminator would be
            // silently overwritten.
            var nonKeyCols = m.UpdateColumns.ToList();
            if (nonKeyCols.Count == 0) return 0;
            var keyCols = m.KeyColumns.ToList();
            var valueCols = keyCols.Concat(nonKeyCols).ToList();
            if (m.TimestampColumn != null) valueCols.Add(m.TimestampColumn);

            var paramsPerEntity = valueCols.Count;
            var operationKey = $"Postgres_BulkUpdate_{m.Type.Name}";
            var sizing = BatchSizer.CalculateOptimalBatchSize(entityList.Take(BatchSizingSampleCount), m, operationKey, entityList.Count);
            var maxBatchForProvider = MaxParameters / Math.Max(1, paramsPerEntity);
            var batchSize = Math.Max(1, Math.Min(sizing.OptimalBatchSize, maxBatchForProvider));

            var totalUpdated = 0;
            var ownedTx = ctx.CurrentTransaction == null;
            DbTransaction? transaction = ownedTx
                ? await ctx.RawConnection.BeginTransactionAsync(ct).ConfigureAwait(false)
                : ctx.CurrentTransaction;
            try
            {
                for (int i = 0; i < entityList.Count; i += batchSize)
                {
                    var batch = entityList.GetRange(i, Math.Min(batchSize, entityList.Count - i));
                    await using var cmd = ctx.CreateCommand();
                    cmd.Transaction = transaction;
                    cmd.CommandTimeout = (int)ctx.Options.TimeoutConfiguration.BaseTimeout.TotalSeconds;

                    var sb = _stringBuilderPool.Get();
                    try
                    {
                        sb.Append("UPDATE ").Append(m.EscTable).Append(" AS t SET ");
                        sb.Append(string.Join(", ", nonKeyCols.Select(c => $"{c.EscCol} = v.{c.EscCol}")));
                        sb.Append(" FROM (VALUES ");

                        var valueRows = new List<string>();
                        var paramIndex = 0;
                        foreach (var entity in batch)
                        {
                            var paramNames = new List<string>();
                            foreach (var col in valueCols)
                            {
                                var pName = $"{ParamPrefix}p{paramIndex++}";
                                var raw = col.Getter(entity);
                                var conv = col.Converter;
                                cmd.AddParam(pName, conv != null ? conv.ConvertToProvider(raw) : raw);
                                paramNames.Add(pName);
                            }
                            valueRows.Add($"({string.Join(", ", paramNames)})");
                        }

                        sb.Append(string.Join(", ", valueRows));
                        sb.Append(") AS v (");
                        sb.Append(string.Join(", ", valueCols.Select(c => c.EscCol)));
                        sb.Append(") WHERE ");

                        // Add tenant predicate to prevent cross-tenant bulk updates
                        var tenantCol = ctx.Options.TenantProvider != null
                            ? ctx.RequireTenantColumn(m, "PostgreSQL bulk update")
                            : null;
                        var tenantParam = tenantCol != null
                            ? $"{ParamPrefix}__tenant_bulk"
                            : null;
                        sb.Append(BuildBulkUpdateWhereClause(
                            keyCols.Select(c => c.EscCol),
                            m.TimestampColumn?.EscCol,
                            tenantCol?.EscCol,
                            tenantParam));
                        if (tenantParam != null)
                        {
                            cmd.AddParam(tenantParam, ctx.GetRequiredTenantId(m, "PostgreSQL bulk update"));
                        }

                        cmd.CommandText = sb.ToString();

                        var batchSw = Stopwatch.StartNew();
                        totalUpdated += await cmd.ExecuteNonQueryWithInterceptionAsync(ctx, ct).ConfigureAwait(false);
                        batchSw.Stop();
                        BatchSizer.RecordBatchPerformance(operationKey, batch.Count, batchSw.Elapsed, batch.Count);
                    }
                    finally
                    {
                        sb.Clear();
                        _stringBuilderPool.Return(sb);
                    }
                }

                if (ownedTx) await transaction!.CommitAsync(CancellationToken.None).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                if (ownedTx)
                {
                    try { await transaction!.RollbackAsync(CancellationToken.None).ConfigureAwait(false); }
                    catch (Exception rollbackEx) { throw new AggregateException(ex, rollbackEx); }
                }
                throw;
            }
            finally
            {
                if (ownedTx && transaction != null)
                    await transaction.DisposeAsync().ConfigureAwait(false);
            }

            ctx.Options.CacheProvider?.InvalidateTag(m.TableName); // Invalidate query cache after bulk write to prevent stale reads
            ctx.Options.Logger?.LogBulkOperation(nameof(BulkUpdateAsync), m.EscTable, totalUpdated, sw.Elapsed);
            return totalUpdated;
        }

        internal static string BuildBulkUpdateWhereClause(
            IEnumerable<string> keyColumns,
            string? timestampColumn,
            string? tenantColumn,
            string? tenantParameter)
        {
            var conditions = keyColumns.Select(c => $"t.{c} = v.{c}").ToList();
            if (timestampColumn != null)
                conditions.Add($"t.{timestampColumn} = v.{timestampColumn}");
            if (tenantColumn != null && tenantParameter != null)
                conditions.Add($"t.{tenantColumn} = {tenantParameter}");
            return string.Join(" AND ", conditions);
        }

        /// <summary>
        /// Deletes entities by primary key using batched <c>DELETE</c> statements.
        /// </summary>
        /// <typeparam name="T">Type of entity to delete.</typeparam>
        /// <param name="ctx">Active <see cref="DbContext"/>.</param>
        /// <param name="m">Table mapping containing key metadata.</param>
        /// <param name="entities">Entities whose keys identify rows to delete.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>Number of rows deleted.</returns>
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Bulk operations build provider transfer structures from mapping metadata and may dispatch to reflection-loaded driver APIs; not NativeAOT-compatible. See docs/aot-trimming.md.")]
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Bulk operations reflect over entity and driver types; trimming may remove the required members. See docs/aot-trimming.md.")]
        public override async Task<int> BulkDeleteAsync<T>(DbContext ctx, TableMapping m, IEnumerable<T> entities, CancellationToken ct) where T : class
        {
            ValidateConnection(ctx.RawConnection);
            if (ctx.Options.UseBatchedBulkOps) return await base.BatchedDeleteAsync(ctx, m, entities, ct).ConfigureAwait(false);

            var sw = Stopwatch.StartNew();
            var entityList = entities.ToList();
            if (entityList.Count == 0) return 0;

            if (m.KeyColumns.Length != 1)
                return await base.BatchedDeleteAsync(ctx, m, entityList, ct).ConfigureAwait(false);

            // Optimistic concurrency: the fast `= ANY(keys)` path matches by key only,
            // which cannot honour a concurrency token. Route token-carrying entities
            // through the shared fallback, which matches (key AND token) so a row another
            // writer has updated is skipped, not destroyed. Token-less entities keep the
            // fast native path.
            if (m.TimestampColumn != null)
                return await base.BatchedDeleteAsync(ctx, m, entityList, ct).ConfigureAwait(false);

            var keyCol = m.KeyColumns[0];
            var operationKey = $"Postgres_BulkDelete_{m.Type.Name}";
            var sizing = BatchSizer.CalculateOptimalBatchSize(entityList.Take(BatchSizingSampleCount), m, operationKey, entityList.Count);
            var batchSize = Math.Max(1, sizing.OptimalBatchSize);

            var totalDeleted = 0;
            var ownedTx = ctx.CurrentTransaction == null;
            DbTransaction? transaction = ownedTx
                ? await ctx.RawConnection.BeginTransactionAsync(ct).ConfigureAwait(false)
                : ctx.CurrentTransaction;
            try
            {
                for (int i = 0; i < entityList.Count; i += batchSize)
                {
                    var batch = entityList.GetRange(i, Math.Min(batchSize, entityList.Count - i));
                    // Convert key values like every other write path: the destination stores
                    // the PROVIDER representation, so matching on raw model values would
                    // silently delete zero rows for converter-typed keys.
                    var keys = CreateTypedArray(batch.Select(e =>
                    {
                        var raw = keyCol.Getter(e);
                        return keyCol.Converter != null ? keyCol.Converter.ConvertToProvider(raw) : raw;
                    }).ToArray());
                    await using var cmd = ctx.CreateCommand();
                    cmd.Transaction = transaction;
                    cmd.CommandTimeout = (int)ctx.Options.TimeoutConfiguration.BaseTimeout.TotalSeconds;
                    var pName = $"{ParamPrefix}p0";
                    var p = cmd.CreateParameter();
                    p.ParameterName = pName;
                    p.Value = keys;
                    cmd.Parameters.Add(p);
                    var deleteSql = $"DELETE FROM {m.EscTable} WHERE {keyCol.EscCol} = ANY({pName})";
                    // Add tenant predicate to prevent cross-tenant bulk deletes
                    if (ctx.Options.TenantProvider != null)
                    {
                        var tenantCol = ctx.RequireTenantColumn(m, "PostgreSQL bulk delete");
                        var tenantParam = $"{ParamPrefix}__tenant_bulk";
                        var tp = cmd.CreateParameter();
                        tp.ParameterName = tenantParam;
                        tp.Value = ctx.GetRequiredTenantId(m, "PostgreSQL bulk delete");
                        cmd.Parameters.Add(tp);
                        deleteSql += $" AND {tenantCol.EscCol} = {tenantParam}";
                    }
                    cmd.CommandText = deleteSql;
                    var batchSw = Stopwatch.StartNew();
                    totalDeleted += await cmd.ExecuteNonQueryWithInterceptionAsync(ctx, ct).ConfigureAwait(false);
                    batchSw.Stop();
                    BatchSizer.RecordBatchPerformance(operationKey, batch.Count, batchSw.Elapsed, batch.Count);
                }

                if (ownedTx) await transaction!.CommitAsync(CancellationToken.None).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                if (ownedTx)
                {
                    try { await transaction!.RollbackAsync(CancellationToken.None).ConfigureAwait(false); }
                    catch (Exception rollbackEx) { throw new AggregateException(ex, rollbackEx); }
                }
                throw;
            }
            finally
            {
                if (ownedTx && transaction != null)
                    await transaction.DisposeAsync().ConfigureAwait(false);
            }

            ctx.InvalidateResultCacheForDeletedTable(m); // invalidate cache (incl. ON DELETE CASCADE child tables) to prevent stale reads
            ctx.Options.Logger?.LogBulkOperation(nameof(BulkDeleteAsync), m.EscTable, totalDeleted, sw.Elapsed);
            return totalDeleted;
        }

        /// <summary>
        /// Maps a CLR type to its PostgreSQL column type equivalent.
        /// Used when generating history tables from CLR metadata without live introspection data.
        /// </summary>
        /// <param name="t">The CLR type to map (unwraps <see cref="Nullable{T}"/> and enum types internally).</param>
        /// <returns>A PostgreSQL type name string (e.g., <c>"INTEGER"</c>, <c>"TEXT"</c>, <c>"UUID"</c>).</returns>
        private static string GetPostgresType(Type t)
        {
            t = Nullable.GetUnderlyingType(t) ?? t;
            if (t.IsEnum) t = Enum.GetUnderlyingType(t);
            if (t == typeof(int)) return "INTEGER";
            if (t == typeof(long)) return "BIGINT";
            if (t == typeof(string)) return "TEXT";
            if (t == typeof(DateTime)) return "TIMESTAMP";
            if (t == typeof(DateOnly)) return "DATE";
            if (t == typeof(TimeOnly)) return "TIME";
            if (t == typeof(DateTimeOffset)) return "TIMESTAMPTZ";
            if (t == typeof(TimeSpan)) return "INTERVAL";
            if (t == typeof(bool)) return "BOOLEAN";
            // Wide default: history rows copy main-table decimals, and a narrow scale
            // would silently round them (no single SQL DECIMAL holds every .NET decimal;
            // live introspection of the main table is the exact path).
            if (t == typeof(decimal)) return "DECIMAL(38,18)";
            if (t == typeof(Guid)) return "UUID";
            if (t == typeof(byte[])) return "BYTEA";
            if (t == typeof(float)) return "REAL";
            if (t == typeof(double)) return "DOUBLE PRECISION";
            if (t == typeof(short)) return "SMALLINT";
            if (t == typeof(byte)) return "SMALLINT";
            if (t == typeof(char)) return "CHAR(1)";
            if (t == typeof(sbyte)) return "SMALLINT";
            if (t == typeof(ushort)) return "INTEGER";
            if (t == typeof(uint)) return "BIGINT";
            if (t == typeof(ulong)) return "NUMERIC(20,0)";
            return "TEXT";
        }
    }
}
