using System;

namespace nORM.Migration
{
    public partial class PostgresMigrationSqlGenerator
    {
        /// <summary>
        /// The identity clause for an identity column: <c>GENERATED BY DEFAULT AS IDENTITY</c> when the column
        /// honors an explicitly-supplied value (the store-generated-key convention — the database generates the
        /// value only when it is default), otherwise the strict <c>GENERATED ALWAYS AS IDENTITY</c> (rejects an
        /// explicit value). See <see cref="ColumnSchema.IdentityByDefault"/>.
        /// </summary>
        private static string GetIdentityClause(ColumnSchema column)
            => column.IdentityByDefault ? " GENERATED BY DEFAULT AS IDENTITY" : " GENERATED ALWAYS AS IDENTITY";

        /// <summary>
        /// Returns the appropriate PostgreSQL integer type for an identity column: BIGINT for long/ulong,
        /// INTEGER for all other integer types. Non-integer CLR types return INTEGER with a leading SQL warning
        /// comment because GENERATED ... AS IDENTITY is only valid for integer types in PostgreSQL.
        /// </summary>
        private static string GetIdentitySqlType(ColumnSchema column)
        {
            if (string.Equals(column.ClrType, typeof(long).FullName, StringComparison.Ordinal)
             || string.Equals(column.ClrType, typeof(ulong).FullName, StringComparison.Ordinal))
                return "BIGINT";

            if (!_integerClrTypes.Contains(column.ClrType))
                // WARNING: GENERATED ... AS IDENTITY is only valid for integer types in PostgreSQL.
                // The column CLR type is not an integer type; INTEGER is used as a fallback — verify the mapping is correct.
                return "/* WARNING: GENERATED AS IDENTITY is only valid for integer types in PostgreSQL */ INTEGER";

            return "INTEGER";
        }
    }
}
