using System.CommandLine;

partial class Program
{
    private static ScaffoldGenerationCommandSymbols CreateScaffoldGenerationCommandSymbols()
        => new(
            new Option<bool>("--no-pluralize") { Description = "Do not singularize entity class names or pluralize generated IQueryable<T> context property names." },
            new Option<bool>("--use-database-names") { Description = "Preserve legal table, view, sequence, routine, column, and routine result-column names as generated CLR names instead of applying PascalCase naming." },
            new Option<bool>("--no-relationships") { Description = "Do not generate relationship navigation properties, many-to-many skip mappings, or fluent relationship configuration." },
            new Option<bool>("--json") { Description = "Emit a machine-readable scaffold result summary." },
            new Option<bool>("--force", "-f") { Description = "Overwrite existing generated files. By default, scaffold output conflicts are refused." },
            new Option<bool>("--no-overwrite") { Description = "Explicitly refuse to overwrite existing generated files." },
            new Option<bool>("--dry-run") { Description = "Validate scaffold output without creating, deleting, or overwriting files." },
            new Option<bool>("--fail-on-warnings") { Description = "Fail scaffolding when unsupported schema features are reported in nORM.ScaffoldWarnings.md/json." },
            new Option<bool>("--emit-routine-stubs") { Description = "Generate provider-bound context wrapper methods for discovered routines/stored procedures. Routine bodies remain provider-owned." },
            new Option<bool>("--emit-sequence-stubs") { Description = "Generate provider-bound context wrapper methods for discovered SQL Server/PostgreSQL standalone sequences." },
            new Option<bool>("--emit-view-entities") { Description = "Compatibility alias for --emit-query-artifacts; generates optional query-only entity classes such as SQLite virtual tables and local table/view synonyms. Ordinary views/materialized views are generated by default." },
            new Option<bool>("--emit-query-artifacts") { Description = "Generate bounded read-oriented query artifacts for optional provider objects such as SQLite virtual tables and local table/view synonyms." });

    private static void AddScaffoldGenerationCommandSymbols(Command scaffold, ScaffoldCommandSymbols symbols)
    {
        scaffold.Add(symbols.NoPluralizeOption);
        scaffold.Add(symbols.UseDatabaseNamesOption);
        scaffold.Add(symbols.NoRelationshipsOption);
        scaffold.Add(symbols.JsonOption);
        scaffold.Add(symbols.ForceOption);
        scaffold.Add(symbols.NoOverwriteOption);
        scaffold.Add(symbols.DryRunOption);
        scaffold.Add(symbols.FailOnWarningsOption);
        scaffold.Add(symbols.EmitRoutineStubsOption);
        scaffold.Add(symbols.EmitSequenceStubsOption);
        scaffold.Add(symbols.EmitViewEntitiesOption);
        scaffold.Add(symbols.EmitQueryArtifactsOption);
    }
}
