#nullable enable
using System.Text;
using static nORM.Scaffolding.ScaffoldCodeText;

namespace nORM.Scaffolding
{
    internal static partial class ScaffoldEntityWriter
    {
        public static string Write(ScaffoldEntityInfo entity)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            AppendNullableDirective(sb, entity.UseNullableReferenceTypes);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
            if (entity.HasIndexes || entity.IsReadOnlyEntity)
                sb.AppendLine("using nORM.Configuration;");
            sb.AppendLine();
            sb.AppendLine($"namespace {entity.NamespaceName};");
            sb.AppendLine();

            var safeTableName = EscapeStringLiteral(entity.TableName);
            var tableAttr = entity.SchemaName is not null
                ? $"[Table(\"{safeTableName}\", Schema = \"{EscapeStringLiteral(entity.SchemaName)}\")]"
                : $"[Table(\"{safeTableName}\")]";
            if (!string.IsNullOrWhiteSpace(entity.TableComment))
                AppendXmlSummary(sb, string.Empty, entity.TableComment!);
            sb.AppendLine(tableAttr);
            if (entity.IsReadOnlyEntity)
                sb.AppendLine("[ReadOnlyEntity]");
            sb.AppendLine($"public partial class {ScaffoldNameHelper.EscapeCSharpIdentifier(entity.EntityName)}");
            sb.AppendLine("{");

            foreach (var column in entity.Columns)
                AppendColumn(sb, column, entity.UseNullableReferenceTypes);

            AppendReferences(sb, entity.References, entity.UseNullableReferenceTypes);
            AppendCollections(sb, entity.Collections, entity.UseNullableReferenceTypes);
            AppendManyToManyCollections(sb, entity.ManyToManyCollections);

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
