#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using nORM.Core;
using static nORM.Scaffolding.ScaffoldCodeText;

namespace nORM.Scaffolding
{
    internal static class ScaffoldContextWriter
    {
        public static string Write(ScaffoldContextInfo context)
        {
            var emitRoutineStubs = context.RoutineStubs.Count > 0;
            var hasSequenceStubs = context.SequenceStubs.Count > 0;
            var needsSystemUsing = context.Relationships.Count > 0
                                   || context.ManyToManyJoins.Count > 0
                                   || context.CompositePrimaryKeys.Count > 0
                                   || emitRoutineStubs;
            var sb = new StringBuilder();
            AppendScaffoldContextHeader(
                sb,
                context.NamespaceName,
                context.ContextName,
                emitRoutineStubs,
                hasSequenceStubs,
                needsSystemUsing,
                context.UseNullableReferenceTypes,
                context.EntityNamespaceName);
            var queryPropertyNames = AppendScaffoldContextConstructorsAndQueries(
                sb,
                context.ContextName,
                context.EntityNames,
                context.PluralizeQueryProperties,
                context.UseNullableReferenceTypes);
            if (emitRoutineStubs)
                ScaffoldRoutineStubWriter.AppendRoutineStubs(sb, context.RoutineStubs, queryPropertyNames, context.UseNullableReferenceTypes, context.UseDatabaseNames);
            if (hasSequenceStubs)
                AppendSequenceStubs(sb, context.SequenceStubs, queryPropertyNames, context.UseDatabaseNames);
            AppendConfigureOptionsStart(sb, context.UseNullableReferenceTypes);
            AppendModelConfiguration(sb, context);
            AppendScaffoldContextFooter(sb);
            return sb.ToString();
        }

        private static void AppendScaffoldContextHeader(
            StringBuilder sb,
            string namespaceName,
            string contextName,
            bool hasRoutineStubs,
            bool hasSequenceStubs,
            bool needsSystemUsing,
            bool useNullableReferenceTypes,
            string? entityNamespaceName)
        {
            var needsEntityNamespaceUsing = !string.IsNullOrWhiteSpace(entityNamespaceName)
                                            && !string.Equals(namespaceName, entityNamespaceName, StringComparison.Ordinal);
            sb.AppendLine("// <auto-generated/>");
            AppendNullableDirective(sb, useNullableReferenceTypes);
            sb.AppendLine("using System.Data.Common;");
            if (hasRoutineStubs || hasSequenceStubs)
            {
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Threading;");
                sb.AppendLine("using System.Threading.Tasks;");
            }

            sb.AppendLine("using System.Linq;");
            if (needsSystemUsing)
                sb.AppendLine("using System;");
            sb.AppendLine("using nORM.Core;");
            sb.AppendLine("using nORM.Configuration;");
            sb.AppendLine("using nORM.Providers;");
            if (needsEntityNamespaceUsing)
                sb.AppendLine($"using {entityNamespaceName};");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
            sb.AppendLine($"public partial class {ScaffoldNameHelper.EscapeCSharpIdentifier(contextName)} : DbContext");
            sb.AppendLine("{");
        }

        private static HashSet<string> AppendScaffoldContextConstructorsAndQueries(
            StringBuilder sb,
            string contextName,
            IEnumerable<string> entities,
            bool pluralizeQueryProperties,
            bool useNullableReferenceTypes)
        {
            var safeContext = ScaffoldNameHelper.EscapeCSharpIdentifier(contextName);
            var nullableReferenceSuffix = useNullableReferenceTypes ? "?" : string.Empty;
            sb.AppendLine($"    public {safeContext}(DbConnection cn, DatabaseProvider provider, DbContextOptions{nullableReferenceSuffix} options = null) : base(cn, provider, ConfigureOptions(options)) {{ }}");
            sb.AppendLine($"    public {safeContext}(string connectionString, DatabaseProvider provider, DbContextOptions{nullableReferenceSuffix} options = null) : base(connectionString, provider, ConfigureOptions(options)) {{ }}");
            sb.AppendLine();

            var queryPropertyNames = CreateReservedContextMemberNameSet();
            foreach (var entity in entities.OrderBy(e => e))
            {
                var safeEntity = ScaffoldNameHelper.EscapeCSharpIdentifier(entity);
                var queryPropertyBase = pluralizeQueryProperties ? ScaffoldNameHelper.Pluralize(safeEntity) : safeEntity;
                var queryProperty = ScaffoldNameHelper.MakeUnique(queryPropertyBase, queryPropertyNames);
                sb.AppendLine($"    public IQueryable<{safeEntity}> {queryProperty} => this.Query<{safeEntity}>();");
            }

            return queryPropertyNames;
        }

        private static void AppendConfigureOptionsStart(StringBuilder sb, bool useNullableReferenceTypes)
        {
            var nullableReferenceSuffix = useNullableReferenceTypes ? "?" : string.Empty;
            sb.AppendLine();
            sb.AppendLine($"    private static DbContextOptions ConfigureOptions(DbContextOptions{nullableReferenceSuffix} options)");
            sb.AppendLine("    {");
            sb.AppendLine("        var configuredOptions = options?.Clone() ?? new DbContextOptions();");
            sb.AppendLine("        var configure = configuredOptions.OnModelCreating;");
            sb.AppendLine("        configuredOptions.OnModelCreating = mb =>");
            sb.AppendLine("        {");
            sb.AppendLine("            configure?.Invoke(mb);");
        }

        private static void AppendModelConfiguration(StringBuilder sb, ScaffoldContextInfo context)
        {
            AppendPrimaryKeyConfigurations(sb, context.CompositePrimaryKeys);
            AppendDefaultValueConfigurations(sb, context.DefaultValueConfigurations);
            AppendIdentityOptionConfigurations(sb, context.IdentityOptionConfigurations);
            AppendPrecisionConfigurations(sb, context.PrecisionConfigurations);
            AppendColumnFacetConfigurations(sb, context.ColumnFacetConfigurations);
            AppendCheckConstraintConfigurations(sb, context.CheckConstraintConfigurations);
            AppendComputedColumnConfigurations(sb, context.ComputedColumnConfigurations);
            AppendCollationConfigurations(sb, context.CollationConfigurations);
            AppendExpressionIndexConfigurations(sb, context.ExpressionIndexConfigurations);
            AppendRelationshipConfigurations(sb, context.Relationships);
            AppendManyToManyConfigurations(sb, context.ManyToManyJoins);
        }

        private static void AppendPrimaryKeyConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextPrimaryKeyInfo> compositePrimaryKeys)
        {
            foreach (var key in compositePrimaryKeys.OrderBy(k => k.EntityName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(key.EntityName);
                var constraintNameSuffix = string.IsNullOrWhiteSpace(key.ConstraintName)
                    ? string.Empty
                    : $", \"{EscapeStringLiteral(key.ConstraintName)}\"";
                sb.AppendLine($"            mb.Entity<{entity}>().HasKey({FormatScaffoldKeySelector("e", key.PropertyNames)}{constraintNameSuffix});");
            }
        }

        private static void AppendDefaultValueConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextDefaultValueInfo> defaultValueConfigurations)
        {
            foreach (var defaultValue in defaultValueConfigurations
                .OrderBy(d => d.EntityName, StringComparer.Ordinal)
                .ThenBy(d => d.PropertyName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(defaultValue.EntityName);
                var property = ScaffoldNameHelper.EscapeCSharpIdentifier(defaultValue.PropertyName);
                var sql = EscapeStringLiteral(defaultValue.DefaultValueSql);
                sb.AppendLine($"            mb.Entity<{entity}>().Property(e => e.{property}).HasDefaultValueSql(\"{sql}\");");
            }
        }

        private static void AppendIdentityOptionConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextIdentityOptionInfo> identityOptionConfigurations)
        {
            foreach (var identity in identityOptionConfigurations
                .OrderBy(i => i.EntityName, StringComparer.Ordinal)
                .ThenBy(i => i.PropertyName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(identity.EntityName);
                var property = ScaffoldNameHelper.EscapeCSharpIdentifier(identity.PropertyName);
                sb.AppendLine($"            mb.Entity<{entity}>().Property(e => e.{property}).HasIdentityOptions({identity.Seed.ToString(CultureInfo.InvariantCulture)}, {identity.Increment.ToString(CultureInfo.InvariantCulture)});");
            }
        }

        private static void AppendPrecisionConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextPrecisionInfo> precisionConfigurations)
        {
            foreach (var precision in precisionConfigurations
                .OrderBy(p => p.EntityName, StringComparer.Ordinal)
                .ThenBy(p => p.PropertyName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(precision.EntityName);
                var property = ScaffoldNameHelper.EscapeCSharpIdentifier(precision.PropertyName);
                var precisionValue = precision.Precision.ToString(CultureInfo.InvariantCulture);
                if (precision.Scale.HasValue)
                    sb.AppendLine($"            mb.Entity<{entity}>().Property(e => e.{property}).HasPrecision({precisionValue}, {precision.Scale.Value.ToString(CultureInfo.InvariantCulture)});");
                else
                    sb.AppendLine($"            mb.Entity<{entity}>().Property(e => e.{property}).HasPrecision({precisionValue});");
            }
        }

        private static void AppendColumnFacetConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextColumnFacetInfo> columnFacetConfigurations)
        {
            foreach (var facet in columnFacetConfigurations
                .OrderBy(f => f.EntityName, StringComparer.Ordinal)
                .ThenBy(f => f.PropertyName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(facet.EntityName);
                var property = ScaffoldNameHelper.EscapeCSharpIdentifier(facet.PropertyName);
                var builder = $"mb.Entity<{entity}>().Property(e => e.{property})";
                if (facet.MaxLength.HasValue)
                    builder += $".HasMaxLength({facet.MaxLength.Value.ToString(CultureInfo.InvariantCulture)})";
                if (facet.IsUnicode.HasValue)
                    builder += $".IsUnicode({(facet.IsUnicode.Value ? "true" : "false")})";
                if (facet.IsFixedLength)
                    builder += ".IsFixedLength()";
                sb.AppendLine($"            {builder};");
            }
        }

        private static void AppendCheckConstraintConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextCheckConstraintInfo> checkConstraintConfigurations)
        {
            foreach (var check in checkConstraintConfigurations
                .OrderBy(c => c.EntityName, StringComparer.Ordinal)
                .ThenBy(c => c.Name, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(check.EntityName);
                var name = EscapeStringLiteral(check.Name);
                var sql = EscapeStringLiteral(check.Sql);
                sb.AppendLine($"            mb.Entity<{entity}>().HasCheckConstraint(\"{name}\", \"{sql}\");");
            }
        }

        private static void AppendComputedColumnConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextComputedColumnInfo> computedColumnConfigurations)
        {
            foreach (var computed in computedColumnConfigurations
                .OrderBy(c => c.EntityName, StringComparer.Ordinal)
                .ThenBy(c => c.PropertyName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(computed.EntityName);
                var property = ScaffoldNameHelper.EscapeCSharpIdentifier(computed.PropertyName);
                var sql = EscapeStringLiteral(computed.Sql);
                var storedSuffix = computed.Stored ? ", stored: true" : string.Empty;
                sb.AppendLine($"            mb.Entity<{entity}>().Property(e => e.{property}).HasComputedColumnSql(\"{sql}\"{storedSuffix});");
            }
        }

        private static void AppendCollationConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextCollationInfo> collationConfigurations)
        {
            foreach (var collation in collationConfigurations
                .OrderBy(c => c.EntityName, StringComparer.Ordinal)
                .ThenBy(c => c.PropertyName, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(collation.EntityName);
                var property = ScaffoldNameHelper.EscapeCSharpIdentifier(collation.PropertyName);
                var value = EscapeStringLiteral(collation.Collation);
                sb.AppendLine($"            mb.Entity<{entity}>().Property(e => e.{property}).HasCollation(\"{value}\");");
            }
        }

        private static void AppendExpressionIndexConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextExpressionIndexInfo> expressionIndexConfigurations)
        {
            foreach (var expressionIndex in expressionIndexConfigurations
                .OrderBy(i => i.EntityName, StringComparer.Ordinal)
                .ThenBy(i => i.Name, StringComparer.Ordinal))
            {
                var entity = ScaffoldNameHelper.EscapeCSharpIdentifier(expressionIndex.EntityName);
                var name = EscapeStringLiteral(expressionIndex.Name);
                var expressionSql = EscapeStringLiteral(expressionIndex.ExpressionSql);
                var uniqueSuffix = expressionIndex.IsUnique ? ", isUnique: true" : string.Empty;
                var filterSuffix = string.IsNullOrWhiteSpace(expressionIndex.FilterSql) ? string.Empty : $", filterSql: \"{EscapeStringLiteral(expressionIndex.FilterSql)}\"";
                sb.AppendLine($"            mb.Entity<{entity}>().HasExpressionIndex(\"{name}\", \"{expressionSql}\"{uniqueSuffix}{filterSuffix});");
            }
        }

        private static void AppendRelationshipConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldContextRelationshipInfo> relationships)
        {
            foreach (var relationship in relationships
                .OrderBy(r => r.PrincipalEntityName, StringComparer.Ordinal)
                .ThenBy(r => r.DependentEntityName, StringComparer.Ordinal)
                .ThenBy(r => r.CollectionNavigationName, StringComparer.Ordinal)
                .ThenBy(r => r.ReferenceNavigationName, StringComparer.Ordinal)
                .ThenBy(r => r.ForeignKeyPropertyNames[0], StringComparer.Ordinal))
            {
                var principal = ScaffoldNameHelper.EscapeCSharpIdentifier(relationship.PrincipalEntityName);
                var dependent = ScaffoldNameHelper.EscapeCSharpIdentifier(relationship.DependentEntityName);
                var collection = ScaffoldNameHelper.EscapeCSharpIdentifier(relationship.CollectionNavigationName);
                var reference = ScaffoldNameHelper.EscapeCSharpIdentifier(relationship.ReferenceNavigationName);
                var foreignKey = FormatScaffoldKeySelector("d", relationship.ForeignKeyPropertyNames);
                var principalKey = FormatScaffoldKeySelector("p", relationship.PrincipalKeyPropertyNames);
                sb.AppendLine($"            mb.Entity<{principal}>()");
                sb.AppendLine(relationship.IsUniqueDependentKey
                    ? $"                .HasOne(p => p.{collection})"
                    : $"                .HasMany(p => p.{collection})");
                sb.AppendLine($"                .WithOne(d => d.{reference})");
                if (IsLegacyCascadeShape(relationship))
                {
                    AppendLegacyRelationshipForeignKey(sb, relationship, foreignKey, principalKey);
                }
                else
                {
                    var constraintNameSuffix = string.IsNullOrWhiteSpace(relationship.ConstraintName)
                        ? string.Empty
                        : $", \"{EscapeStringLiteral(relationship.ConstraintName)}\"";
                    sb.AppendLine($"                .HasForeignKey({foreignKey}, {principalKey}, {FormatReferentialAction(relationship.OnDelete)}, {FormatReferentialAction(relationship.OnUpdate)}{constraintNameSuffix});");
                }
            }
        }

        private static void AppendLegacyRelationshipForeignKey(StringBuilder sb, ScaffoldContextRelationshipInfo relationship, string foreignKey, string principalKey)
        {
            var cascadeSuffix = relationship.CascadeDelete ? string.Empty : ", cascadeDelete: false";
            if (!string.IsNullOrWhiteSpace(relationship.ConstraintName))
            {
                var constraintName = EscapeStringLiteral(relationship.ConstraintName);
                cascadeSuffix = relationship.CascadeDelete
                    ? $", \"{constraintName}\""
                    : $", \"{constraintName}\", false";
            }

            sb.AppendLine($"                .HasForeignKey({foreignKey}, {principalKey}{cascadeSuffix});");
        }

        private static void AppendManyToManyConfigurations(StringBuilder sb, IReadOnlyList<ScaffoldManyToManyJoinInfo> manyToManyJoins)
        {
            foreach (var join in manyToManyJoins
                .OrderBy(j => j.LeftEntityName, StringComparer.Ordinal)
                .ThenBy(j => j.RightEntityName, StringComparer.Ordinal)
                .ThenBy(j => j.LeftCollectionNavigationName, StringComparer.Ordinal)
                .ThenBy(j => j.RightCollectionNavigationName, StringComparer.Ordinal)
                .ThenBy(j => j.JoinTableKey, StringComparer.Ordinal))
            {
                AppendManyToManyConfiguration(sb, join);
            }
        }

        private static void AppendManyToManyConfiguration(StringBuilder sb, ScaffoldManyToManyJoinInfo join)
        {
            var left = ScaffoldNameHelper.EscapeCSharpIdentifier(join.LeftEntityName);
            var right = ScaffoldNameHelper.EscapeCSharpIdentifier(join.RightEntityName);
            var collection = ScaffoldNameHelper.EscapeCSharpIdentifier(join.LeftCollectionNavigationName);
            var inverseCollection = ScaffoldNameHelper.EscapeCSharpIdentifier(join.RightCollectionNavigationName);
            var joinTable = EscapeStringLiteral(join.JoinTableName);
            var joinSchema = join.JoinTableSchema is null ? null : EscapeStringLiteral(join.JoinTableSchema);
            var leftKey = FormatScaffoldKeySelector("p", join.LeftPrincipalKeyProperties);
            var rightKey = FormatScaffoldKeySelector("p", join.RightPrincipalKeyProperties);
            sb.AppendLine($"            mb.Entity<{left}>()");
            sb.AppendLine($"                .HasMany<{right}>(p => p.{collection})");
            sb.AppendLine($"                .WithMany(p => p.{inverseCollection})");
            sb.AppendLine($"                {FormatManyToManyUsingTableCall(join, joinTable, joinSchema, leftKey, rightKey)}");
        }

        private static string FormatManyToManyUsingTableCall(
            ScaffoldManyToManyJoinInfo join,
            string joinTable,
            string? joinSchema,
            string leftKey,
            string rightKey)
        {
            var schemaArgument = joinSchema is null ? string.Empty : $", schema: \"{joinSchema}\"";
            if (RequiresExplicitManyToManyReferentialActions(join))
                return FormatManyToManyUsingTableWithReferentialActions(join, joinTable, schemaArgument, leftKey, rightKey);

            if (joinSchema is null && !join.IsComposite && join.UsesPrimaryKeys)
                return $".UsingTable(\"{joinTable}\", \"{EscapeStringLiteral(join.LeftForeignKeyColumn)}\", \"{EscapeStringLiteral(join.RightForeignKeyColumn)}\");";

            if (joinSchema is null && join.UsesPrimaryKeys)
                return $".UsingTable(\"{joinTable}\", {FormatStringArrayLiteral(join.LeftForeignKeyColumns)}, {FormatStringArrayLiteral(join.RightForeignKeyColumns)});";

            if (joinSchema is null && !join.IsComposite)
                return $".UsingTable(\"{joinTable}\", \"{EscapeStringLiteral(join.LeftForeignKeyColumn)}\", \"{EscapeStringLiteral(join.RightForeignKeyColumn)}\", {leftKey}, {rightKey});";

            if (joinSchema is null)
                return $".UsingTable(\"{joinTable}\", {FormatStringArrayLiteral(join.LeftForeignKeyColumns)}, {FormatStringArrayLiteral(join.RightForeignKeyColumns)}, {leftKey}, {rightKey});";

            if (!join.IsComposite && join.UsesPrimaryKeys)
                return $".UsingTable(\"{joinTable}\", \"{EscapeStringLiteral(join.LeftForeignKeyColumn)}\", \"{EscapeStringLiteral(join.RightForeignKeyColumn)}\", schema: \"{joinSchema}\");";

            if (join.UsesPrimaryKeys)
                return $".UsingTable(\"{joinTable}\", {FormatStringArrayLiteral(join.LeftForeignKeyColumns)}, {FormatStringArrayLiteral(join.RightForeignKeyColumns)}, schema: \"{joinSchema}\");";

            if (!join.IsComposite)
                return $".UsingTable(\"{joinTable}\", \"{EscapeStringLiteral(join.LeftForeignKeyColumn)}\", \"{EscapeStringLiteral(join.RightForeignKeyColumn)}\", {leftKey}, {rightKey}, schema: \"{joinSchema}\");";

            return $".UsingTable(\"{joinTable}\", {FormatStringArrayLiteral(join.LeftForeignKeyColumns)}, {FormatStringArrayLiteral(join.RightForeignKeyColumns)}, {leftKey}, {rightKey}, schema: \"{joinSchema}\");";
        }

        private static string FormatManyToManyUsingTableWithReferentialActions(
            ScaffoldManyToManyJoinInfo join,
            string joinTable,
            string schemaArgument,
            string leftKey,
            string rightKey)
        {
            var leftOnDelete = FormatReferentialAction(join.LeftOnDelete);
            var leftOnUpdate = FormatReferentialAction(join.LeftOnUpdate);
            var rightOnDelete = FormatReferentialAction(join.RightOnDelete);
            var rightOnUpdate = FormatReferentialAction(join.RightOnUpdate);
            return join.UsesPrimaryKeys
                ? $".UsingTable(\"{joinTable}\", {FormatStringArrayLiteral(join.LeftForeignKeyColumns)}, {FormatStringArrayLiteral(join.RightForeignKeyColumns)}, {leftOnDelete}, {leftOnUpdate}, {rightOnDelete}, {rightOnUpdate}{schemaArgument});"
                : $".UsingTable(\"{joinTable}\", {FormatStringArrayLiteral(join.LeftForeignKeyColumns)}, {FormatStringArrayLiteral(join.RightForeignKeyColumns)}, {leftKey}, {rightKey}, {leftOnDelete}, {leftOnUpdate}, {rightOnDelete}, {rightOnUpdate}{schemaArgument});";
        }

        private static void AppendScaffoldContextFooter(StringBuilder sb)
        {
            sb.AppendLine("            OnModelCreatingPartial(mb);");
            sb.AppendLine("        };");
            sb.AppendLine("        return configuredOptions;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static partial void OnModelCreatingPartial(ModelBuilder modelBuilder);");
            sb.AppendLine();
            sb.AppendLine("}");
        }

        private static void AppendSequenceStubs(
            StringBuilder sb,
            IReadOnlyList<ScaffoldContextSequenceInfo> sequenceStubs,
            HashSet<string> memberNames,
            bool useDatabaseNames)
            => ScaffoldSequenceStubWriter.AppendSequenceStubs(sb, sequenceStubs, memberNames, useDatabaseNames);

        private static HashSet<string> CreateReservedContextMemberNameSet()
        {
            var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var member in typeof(DbContext).GetMembers())
                names.Add(member.Name);
            foreach (var member in typeof(object).GetMembers())
                names.Add(member.Name);
            names.Add("ConfigureOptions");
            return names;
        }

        private static bool IsLegacyCascadeShape(ScaffoldContextRelationshipInfo relationship)
            => (string.Equals(relationship.OnDelete, "CASCADE", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(relationship.OnDelete, "NO ACTION", StringComparison.OrdinalIgnoreCase))
               && string.Equals(relationship.OnUpdate, "NO ACTION", StringComparison.OrdinalIgnoreCase);

        private static string FormatReferentialAction(string action)
            => NormalizeReferentialAction(action) switch
            {
                "CASCADE" => "ReferentialAction.Cascade",
                "SET NULL" => "ReferentialAction.SetNull",
                "RESTRICT" => "ReferentialAction.Restrict",
                "SET DEFAULT" => "ReferentialAction.SetDefault",
                _ => "ReferentialAction.NoAction"
            };

        private static bool RequiresExplicitManyToManyReferentialActions(ScaffoldManyToManyJoinInfo join)
            => !IsDefaultReferentialAction(join.LeftOnDelete)
               || !IsDefaultReferentialAction(join.LeftOnUpdate)
               || !IsDefaultReferentialAction(join.RightOnDelete)
               || !IsDefaultReferentialAction(join.RightOnUpdate);

        private static bool IsDefaultReferentialAction(string action)
            => string.Equals(NormalizeReferentialAction(action), "NO ACTION", StringComparison.OrdinalIgnoreCase);

        private static string NormalizeReferentialAction(string? action)
            => string.IsNullOrWhiteSpace(action)
                ? "NO ACTION"
                : action.Replace('_', ' ').Trim().ToUpperInvariant();

        private static string FormatScaffoldKeySelector(string parameterName, IReadOnlyList<string> propertyNames)
        {
            if (propertyNames.Count == 1)
                return $"{parameterName} => {parameterName}.{ScaffoldNameHelper.EscapeCSharpIdentifier(propertyNames[0])}";

            return $"{parameterName} => new {{ {string.Join(", ", propertyNames.Select(name => parameterName + "." + ScaffoldNameHelper.EscapeCSharpIdentifier(name)))} }}";
        }

        private static string FormatStringArrayLiteral(IReadOnlyList<string> values)
            => "new[] { " + string.Join(", ", values.Select(value => "\"" + EscapeStringLiteral(value) + "\"")) + " }";

        private static void AppendNullableDirective(StringBuilder sb, bool useNullableReferenceTypes)
            => sb.AppendLine(useNullableReferenceTypes ? "#nullable enable" : "#nullable disable");
    }
}
