#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using nORM.Core;

namespace nORM.Scaffolding
{
    internal static partial class ScaffoldContextWriter
    {
        private static void AppendScaffoldContextHeader(
            StringBuilder sb,
            string namespaceName,
            string contextName,
            bool hasRoutineStubs,
            bool hasSequenceStubs,
            bool needsSystemUsing,
            bool useNullableReferenceTypes,
            string? entityNamespaceName)
        {
            var needsEntityNamespaceUsing = !string.IsNullOrWhiteSpace(entityNamespaceName)
                                            && !string.Equals(namespaceName, entityNamespaceName, StringComparison.Ordinal);
            sb.AppendLine("// <auto-generated/>");
            AppendNullableDirective(sb, useNullableReferenceTypes);
            sb.AppendLine("using System.Data.Common;");
            if (hasRoutineStubs || hasSequenceStubs)
            {
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using System.Threading;");
                sb.AppendLine("using System.Threading.Tasks;");
            }

            sb.AppendLine("using System.Linq;");
            if (needsSystemUsing)
                sb.AppendLine("using System;");
            sb.AppendLine("using nORM.Core;");
            sb.AppendLine("using nORM.Configuration;");
            sb.AppendLine("using nORM.Providers;");
            if (needsEntityNamespaceUsing)
                sb.AppendLine($"using {entityNamespaceName};");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
            sb.AppendLine($"public partial class {ScaffoldNameHelper.EscapeCSharpIdentifier(contextName)} : DbContext");
            sb.AppendLine("{");
        }

        private static HashSet<string> AppendScaffoldContextConstructorsAndQueries(
            StringBuilder sb,
            string contextName,
            IEnumerable<string> entities,
            bool pluralizeQueryProperties,
            bool useNullableReferenceTypes)
        {
            var safeContext = ScaffoldNameHelper.EscapeCSharpIdentifier(contextName);
            var nullableReferenceSuffix = useNullableReferenceTypes ? "?" : string.Empty;
            sb.AppendLine($"    public {safeContext}(DbConnection cn, DatabaseProvider provider, DbContextOptions{nullableReferenceSuffix} options = null) : base(cn, provider, ConfigureOptions(options)) {{ }}");
            sb.AppendLine($"    public {safeContext}(string connectionString, DatabaseProvider provider, DbContextOptions{nullableReferenceSuffix} options = null) : base(connectionString, provider, ConfigureOptions(options)) {{ }}");
            sb.AppendLine();

            var queryPropertyNames = CreateReservedContextMemberNameSet();
            foreach (var entity in entities.OrderBy(e => e))
            {
                var safeEntity = ScaffoldNameHelper.EscapeCSharpIdentifier(entity);
                var queryPropertyBase = pluralizeQueryProperties ? ScaffoldNameHelper.Pluralize(safeEntity) : safeEntity;
                var queryProperty = ScaffoldNameHelper.MakeUnique(queryPropertyBase, queryPropertyNames);
                sb.AppendLine($"    public IQueryable<{safeEntity}> {queryProperty} => this.Query<{safeEntity}>();");
            }

            return queryPropertyNames;
        }

        private static void AppendConfigureOptionsStart(StringBuilder sb, bool useNullableReferenceTypes)
        {
            var nullableReferenceSuffix = useNullableReferenceTypes ? "?" : string.Empty;
            sb.AppendLine();
            sb.AppendLine($"    private static DbContextOptions ConfigureOptions(DbContextOptions{nullableReferenceSuffix} options)");
            sb.AppendLine("    {");
            sb.AppendLine("        var configuredOptions = options?.Clone() ?? new DbContextOptions();");
            sb.AppendLine("        var configure = configuredOptions.OnModelCreating;");
            sb.AppendLine("        configuredOptions.OnModelCreating = mb =>");
            sb.AppendLine("        {");
            sb.AppendLine("            configure?.Invoke(mb);");
        }

        private static void AppendScaffoldContextFooter(StringBuilder sb)
        {
            sb.AppendLine("            OnModelCreatingPartial(mb);");
            sb.AppendLine("        };");
            sb.AppendLine("        return configuredOptions;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static partial void OnModelCreatingPartial(ModelBuilder modelBuilder);");
            sb.AppendLine();
            sb.AppendLine("}");
        }

        private static void AppendSequenceStubs(
            StringBuilder sb,
            IReadOnlyList<ScaffoldContextSequenceInfo> sequenceStubs,
            HashSet<string> memberNames,
            bool useDatabaseNames)
            => ScaffoldSequenceStubWriter.AppendSequenceStubs(sb, sequenceStubs, memberNames, useDatabaseNames);

        private static HashSet<string> CreateReservedContextMemberNameSet()
        {
            var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var member in typeof(DbContext).GetMembers())
                names.Add(member.Name);
            foreach (var member in typeof(object).GetMembers())
                names.Add(member.Name);
            names.Add("ConfigureOptions");
            return names;
        }

        private static void AppendNullableDirective(StringBuilder sb, bool useNullableReferenceTypes)
            => sb.AppendLine(useNullableReferenceTypes ? "#nullable enable" : "#nullable disable");
    }
}
